### ISSUE TITLE
Wrong display in wallabag

### ISSUE THREAD

**Issue by j0k3r** [wallabag/wallabag#3904] opened 2019-03-11 17:29 UTC
*Sent by Randy Haupt and automatically created by email*

---

https://askubuntu.com/questions/299747/converting-epub-files-to-pdf-format/2
99752#299752 
No matter what I try, above link and
- https://askubuntu.com/questions/299747/converting-epub-files-to-pdf-format
-
https://askubuntu.com/questions/299747/converting-epub-files-to-pdf-format?a
nswertab=votes#tab-top
-
https://askubuntu.com/questions/299747/converting-epub-files-to-pdf-format?a
nswertab=oldest#tab-top

always copies the answer from
https://askubuntu.com/questions/299747/converting-epub-files-to-pdf-format/9
54582#954582

**Comment by Kdecherf** [comment] 2019-03-12 21:34
Like for #3906, could be a duplicate of #3644

**Closed** 2019-06-26 18:10 UTC
Labels: Site Config
