### ISSUE TITLE
Mise à jour vers 2.5.3 erreur

### ISSUE THREAD

**Issue by qwertygc** [wallabag/wallabag#6273] opened 2023-02-02 10:29 UTC
Bonjour,

Je suis sur un mutualisé. Je met à jour du 2.5.2 vers 2.5.3, en renplaçant le fichier app/config/parameters.yml par mon fichier. J'ai cette erreur :

` Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\RuntimeException: Class "Doctrine\Bundle\FixturesBundle\Fixture" not found while loading "Wallabag\AnnotationBundle\DataFixtures\AnnotationFixtures". in /wallabag/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/DefinitionErrorExceptionPass.php:54 Stack trace: #0 /wallabag/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(83): Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->processValue() #1 /wallabag/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/DefinitionErrorExceptionPass.php(32): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue() #2 /wallabag/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(47): Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->processValue() #3 /wallabag/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php(94): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->process() #4 /wallabag/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(762): Symfony\Component\DependencyInjection\Compiler\Compiler->compile() #5 /wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(594): Symfony\Component\DependencyInjection\ContainerBuilder->compile() #6 /wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(136): Symfony\Component\HttpKernel\Kernel->initializeContainer() #7 /wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(196): Symfony\Component\HttpKernel\Kernel->boot() #8 /wallabag/web/app.php(13): Symfony\Component\HttpKernel\Kernel->handle() #9 {main} thrown in /wallabag/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/DefinitionErrorExceptionPass.php on line 54`

J'ai suivi la procédure de la documentation (téléchargement de https://wllbg.org/latest-v2-package, décompression, envoi sur le serveur par FTP, vidage du cache)

Merci

**Comment by nicosomb** [comment] 2023-02-02 10:36
Hello @qwertygc. 

Did you run `make install` command?

**Comment by nsteinmetz** [comment] 2023-02-02 12:09
Same case here, as I need to override php version for alwaysdata:

```
SYMPHONY_ENV=prod /usr/alwaysdata/php/7.4.33/bin/php -c ~/admin/config/php/php-691511.ini composer.phar install --no-dev -o --prefer-dist --ignore-platform-req=ext-tidy --ignore-platform-req=ext-sodium --ignore-platform-req=ext-sockets
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package guzzlehttp/ringphp is abandoned, you should avoid using it. No replacement was suggested.
Package guzzlehttp/streams is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/compiler is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/consistency is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/event is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/exception is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/file is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/iterator is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/math is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/protocol is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/regex is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/ruler is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/stream is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/ustring is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/visitor is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/zformat is abandoned, you should avoid using it. No replacement was suggested.
Package sensio/framework-extra-bundle is abandoned, you should avoid using it. Use Symfony instead.
Package true/punycode is abandoned, you should avoid using it. No replacement was suggested.
Package php-cs-fixer/diff is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
Class SimpleHtmlDom\simple_html_dom_node located in ./vendor/mgargano/simplehtmldom/src/simple_html_dom.php does not comply with psr-0 autoloading standard. Skipping.
Class SimpleHtmlDom\simple_html_dom located in ./vendor/mgargano/simplehtmldom/src/simple_html_dom.php does not comply with psr-0 autoloading standard. Skipping.
55 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> bin/console cache:clear --no-warmup

Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DoctrineFixturesBundle" from namespace "Doctrine\Bundle\FixturesBundle".
Did you forget a "use" statement for another namespace? in /home/cerenit/steinmetz/wallabag/app/AppKernel.php:50
Stack trace:
#0 /home/cerenit/steinmetz/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(446): AppKernel->registerBundles()
#1 /home/cerenit/steinmetz/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(133): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /home/cerenit/steinmetz/wallabag/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(169): Symfony\Component\HttpKernel\Kernel->boot()
#3 /home/cerenit/steinmetz/wallabag/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(75): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
#4 /home/cerenit/steinmetz/wallabag/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(149): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /home/cerenit/steinmetz/wallabag/bin/console(27): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#6 {main}
  thrown in /home/cerenit/steinmetz/wallabag/app/AppKernel.php on line 50
Script bin/console cache:clear --no-warmup handling the post-cmd event returned with error code 255
Script @post-cmd was called via post-install-cmd
```

**Comment by nicosomb** [comment] 2023-02-02 12:49
@nsteinmetz could you try `bin/console cache:clear -e prod` ?

**Comment by nsteinmetz** [comment] 2023-02-02 18:19
@nicosomb same output:

```
/usr/alwaysdata/php/7.4.33/bin/php -c ~/admin/config/php/php-691511.ini bin/console clear:cache --e prod

In DefinitionErrorExceptionPass.php line 54:

  Class "Doctrine\Bundle\FixturesBundle\Fixture" not found while loading "Wallabag\AnnotationBundle\DataFixtures\Annotat
  ionFixtures".
```

**Comment by qwertygc** [comment] 2023-02-02 18:41
> Hello @qwertygc.
> 
> Did you run `make install` command?

I can't it's a shared host.

**Comment by j0k3r** [comment] 2023-02-02 19:16
@nsteinmetz It's not `--e` it's `-e` or `--env=prod`

@qwertygc Package deprecation has nothing to do with the error.

**Comment by nsteinmetz** [comment] 2023-02-02 20:16
@j0k3r I edited indeed - it's the same output at the end

**Comment by j0k3r** [comment] 2023-02-03 08:48
The problem comes from the tar.gz.
Duplicate of #6269

**Closed by j0k3r** 2023-02-03 08:48 UTC

**Comment by nsteinmetz** [comment] 2023-02-03 10:30
@j0k3r thanks a lot - works now as expected 😎
