### ISSUE TITLE
`published_by` can sometimes be an array of null

### ISSUE THREAD

**Issue by ghost** [wallabag/wallabag#3867] opened 2019-01-27 22:43 UTC
### Issue details

As described in https://github.com/swalladge/wallabag-rs/issues/1, `published_by` for an entry can sometimes be set by the server to an array containing nulls (instead of the expected single null). Observed with this url: <https://www.newyorker.com/magazine/2018/03/05/donald-glover-cant-save-you>. Wallabag reports issues with retrieving the content for the article, but ideally this shouldn't result in unexpected or non deterministic formats of the data.

### Environment

* wallabag version (or git revision) that exhibits the issue: wallabag 2.3.6 (app.wallabag.it)

### Steps to reproduce/test case

1. save the above article
2. observe the json returned for the entry

**Comment by j0k3r** [comment] 2019-06-06 12:21
As newyorker doesn't work anymore it could be great to have an other link to reproduce the bug.

**Comment by j0k3r** [comment] 2019-07-10 12:01
ping @swalladge

**Comment by swalladge** [comment] 2019-07-10 12:28
@j0k3r Ah yes sorry I haven't done any work on this for a while, so haven't found any more links to reproduce this. I'll dig into it this weekend if I have time. Thanks for the ping. :)

**Comment by swalladge** [comment] 2019-07-13 13:32
@j0k3r so I didn't have time to find another url to reproduce the issue, but I did some digging - traced the potential entry point of the nulls to [updateEntry](https://github.com/wallabag/wallabag/blob/4910361ac4c5bcf662e99d9de407d572ce1d731e/src/Wallabag/CoreBundle/Helper/ContentProxy.php#L48). It's possible that it's an issue in Graby that is returning the nulls, or somewhere else up the chain is giving it in the $content argument. Perhaps some logic to sanitize the field could be added to the bottom of updateEntry? (there is already some other sanitization code there) That would be a simple fix, but will need more looking to see if this original issue has been since fixed, or to track down where this array of nulls is actually generated in the first place.

**Comment by j0k3r** [comment] 2019-07-13 14:19
If you can provide me an url I can also give a look

**Comment by ngosang** [comment] 2019-08-26 18:54
@j0k3r I get an array
Wallabag 2.3.8
 https://www.newyorker.com/magazine/2016/02/29/a-new-generation-of-airships-is-born?mbid=rss

**Comment by j0k3r** [comment] 2019-08-27 07:20
Yeah it fails for me too on the master. Looks like a bug in Readability

**Comment by nicosomb** [comment] 2023-06-21 11:11
I tried this URL `https://www.newyorker.com/magazine/2016/02/29/a-new-generation-of-airships-is-born?mbid=rss` and it seems ok on app.wallabag.it. 

@ngosang @swalladge could you tell me if it's ok for you?

**Comment by ngosang** [comment] 2023-07-02 21:55
It's working in 2.6.1. I think you can close this issue.

**Closed** 2023-07-03 05:41 UTC
Labels: Bug
