### ISSUE TITLE
Fetching article https://gafferongames.com/post/serialization_strategies/ does not work correctly

### ISSUE THREAD

**Issue by opcon** [wallabag/wallabag#3400] opened 2017-11-02 04:27 UTC
### Issue details

Fetching [this url](https://gafferongames.com/post/serialization_strategies/) in wallabag produces the following article:

![wallabag](https://user-images.githubusercontent.com/2180488/32309642-2a0248a6-bfe1-11e7-88a3-0c0996f32675.png)

It looks like wallabag is cutting off the first half of the article, and starting in a `<pre>` tag.

This same url works fine on https://f43.me/feed/test

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.3
* How did you install wallabag? Using the [docker](https://github.com/wallabag/docker) repository with the suggested docker-compose file.
* php version: php7
* OS: Docker on Linux
* type of hosting (shared or dedicated): Dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MariaDB

### Steps to reproduce/test case

Fetch the following url in wallabag and compare with the original article.

https://gafferongames.com/post/serialization_strategies/

Thanks for your help :smile:

**Comment by nico202** [comment] 2017-11-02 07:13
I can reproduce it

**Comment by docljn** [comment] 2018-08-13 15:38
Is this still a concern, @opcon ?

**Comment by opcon** [comment] 2018-10-18 15:56
Hi @docljn, sorry for the late reply. I still have the same problem on Wallabag version 2.3.3

**Comment by techexo** [comment] 2018-11-27 20:54
@opcon Can't reproduce the error with my instance. Could you try with latest wallabag release (https://github.com/wallabag/docker/releases/tag/2.3.4)?

**Comment by j0k3r** [comment] 2019-01-11 12:43
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Closed by j0k3r** 2019-01-11 12:43 UTC
Labels: Awaiting response, Site Config
