### ISSUE TITLE
Login Page is blank

### ISSUE THREAD

**Issue by throwawa12** [wallabag/wallabag#3175] opened 2017-06-01 19:30 UTC
### Issue details
First of all i am using apache2, and various things here have been renamed for privacy
When i go to mysite.com/wallabag it redirects successfully to https://mysite.com/wallabag/login
(i have a alias set up in mysite.conf) which is Alias /wallabag "/var/www/HIDDEN/wallabag/web"

the page is COMPLETELY blank, no errors or anything

The only log in wallabag/var/logs/ is prod.conf which is empty

### Environment

* wallabag version (or git revision) that exhibits the issue: latest
* How did you install wallabag? Via `git clone` or by downloading the package?git clone
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7 (latest)
* OS:ubuntu server 16.04
* type of hosting (shared or dedicated):dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):sqlite

### Steps to reproduce/test case

Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies, if possible).

**Comment by j0k3r** [comment] 2017-06-01 20:42
Well, that'll be hard to investigate...
Did you check apache log? Did you enable rewrite log on apache and set them to be more verbose? Did you find something in syslog during the test period?

**Comment by throwawa12** [comment] 2017-06-01 23:14
https://pastebin.com/8FZQRhdH

here is the apache error.log with trace8 on

nothing of note in syslog

**Comment by j0k3r** [comment] 2017-06-02 05:07
Did you check php error log if enable?

**Comment by iav** [comment] 2017-06-27 02:44
Check if apache can write into wallabag/var/logs and have right to overwrite existing log file. 
Disable selinux if enabled.

**Comment by LibertatisPrius** [comment] 2017-07-05 17:10
I ran into this problem last night; absolutely blank page (no html even) after properly redirecting from /wallabag to /wallabag/login. I found the problem was ownership of a handful of folders & files; the tutorial I was using didn't cover setting up proper ownership. The proper settings are given here - https://doc.wallabag.org/en/admin/installation/rightaccess.html.

Everything works as expected after changing ownership of 
>/wallabag/web
/wallabag/var
/wallabag/bin/
/wallabag/app/config/
/wallabag/vendor/
/wallabag/data/

to www-data:www-data.

**Comment by j0k3r** [comment] 2017-07-06 06:21
@throwawa12 Could you try what @LibertatisPrius says?

**Comment by cavebeat** [comment] 2017-07-26 18:04
hi,

i guess i have the same problem. 

my setup is as follows: 
LXC Container, lan-IP 192.168.100.222 and local dns bag.mydomain.lan 
Debian Stretch, Apache2, install via git clone, redis and mysql on different IP/container also Debian Stretch. 

> root@bag:/var/www# apache2 -v       
> Server version: Apache/2.4.25 (Debian)
> Server built:   2017-07-18T18:37:33

make run works without any problems on 127.0.0.1:8000

wallabag folder is placed in /var/www/
root@bag:/var/www# chown www-data:www-data wallabag/ -R


vHosts file 000-default.conf is disabled. 

wallabag vHost is used from docu
>    ServerName bag.mydomain.tld
>    ServerAlias bag.mydomain.lan


> root@bag:/etc/apache2/sites-available# apache2ctl -S
> VirtualHost configuration:
> *:80                   bag.mydomain.tld (/etc/apache2/sites-enabled/100-wallabag.conf:1)
> ServerRoot: "/etc/apache2"
> Main DocumentRoot: "/var/www/html"
> Main ErrorLog: "/var/log/apache2/error.log"
> Mutex default: dir="/var/run/apache2/" mechanism=default 
> Mutex mpm-accept: using_defaults
> Mutex watchdog-callback: using_defaults
> Mutex rewrite-map: using_defaults
> PidFile: "/var/run/apache2/apache2.pid"
> Define: DUMP_VHOSTS
> Define: DUMP_RUN_CFG
> User: name="www-data" id=33
> Group: name="www-data" id=33

> root@bag:/var/www# apache2ctl -M | grep rewrite
>  rewrite_module (shared)


any idea? 

When i enter 192.168.100.222 or bag.mydomain.lan i get forwarded to http://bag.mydomain.lan/login, 
same happens with http://192.168.100.222/ -> http://192.168.100.222/login
but the page is completely empty. similar or same problem like the OP

**Comment by j0k3r** [comment] 2017-07-26 20:55
What's in the var/logs/prod.log of wallabag ?

**Comment by cavebeat** [comment] 2017-07-27 19:35
hi, 

> root@bag:/var/log/apache2# ls -lha
> total 20K
> drwxr-x--- 2 root adm  4.0K Jul 27 21:26 .
> drwxr-xr-x 4 root root 4.0K Jul 27 06:44 ..
> -rw-r----- 1 root adm     0 Jul 27 21:26 access.log
> -rw-r----- 1 root adm  1.8K Jul 27 21:31 error.log
> -rw-r----- 1 root adm     0 Jul 27 06:44 other_vhosts_access.log
> -rw-r--r-- 1 root adm   301 Jul 27 21:31 wallabag_access.log
> -rw-r--r-- 1 root adm  1.4K Jul 27 21:31 wallabag_error.log


i set LogLevel from warn to debug, emptied all logs, and rebooted. 


> root@bag:/var/log/apache2# tail *
> ==> access.log <==
> 
> ==> error.log <==
> [Thu Jul 27 21:27:08.185405 2017] [watchdog:debug] [pid 163] mod_watchdog.c(563): AH02980: Watchdog: nothing configured?
> [Thu Jul 27 21:27:08.186007 2017] [watchdog:debug] [pid 164] mod_watchdog.c(563): AH02980: Watchdog: nothing configured?
> [Thu Jul 27 21:27:08.191180 2017] [mpm_prefork:notice] [pid 143] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
> [Thu Jul 27 21:27:08.191242 2017] [mpm_prefork:info] [pid 143] AH00164: Server built: 2017-07-18T18:37:33
> [Thu Jul 27 21:27:08.191262 2017] [core:notice] [pid 143] AH00094: Command line: '/usr/sbin/apache2'
> [Thu Jul 27 21:27:08.191269 2017] [core:debug] [pid 143] log.c(1546): AH02639: Using SO_REUSEPORT: yes (1)
> [Thu Jul 27 21:27:08.191297 2017] [mpm_prefork:debug] [pid 143] prefork.c(1032): AH00165: Accept mutex: none (default: sysvsem)
> [Thu Jul 27 21:27:08.193118 2017] [watchdog:debug] [pid 168] mod_watchdog.c(563): AH02980: Watchdog: nothing configured?
> [Thu Jul 27 21:27:08.193711 2017] [watchdog:debug] [pid 167] mod_watchdog.c(563): AH02980: Watchdog: nothing configured?
> [Thu Jul 27 21:27:08.194302 2017] [watchdog:debug] [pid 169] mod_watchdog.c(563): AH02980: Watchdog: nothing configured?
> 
> ==> other_vhosts_access.log <==
> 
> ==> wallabag_access.log <==
> 
> ==> wallabag_error.log <==
> root@bag:/var/log/apache2# 

went to the browser, and opened bag.mydomain.lan 

> root@bag:/var/log/apache2# tail *
> ==> access.log <==
> 
> ==> error.log <==
> [Thu Jul 27 21:27:08.186007 2017] [watchdog:debug] [pid 164] mod_watchdog.c(563): AH02980: Watchdog: nothing configured?
> [Thu Jul 27 21:27:08.191180 2017] [mpm_prefork:notice] [pid 143] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
> [Thu Jul 27 21:27:08.191242 2017] [mpm_prefork:info] [pid 143] AH00164: Server built: 2017-07-18T18:37:33
> [Thu Jul 27 21:27:08.191262 2017] [core:notice] [pid 143] AH00094: Command line: '/usr/sbin/apache2'
> [Thu Jul 27 21:27:08.191269 2017] [core:debug] [pid 143] log.c(1546): AH02639: Using SO_REUSEPORT: yes (1)
> [Thu Jul 27 21:27:08.191297 2017] [mpm_prefork:debug] [pid 143] prefork.c(1032): AH00165: Accept mutex: none (default: sysvsem)
> [Thu Jul 27 21:27:08.193118 2017] [watchdog:debug] [pid 168] mod_watchdog.c(563): AH02980: Watchdog: nothing configured?
> [Thu Jul 27 21:27:08.193711 2017] [watchdog:debug] [pid 167] mod_watchdog.c(563): AH02980: Watchdog: nothing configured?
> [Thu Jul 27 21:27:08.194302 2017] [watchdog:debug] [pid 169] mod_watchdog.c(563): AH02980: Watchdog: nothing configured?
> [Thu Jul 27 21:31:18.440341 2017] [watchdog:debug] [pid 343] mod_watchdog.c(563): AH02980: Watchdog: nothing configured?
> 
> ==> other_vhosts_access.log <==
> 
> ==> wallabag_access.log <==
> 192.168.100.45 - - [27/Jul/2017:21:31:18 +0200] "GET / HTTP/1.1" 302 643 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0"
> 192.168.100.45 - - [27/Jul/2017:21:31:19 +0200] "GET /login HTTP/1.1" 200 236 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0"
> 
> ==> wallabag_error.log <==
> [Thu Jul 27 21:31:18.183502 2017] [authz_core:debug] [pid 163] mod_authz_core.c(809): [client 192.168.100.45:41013] AH01626: authorization result of Require all granted: granted
> [Thu Jul 27 21:31:18.183594 2017] [authz_core:debug] [pid 163] mod_authz_core.c(809): [client 192.168.100.45:41013] AH01626: authorization result of <RequireAny>: granted
> [Thu Jul 27 21:31:18.183839 2017] [authz_core:debug] [pid 163] mod_authz_core.c(809): [client 192.168.100.45:41013] AH01626: authorization result of Require all granted: granted
> [Thu Jul 27 21:31:18.183850 2017] [authz_core:debug] [pid 163] mod_authz_core.c(809): [client 192.168.100.45:41013] AH01626: authorization result of <RequireAny>: granted
> [Thu Jul 27 21:31:19.122504 2017] [authz_core:debug] [pid 163] mod_authz_core.c(809): [client 192.168.100.45:41013] AH01626: authorization result of Require all granted: granted
> [Thu Jul 27 21:31:19.122550 2017] [authz_core:debug] [pid 163] mod_authz_core.c(809): [client 192.168.100.45:41013] AH01626: authorization result of <RequireAny>: granted
> [Thu Jul 27 21:31:19.122626 2017] [authz_core:debug] [pid 163] mod_authz_core.c(809): [client 192.168.100.45:41013] AH01626: authorization result of Require all granted: granted
> [Thu Jul 27 21:31:19.122636 2017] [authz_core:debug] [pid 163] mod_authz_core.c(809): [client 192.168.100.45:41013] AH01626: authorization result of <RequireAny>: granted


any other logs needed?

**Comment by j0k3r** [comment] 2017-07-27 19:46
Could you check for logs in `/var/www/var/logs` instead?

**Comment by cavebeat** [comment] 2017-07-27 19:49
Have never seen in /var/www any logs or var directory. 
 
> root@bag:/var/www# ls -lha
> total 16K
> drwxr-xr-x  4 root     root     4.0K Jul 26 19:06 .
> drwxr-xr-x 12 root     root     4.0K Jul 25 21:51 ..
> drwxr-xr-x  2 www-data www-data 4.0K Jul 26 23:09 html
> drwxr-xr-x 15 www-data www-data 4.0K Jul 26 23:07 wallabag

**Comment by j0k3r** [comment] 2017-07-27 20:15
Well, then looks inside `/var/www/wallabag/var/logs`.

**Comment by cavebeat** [comment] 2017-07-27 20:58
ya, there is something. 

> root@bag:/var/www/wallabag/var/logs# cat prod.log 
> [2017-07-26 17:34:14] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /web/login" (from "http://192.168.100.222/")" at /var/www/wallabag/var/cache/prod/classes.php line 3941 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /web/login\" (from \"http://192.168.100.222/\") at /var/www/wallabag/var/cache/prod/classes.php:3941, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/wallabag/var/cache/prod/appProdProjectContainerUrlMatcher.php:880)"} []

**Comment by cavebeat** [comment] 2017-07-27 21:36
gnahh,... same behaviour with ngin-x... wtf

the internal php server works with 
> php bin/console wallabag:install --env=prod
and 
> ssh -L 8000:localhost:8000 root@bag.mydomain.lan

**Comment by j0k3r** [comment] 2017-07-28 05:40
It looks like your `DocumentRoot` is wrong with `/var/www/html` it should be `/var/www/wallabag/web`

**Comment by cavebeat** [comment] 2017-07-28 17:16
good news, it's working. 
i did again chown -R  www-data the whole /var/www directory and chmod 0755 the /var/www -R and it worked... 
so i destroyed the instance. 
create 2 new debian boxes and installed Wallabag again, and again. to nail and reproduce the problem. 
But i failed and it worked both times... yay, reproducible **working** on debian stretch. 
i do not know, i guess some apache install/config fuckup appeared. 

thanks for your time and all your effort and help. 
i couldn't find the issue on bountysource, so i put some penny's on your liberapay profile. 

i do not know what @throwawa12 think's, but i'd vote to close the issue

**Comment by j0k3r** [comment] 2017-07-28 18:45
Thanks for the Liberapay 👍 
I'll put a label and if didn't have news in days I'll close that issue.

**Closed** 2017-08-26 08:50 UTC
Labels: Awaiting response
