### ISSUE TITLE
Not fetching theitbros.com title properly

### ISSUE THREAD

**Issue by andre-faria** [wallabag/wallabag#3915] opened 2019-03-22 18:29 UTC
Any saved article from theitbros.com are saved with title "theitbros" instead of the real article name.

Steps to reproduce/test case
Add any theitbros.com article to Wallabag
e.g: https://theitbros.com/configure-ntp-time-sync-group-policy/

wallabag version (or git revision) that exhibits the issue: 2.3.6
How did you install wallabag? Via git clone or by downloading the package? git clone
Last wallabag version that did not exhibit the issue (if applicable): N/A
php version: 7.2
OS: Ubuntu 18.04
type of hosting (shared or dedicated): dedicated
which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MariaDB

**Comment by techexo** [comment] 2019-04-07 23:43
Hi @andre-faria, I cannot reproduce this issue on my wallabag's instance (v 2.3.7). Could you check if you have the `php-tidy` package installed on your server, and if you can reproduce this issue after upgrading to the latest version of wallabag?

**Comment by andre-faria** [comment] 2019-04-09 16:49
@techexo, I've installed tidy package and still happening that, what is the best way to upgrade wallabag?

**Comment by techexo** [comment] 2019-04-09 21:29
You indicated that you installed it via `git clone`. You can thus do `make update` in wallabag's directory (or `sudo -u www-data make update`, according to your distribution's policy).

**Comment by andre-faria** [comment] 2019-04-10 13:25
@techexo, I was having issues to upgrade, but I figured out what was happening when you said to use `-u www-data,` after upgrade to latest version articles from this site are fetching fine.

I'm very grateful for you help!
Thank you.

**Comment by Kdecherf** [comment] 2019-04-14 11:34
:+1: 

I'm closing this issue then.

**Closed by Kdecherf** 2019-04-14 11:34 UTC
Labels: Site Config
