### ISSUE TITLE
Page Image not as expected the first but last offered image

### ISSUE THREAD

**Issue by gerhard-tinned** [wallabag/wallabag#3115] opened 2017-05-12 14:58 UTC
### Issue details

When a new page is saved, wallabag is collecting an image from the website. This is apperently done via the images offered in the html header section. If thius section offers more then one image wallabag chooses the last of them offered. (at least this is what i could observe)

Most sozial media sites behave differently by either choosing the first offered one or allow to choose one of the offered ones.

### Environment

* wallabag version: Docker 2.16 (because the latest docker image is broken)
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

Easiest way is to save this URL ... https://blog.tinned-software.net/restore-mysql-replication-after-error/

Instead of the image with the two servers, it shows the image of the blue "i"nfo icon. The html offers both images. The first one is the one with the tho servers the second one the "i" icon.

**Comment by j0k3r** [comment] 2017-05-12 15:14
Offering to choose which one to use will be too hard.
Choosing automatically the first one, the second one, ... or the last one won't apply to all websites.

Maybe the better option would be to allow user to define the preview picture (by defining an url) after saving the article.

What do you think?

**Comment by nicosomb** [comment] 2017-05-13 07:37
Is this issue a kind of duplicate of this one https://github.com/wallabag/wallabag/issues/1874?

**Comment by j0k3r** [comment] 2017-05-13 07:41
Kind of, maybe we close the other one and kept that one.

**Comment by benpro** [comment] 2017-05-18 18:53
As I understand, this is a feature request for preview image to:

- Not use a small picture as it will be ugly.
- Try to detect "a better" picture in the article page.

**Comment by gerhard-tinned** [comment] 2017-05-18 20:22
* Not use a small picture as it will be ugly.
That would be another option I did not think of. But I like this approach as well - tough not sure if it would be correct in all cases.

* Try to detect "a better" picture in the article page.
No, that would be to complicate. Just take the first image listed in the html not the last one. All sozial networks I know use the first offered image not the last one.

**Comment by j0k3r** [comment] 2017-06-02 19:57
Will be fixed in the upcoming 2.3.

**Closed** 2017-06-02 20:10 UTC
Labels: Feature
