### ISSUE TITLE
Fetch HTML as Browser requests it (login, useragent, ...)

### ISSUE THREAD

**Issue by Matthias84** [wallabag/wallabag#3925] opened 2019-04-13 18:29 UTC
### Issue details

A common pattern for paywalled webpages is, that paying customers can fetch all the content, but non logged in users can't. Sometimes they also allow the Google Bot to read all the content, too.

Unfortunatly wallabag tries to fetch the content by it's own request and the Mozilla addon doesn't send the already received page content to wallabag service. So the login / user agent / intranet page / ... might become unreadable

So I like to ask, if you see a way, to add an feature to transfer all of the current cached page content of your local browser to wallabag?

**Comment by Kdecherf** [comment] 2019-04-14 11:19
Hello @Matthias84, thanks for opening this issue but I'm closing it as a dup of #3251 

Duplicates #3251

**Comment by Kdecherf** [comment] 2019-04-14 11:20
Duplicate of #3251

**Closed by Kdecherf** 2019-04-14 11:19 UTC

**Comment by Matthias84** [comment] 2019-04-14 15:24
Thanks, I just didn't found this existing issue with search!
