### ISSUE TITLE
Search by tag

### ISSUE THREAD

**Issue by aleksandar-todorovic** [wallabag/wallabag#4125] opened 2019-09-25 10:39 UTC
### Issue details

I have plenty of tags, but realistically, I'm looking at one of them regularly. I'd like to get to it with the shortest friction possible.

#### What I have to do now

To get to the tag, I'd have to: 

1. Click on "Tags" in the sidebar
2. Search for it across 80ish tags I have.

#### What I'd like to have

1. ~~The tag available right on the sidebar.~~ duplicate of #3670 
2. An option to search for all items that have this tag. For example, typing "tag:tech" should return all items tagged with "tech".

**Comment by techexo** [comment] 2019-09-26 11:39
The second item seems quite clever to me, as it would need minor modification for the search module, as a special page already exists when looking for articles with a tag (`https://wallabag.tld/tag/list/tag_name`).

It is then "just" detecting `tag:tag_name` for the search and redirecting to the following articles-by-tag list.

**Comment by nicosomb** [comment] 2019-09-27 15:45
Is your issue a duplicate of #3670?

**Comment by aleksandar-todorovic** [comment] 2019-09-29 10:37
@nicosomb Yup, the first use case is definitely a duplicate of that bug.

I've edited the issue and its title so that it only refers to limiting search results via tags (example: "tag:tech").

**Comment by globalmatt** [comment] 2020-04-09 12:33
I might have a go at implementing this. Would it also be useful to be able to search multiple tags at once, a.k.a. tag intersection (#1197)? If so, what would be a good UI for that? "tags:tag1,tag2" in the search box, or something else? Thoughts?

**Comment by j0k3r** [comment] 2020-04-09 12:38
`tags:tag1,tag2` looks a good idea

**Comment by nicosomb** [comment] 2020-04-13 13:27
Is this issue https://github.com/wallabag/wallabag/issues/1197 a duplicate of this one?

**Comment by j0k3r** [comment] 2020-04-14 04:00
It is

**Closed** 2020-04-14 04:00 UTC
Labels: Feature

**Comment by condenseinform** [comment] 2022-03-02 04:26
Three tagalongs (same concept, so no separate ticket needed, right?):

```
title:(Clay OR "amazing adventures") AND Kavalier
```
Why not title-only searches with Boolean, parenthetical groupings and quoted phrases? Right now, quotes are searched for literally and all searches are phrase searches, but it'd be cool to be able to do this. (Maybe the capability to search for the quote character itself could be kept by escaping it with a backslash. E.g. `\"There and Back Again\"`)

```
url:eff.org
```
I imagine this one completing anywhere in bagged URLs. So, `eff` would return "eff.org" and "effingelves.net" as well as "jeffbuckley.com" (I don't know who runs this site, but it is genuinely about the musician).

```
body:"EARN IT Act"
```
Self-explanatory, and, except for phrases right now being automatic without the quotes, Wallabag is already doing a body search every time. `body:` wouldn't serve much purpose as a search operator. But 3 is a better number than 2, so here we are.

**Comment by meonkeys** [comment] 2022-11-25 23:20
#2814 looks similar as well
