### ISSUE TITLE
Error in downloaded images

### ISSUE THREAD

**Issue by ngosang** [wallabag/wallabag#2823] opened 2017-02-01 07:48 UTC
### Issue details
I have wallabag installed in non-root path:
=> http://my_domain/wallabag/web/
If I check "Download images locally", I can't see any image because the URLs are wrong.
=> Wrong (current implementation) http://my_domain/assets/images/
=> Right http://my_domain/wallabag/web/assets/images/

I think you should change absolute paths to relative paths.

### Environment

* Version: 2.2.1
* php version: 7
* OS: ubuntu
* shared hosting
* SQLite

Related in some way: #410 #412

**Comment by nicosomb** [comment] 2017-02-16 15:57
It seems to be a duplicate of https://github.com/wallabag/wallabag/issues/2852. 
If I'm wrong, feel free to reopen your issue.

**Closed by nicosomb** 2017-02-16 15:57 UTC
Labels: Bug
