### ISSUE TITLE
Download images locally and domain change

### ISSUE THREAD

**Issue by ngosang** [wallabag/wallabag#2904] opened 2017-02-17 08:58 UTC
### Issue details
I have "Download images locally" enabled and a lot of articles downloaded. If I change the "URL of *your* wallabag instance" this applies to new articles but old articles images are broken. :(

You should save a relative image path and compose the full URL when you request the article.
Example:
1) You add an article, download the images to local dir and replace URLs in the article with relative URLs.
2) When you request an article, search for images in the text and replace relative URLs with "URL of *your* wallabag instance" + relative URL. **Or better, let the relative URL and don't use "URL of *your* wallabag instance"**
3) If you change "URL of *your* wallabag instance" everything is fine.

![](http://pix.toile-libre.org/upload/original/1487319468.png)

### Environment
* wallabag master

**Comment by nicofrand** [comment] 2017-02-17 10:07
Duplicate of https://github.com/wallabag/wallabag/issues/2852.

**Closed** 2017-02-17 10:30 UTC
