### ISSUE TITLE
Does not add articles after the update php

### ISSUE THREAD

**Issue by Pitstopper** [wallabag/wallabag#3949] opened 2019-05-03 12:10 UTC
### Issue details
Hey! After updating php to the latest version, links to some sites have ceased to be added. There is a requirement to increase the response time in php or allocate memory size in php. But if all this is done, an error 500 occurs, although all the necessary rights and permissions to the directories are present. I will attach full logs below.
[prod1.log](https://github.com/wallabag/wallabag/files/3141766/prod1.log)
[prod2.log](https://github.com/wallabag/wallabag/files/3141767/prod2.log)

 Please help! 

### Environment

* wallabag version - 2.3.7, 2.3.8-dev
* How did you install wallabag -`git clone`
* php version: PHP 7.3.5-1 (built: May  3 2019 09:38:28) ( NTS )
* OS: Debian 9
* type of hosting - dedicated
* which storage system you choose - MySQL/MariaDB

### Steps to reproduce/test case

Trying to add articles like this:
1. https://habr.com/ru/post/450230/
2. https://habr.com/ru/post/450228/

**Comment by tcitworld** [comment] 2019-05-03 12:25
Duplicate of #3926

**Closed** 2019-05-03 12:25 UTC
