### ISSUE TITLE
[v2] Source code should not contain TODO comments - in src/Wallabag/…/Import/PocketImport.php, line 181

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1602] opened 2016-01-20 14:42 UTC
**[in src/Wallabag/ImportBundle/Import/PocketImport.php, line 181](https://github.com/wallabag/wallabag/blob/d481f42b7d383eb6211d1d3049d1a2c8288d9edb/src/Wallabag/ImportBundle/Import/PocketImport.php#L181)**

> TODO comments are left in the code when a feature (or a bug) isn't completely developed (or fixed). You should complete the implementation and remove the comment.

```php
    {
        $this->client = $client;
    }

    /**
     * @todo move that in a more global place
     */
    private function assignTagsToEntry(Entry $entry, $tags)
    {
        foreach ($tags as $tag) {
            $label = trim($tag['tag']);
```

**Comment by j0k3r** [comment] 2016-02-19 10:37
Kind of duplicate of https://github.com/wallabag/wallabag/issues/1667

**Closed by j0k3r** 2016-02-19 10:37 UTC
