### ISSUE TITLE
Reddit: Failed to get the article 

### ISSUE THREAD

**Issue by TofPlay** [wallabag/wallabag#3756] opened 2018-10-19 06:55 UTC
### Issue details

I want to store some articles from reddit 
When I try to do it with Wallabag I just have the title of the article

### Environment

* wallabag version: 2.3.3
* How did you install wallabag? : wallabag docker
* php version: 7.2.10
* OS: Docker alpine:edge
* type of hosting: self hosting 
* which storage system you choose at install: mariadb

### Steps to reproduce/test case

Add new entry 
https://www.reddit.com/r/mac/comments/8rncud/i_accidentally_put_apfs_on_my_hdd_i_should_switch/e0t4b8t/

You will see
![](https://snag.gy/6PhALV.jpg)

On wallabag you will see
![](https://snag.gy/PCdks0.jpg)

**Comment by techexo** [comment] 2018-11-16 01:21
The siteconfig for reddit.com (https://github.com/fivefilters/ftr-site-config/blob/master/reddit.com.txt) explicitely states:

> This setup grabs the text from a Reddit self post. It ignores all comments etc.

And it is exactly what it does on my setup:
![image](https://user-images.githubusercontent.com/1850197/48591793-c744f300-e945-11e8-9cd6-38f11bc9c7a0.png)

I think that as you are using a link to a specific comment, it cannot work.

**Comment by hrehfeld** [comment] 2019-04-16 21:58
It would still be very nice to fix this! Example where comment is long enough to warrant supporting: https://www.reddit.com/r/videos/comments/bdfqm4/the_real_reason_boeings_new_plane_crashed_twice/ekyyd9g/

**Comment by gitlabt** [comment] 2019-08-09 16:15
I have the same. 

What can I do to make the articles visible with comments.
I exports the page to epub and I read with the dictionary. Now I have only the main article

Do I need to set site config. If so, how should I do it?

**Comment by GitJamz** [comment] 2020-10-20 20:24
Also want to know if this is fixable! A lot of discussions on subjects are very valuable for the subject and you want it snatched with wallabag..

**Comment by j0k3r** [comment] 2021-02-10 13:37
Duplicate of #3644

**Closed by j0k3r** 2021-02-10 13:37 UTC
Labels: Site Config
