### ISSUE TITLE
Download images locally

### ISSUE THREAD

**Issue by ngosang** [wallabag/wallabag#2964] opened 2017-03-05 15:51 UTC
### Issue details

1) Enable "Download images locally"
2) Add => https://www.tvaddons.ag/realdebrid-kodi-jarvis/
3) Most images are not stored locally.

![2017-03-05 16_43_04-configuring the real-debrid service for kodi 16 1 jarvis or below tvaddons ag](https://cloud.githubusercontent.com/assets/10577978/23588805/200ce608-01c3-11e7-9e6c-496c0f9f4d3b.png)

### Environment

* wallabag 2.2.2

**Comment by j0k3r** [comment] 2017-03-06 09:09
Thanks for the report, we'll have a look

**Comment by prolibre** [comment] 2017-03-06 12:13
idem for that

https://theconversation.com/conversation-avec-gerald-bronner-ce-nest-pas-la-post-verite-qui-nous-menace-mais-lextension-de-notre-credulite-73089

thanks,

Anthony

**Comment by Alwaysin** [comment] 2017-06-01 18:39
Could reproduce.

**Comment by j0k3r** [comment] 2017-06-01 20:36
@Alwaysin could you please share the related url to reproduce?

**Comment by j0k3r** [comment] 2017-06-01 20:56
@ngosang the problem was related to the symbol `&` in each url. This'll be fixed in https://github.com/wallabag/wallabag/pull/3176

@prolibre the problem with this url is we can't determine if it's a real image so we can't find the extension. The server respond with an empty header instead of some information about image (if it's a jpg, gif, etc..) http://hurl.eu/hurls/45edd6b5e31d8460c152cab9f85ffa1e33b51422/256e61fdf52426ab47f213789804fedd912edefb
Yes we can check about the final extension of the url but we can't 100% sure it's an image. It can be a zip file with a jpg at the end. So I guess, we won't be able to fix the problem in that particular case.

@Alwaysin could you please share the related url to reproduce? So I can try myself to see what's wrong. Otherwise you can also check `var/log/prod.log` and look for `DownloadImages`. It might have a line with an error about that.

**Comment by Alwaysin** [comment] 2017-06-03 17:12
Example with: https://cdn.theconversation.com/files/164136/width1356x668/image-20170405-14593-pvu9r5.JPG

**Comment by j0k3r** [comment] 2017-06-03 17:13
@Alwaysin I mean the article url not the image 🙂

**Comment by Alwaysin** [comment] 2017-06-03 17:16
Sorry, edited my answer. Here is the log:

[2017-06-01 18:36:29] app.DEBUG: DownloadImages: working on image: https://cdn.theconversation.com/files/164136/width1356x668/image-20170405-14593-pvu9r5.JPG [] []
[2017-06-01 18:36:31] app.DEBUG: DownloadImages: Checking extension {"ext":null,"header":""} []
[2017-06-01 18:36:31] app.ERROR: DownloadImages: Processed image with not allowed extension. Skipping https://cdn.theconversation.com/files/164136/width1356x668/image-20170405-14593-pvu9r5.JPG [] []

Coulmd it be because JPG is in capital letters?

**Comment by j0k3r** [comment] 2017-06-03 17:20
Sadly it's not related to the JPG in capital letters.
Check that link: http://hurl.eu/hurls/13eb397748a14c037500d1acb7170ae9c5f7fd82/51d898be7ca74a1a481c0132a41628c3f3314d10
It's the server response when asking for the image. See the `Content-Type:`? It means , the server doesn't tell which type is the response.

Here is an other response from a different server for an image: http://hurl.eu/hurls/327663afc9c907614af05b3f02fcb5e38e4d02aa/0303c1cc1561a8c11bf43643532e9a1aceeb8f08
See the `Content-Type: image/jpeg`? It tells us that the response is an image.

**Comment by Alwaysin** [comment] 2017-06-03 17:27
So there is no way for wallabag to handle this?

**Comment by j0k3r** [comment] 2017-06-05 20:58
I've found an alternative solution that should fix the content-type problem.

**Closed** 2017-06-07 11:41 UTC
Labels: Bug
