### ISSUE TITLE
Authentication to websites needed to fetch the text

### ISSUE THREAD

**Issue by sciunto** [wallabag/wallabag#1009] opened 2015-01-18 23:13 UTC
Hi,

I bought access to news websites but my instance of wallabag cannot import the text because it ignores the login/password, whereas I can visualize the text in my browser.

I'm looking forward any workaround or solution. Ideally, I would see the possibility to put the domain name, the login and the password in wallabag.

Thank you.

**Comment by tcitworld** [comment] 2015-01-19 16:09
Hi,
It's a duplicate of #438. There are also some ideas at #886.
Please follow up here.

**Closed by tcitworld** 2015-01-19 16:09 UTC
