### ISSUE TITLE
Error message when installing Wallabag within docker and SQLite

### ISSUE THREAD

**Issue by rican13** [wallabag/wallabag#6424] opened 2023-04-11 15:39 UTC
I get a blocking error message on the easiest way to install Wallabag on Docker. I'm on "Ubuntu 22.04.2 LTS", I have a working "docker" and "docker-compose" installation. When I run the simplest command to start Wallabag (with SQLite), I get a blocking message.

### Environment
* **Version**: latest
* **Installation**: docker
* **PHP version**:
* **OS**: Ubuntu 22.04.2 LTS
* **Database**: SQLite
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>
  ```
docker run -v /opt/wallabag/data:/var/www/wallabag/data -v /opt/wallabag/images:/var/www/wallabag/web/assets/images -p 80:80 -e "SYMFONY__ENV__DOMAIN_NAME=http://localhost" wallabag/wallabag
  ```
</details>

### What steps will reproduce the bug?
Error message :
Step 1 of 4: Checking system requirements.
  PDO Driver (pdo_sqlite)   OK!
  Database connection       ERROR!   Can't connect to the database: An exception occurred in driver: SQLSTATE[HY000] [14] unable to open database file  
  Database version          OK!
  curl_exec                 OK!                               
  curl_multi_init           OK!

15:09:35 ERROR     [console] Error thrown while running command "wallabag:install --env=prod -n". Message: "Some system requirements are not fulfilled. Please check output messages and fix them." ["exception" => RuntimeException { …},"command" => "wallabag:install --env=prod -n","message" => "Some system requirements are not fulfilled. Please check output messages and fix them."]

In InstallCommand.php line 163:
  Some system requirements are not fulfilled. Please check output messages an  
  d fix them.

**Comment by j0k3r** [comment] 2023-04-12 12:16
Duplicate of https://github.com/wallabag/docker/issues/316

**Closed by j0k3r** 2023-04-12 12:16 UTC
