### ISSUE TITLE
Tag autosuggest

### ISSUE THREAD

**Issue by franck-paul** [wallabag/wallabag#5624] opened 2022-02-20 09:45 UTC
When adding a (or several) tag(s) to an article, it should be nice to have an autosuggest (from already created tags) at least 2 or 3 characters are entered.

**Comment by Kdecherf** [comment] 2022-02-20 11:36
Duplicate of #5236

**Closed by Kdecherf** 2022-02-20 11:36 UTC
Labels: Feature

**Comment by franck-paul** [comment] 2022-02-21 09:29
Oh sorry for this duplicated issue!

I searched for "suggest tags" "autosuggest tag" … but not for "existing", "show" and "labels" :-)

**Comment by Kdecherf** [comment] 2022-02-21 09:43
No worries :)
