### ISSUE TITLE
Export feature including annotations

### ISSUE THREAD

**Issue by jason-mehmel** [wallabag/wallabag#7871] opened 2024-12-02 18:38 UTC
**Is your feature request related to a problem? Please describe.**

I'm trying to find a way to export the articles INCLUDING the annotations. Currently the export features export the articles but not the annotations made within wallabag.

**Describe the solution you'd like**

Within the export options, hopefully including PDF, HTML, and EPUB, the articles would contain either a collection of annotations at the top or bottom of the article.

**Describe alternatives you've considered**

I've tried the obsidian-wallabag plugin, but can't get it to work. This might be due to the scale of my data in wallabag, or technical elements I haven't yet discovered.

**Additional context**

**Comment by jason-mehmel** [comment] 2024-12-03 18:19
Ah! And to add to that request... if the export feature could include tags as well!

**Comment by j0k3r** [comment] 2024-12-04 04:21
Duplicate of https://github.com/wallabag/wallabag/issues/1130

**Closed** 2024-12-04 04:21 UTC
Labels: Feature
