### ISSUE TITLE
Tag articles directly from the unread overview

### ISSUE THREAD

**Issue by janLo** [wallabag/wallabag#2761] opened 2017-01-17 16:00 UTC
### Issue details

I use the wallabagger chrome extension by right-clicking on a link and clicking "Wallabag it!". So I do not assign tags instantly. It would be nice to be able to tag articles then directly from the article overview instead to have to click on every article and typing the tags in there.

**Comment by sanjayankur31** [comment] 2017-02-09 15:47
+1 This functionality would be really great :)

**Comment by nicosomb** [comment] 2017-02-14 17:09
In fact, it's a duplicate of https://github.com/wallabag/wallabag/issues/2246.

**Closed by nicosomb** 2017-02-14 17:09 UTC
Labels: Feature, UI
