### ISSUE TITLE
Suggestion about Paywalls

### ISSUE THREAD

**Issue by guakamole** [wallabag/wallabag#3304] opened 2017-08-01 00:46 UTC
Hello,

Thank you for Wallabag.

I know that it is possible to provide credentials for a series of website in order to allow Wallabag to fetch articles behind paywalls. The problem with this method is that it requires user config and/or per site config.

Have you ever thought about - rather than remotely fetching the content of a page based on a URL provided by a bookmarklet/URL (current situation) - sending the content of a page based on its displayed content ? This would fully bypass the paywall problem without requiring users to create dedicated configs/provide their credentials.

Scenario:

* Bob is a paying member of `foobar.com` , he's logged in and reads `foobar.com/super-article-behind-paywall-for-non-members`
* Bob clicks onto his browser extension/bookmarklet
* The extension/bookmarklet sends a base64 encoded (or whatever) version of the current page to the wallabag server
* Wallabag decodes the page and does its magic

**Comment by j0k3r** [comment] 2017-08-01 04:52
This will be available in the next release in the API (ability to send the whole content).
Extension will have to implement it.

Duplicate of https://github.com/wallabag/wallabag/issues/1525

**Closed by j0k3r** 2017-08-01 04:52 UTC
