### ISSUE TITLE
Prevent creation of duplicate articles

### ISSUE THREAD

**Issue by n00b12345** [wallabag/wallabag#3045] opened 2017-04-20 03:00 UTC
At present, if I save an existing article twice, the article will be saved twice.

Ideally Wallabag should be able to detect it and then not add a duplicate.

It would really be great if at some point, this was considered as a feature.

**Comment by nicosomb** [comment] 2017-04-20 07:28
Hello @n00b12345 ! 

Can you give us some URL which are duplicated? 
Because duplication is already handled in wallabag, but maybe there are issues with some URLs.

**Comment by n00b12345** [comment] 2017-04-20 07:41
Hi @nicosomb,

I'll try to explain. I'm on iOS and I'm using the Wallabag app extension to save articles from Twitter for iOS. 

- I open this tweet on twitter and save the techcruch link within it: https://twitter.com/techcrunch/status/854858178957365249
- I hit save using the Wallabag extension
- I try to save the exact same article again using the Wallabag extension
- I visit Wallabag and it has saved the article twice

Small detail - The tech crunch link from twitter is a shortened one: http://tcrn.ch/2pC4j9N

I'm not sure if URL shortening and then expanding is causing Wallabag to save the same article multiple times.

Mind you this does not happen with absolute URLs which are already expanded. Eg. things would perfectly (no multiple saves) with the expanded link of that article which is: https://techcrunch.com/2017/04/19/juicero-users-find-that-man-trumps-machine/?ncid=rss&utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+Techcrunch+%28TechCrunch%29&sr_share=twitter

**Comment by nicosomb** [comment] 2017-04-20 07:55
OK, that's the problem: URL shortener. 
In fact, we save in database the techcrunch URL in our database (here: `https://techcrunch.com/2017/04/19/juicero-users-find-that-man-trumps-machine/`). 

But when you want to save the article twice, we only have the `tcrn.ch` URL, and this URL is not in database. I hope I'm clear. 

So your issue is a duplicate of https://github.com/wallabag/wallabag/issues/2232.

**Closed by nicosomb** 2017-04-20 07:55 UTC
