### ISSUE TITLE
Restrict image size to be an preview-image

### ISSUE THREAD

**Issue by Rurik19** [wallabag/wallabag#1874] opened 2016-04-06 09:44 UTC
If it possible not to take too little images as an article-image? Default image from livejournal.com articles  without images looks ugly.

**Comment by j0k3r** [comment] 2016-04-06 10:02
Could you provide a link to livejournal.com article and a screenshot please of wallabag?

**Comment by Rurik19** [comment] 2016-04-06 10:21
Sure
[http://vi4kin77.livejournal.com/150817.html](url)
[http://vi4kin77.livejournal.com/150817.html](url)
![image](https://cloud.githubusercontent.com/assets/1955806/14313466/3f7bb7bc-fc0b-11e5-973a-ec5eb14007b0.png)

**Comment by nicosomb** [comment] 2017-05-13 07:41
Duplicate of #3115.

**Closed** 2017-05-13 07:41 UTC
Labels: Feature
