### ISSUE TITLE
Automatically send new article by email

### ISSUE THREAD

**Issue by rParslow** [wallabag/wallabag#2738] opened 2017-01-06 12:57 UTC
Today I have to use IFTTT to receive new articles by mail

Request is to have the possibility to have the same feature within Wallabag.  
By adding an option in https://app.wallabag.it/config "push new article by mail" or "my account" article to be mailed to user email

Nice to have could be to filter by tags

This feature might handle also #770 Add possibility to send articles to Kindle 
In that case the destination email should be a parameter and the article send in mobi format.

**Comment by nicosomb** [comment] 2024-11-14 20:44
Duplicate of #239

**Closed** 2024-11-14 20:45 UTC
Labels: Feature
