### ISSUE TITLE
Document upgrade from v1 to v2

### ISSUE THREAD

**Issue by zertrin** [wallabag/wallabag#1624] opened 2016-01-23 13:30 UTC
Hi!

I've quickly looked around but didn't easily find a document describing the process of upgrading from wallabag v1 to v2.

Since the release of the v2 is approaching, I think this could be a TODO before the final version.

The goal is to explain how to migrate from v1 to v2 without starting from scratch (keeping most settings and all already archived webpages).

If such a document already exist, sorry for the noise here and please point me to it ;)

Thanks!

**Comment by nicosomb** [comment] 2016-01-23 13:33
Hello @zertrin ! 

Thanks for your post. You're totally right, we need a real HOWTO upgrade. We started something here https://github.com/wallabag/wallabag/blob/v2/docs/en/user/import.rst (available in our next documentation website http://wallabag.readthedocs.org/en/v2/user/import.html) but all is not finished.

**Comment by tcitworld** [comment] 2016-01-23 13:33
Also, import from v1 to v2 is not available (see #1601).

**Comment by nicosomb** [comment] 2016-01-24 09:25
Duplicate of #1595 in fact.

**Closed by nicosomb** 2016-01-24 09:25 UTC
Labels: Documentation
