### ISSUE TITLE
Database error on update from 2.1.5 to 2.2

### ISSUE THREAD

**Issue by Philppe** [wallabag/wallabag#2961] opened 2017-03-04 12:54 UTC
Hi, 

I get this error during the update from 2.1.5 to 2.2 :

`Migration 20161022134138 failed during Execution. Error An exception occurred while executing 'ALTER TABLE wallabag_user CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;':`

`SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes`
                                                                                                 
  `[Doctrine\DBAL\Exception\DriverException]                                                                                        
  An exception occurred while executing 'ALTER TABLE wallabag_user CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;':  
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes`                  
                                                                                                                   
  `[Doctrine\DBAL\Driver\PDOException]                                                                              
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes`
                                                                                                                 
`[PDOException]                                                                                                   
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes`

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.5
* How did you install wallabag? Via `git clone` or by downloading the package? `git clone`
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 5.6.30
* OS: Debian Jessie 8.7
* type of hosting (shared or dedicated): self-hosting
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

I have used the `make update` command to upgrade.

Thanks for your help

**Comment by Philppe** [comment] 2017-03-09 11:17
Any idea about this issue ?

**Comment by nicosomb** [comment] 2017-03-09 12:52
Hello @Philppe !

Your issue seems to be a duplicate of https://github.com/wallabag/wallabag/issues/2810. 
Feel free to reopen it if I was wrong.

**Closed by nicosomb** 2017-03-09 12:52 UTC
