### ISSUE TITLE
Truncated Text - h2 ignored

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#3444] opened 2017-11-29 07:28 UTC
### Issue details

when adding the URL http://www2.cnrs.fr/presse/communique/5327.htm

The result of the article in wallabag is that the text is uncomplet. the h2#chapeau is not included

### Environment

* wallabag version (or git revision) that exhibits the issue:
* How did you install wallabag? Via `git clone` or by downloading the package? git
* Last wallabag version that did not exhibit the issue (if applicable):  2.2.3
* php version: 7
* OS : debian 9.1
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): PostgreSQL

### Steps to reproduce/test case

add the page http://www2.cnrs.fr/presse/communique/5327.htm and see the truncated text

**Comment by techexo** [comment] 2018-11-21 01:11
PR https://github.com/fivefilters/ftr-site-config/pull/556 should solve this. I am wondering however if it's not caused by [this code](https://github.com/j0k3r/php-readability/blob/ed3393a79fe8fbbf1abe7daf17a47b21d862ddfb/src/Readability.php#L587-L594).

**Comment by Kdecherf** [comment] 2018-11-25 15:41
This issue seems to be fixed in wallabag 2.3.4, I'm closing it.

Thanks @techexo :+1:

**Closed by Kdecherf** 2018-11-25 15:41 UTC
Labels: Site Config
