### ISSUE TITLE
Could the docker image run on ARM?

### ISSUE THREAD

**Issue by starsareintherose** [wallabag/wallabag#5301] opened 2021-05-24 02:41 UTC
Could the docker image run on ARM? Such as docker on Raspberry Pi？.

**Comment by mritzmann** [comment] 2021-06-16 12:38
duplicate of  #5201

**Comment by tcitworld** [comment] 2021-06-16 12:41
Closed as duplicate of https://github.com/wallabag/docker/issues/266

**Closed by tcitworld** 2021-06-16 12:41 UTC
Labels: Feature
