### ISSUE TITLE
Issue Upgrading to 2.4.1

### ISSUE THREAD

**Issue by tomershvueli** [wallabag/wallabag#4917] opened 2021-01-07 18:10 UTC
### Environment

* **Version**: 2.3.7-dev
* **Installation**: Installed through Cloudron
* **PHP version**: 7.3
* **OS**: Ubuntu 18.04
* **Database**: Postgres
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: wallabag
    database_user: root
    database_password: null
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
    domain_name: 'https://your-wallabag-url-instance.com'
    server_name: 'Your wallabag instance'
    mailer_transport: smtp
    mailer_user: null
    mailer_password: null
    mailer_host: 127.0.0.1
    mailer_port: false
    mailer_encryption: null
    mailer_auth_mode: null
    locale: en
    secret: CHANGE_ME_TO_SOMETHING_SECRET_AND_RANDOM
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null
  ```
</details>

### What steps will reproduce the bug?

Trying to upgrade to the latest 2.4.1 is failing with the following errors: 
```Jan 07 13:06:07 Database successfully setup.
Jan 07 13:06:07
Jan 07 13:06:07 Step 3 of 4: Administration setup.
Jan 07 13:06:07 ----------------------------------
Jan 07 13:06:07
Jan 07 13:06:07
Jan 07 13:06:07 In AbstractPostgreSQLDriver.php line 57:
Jan 07 13:06:07
Jan 07 13:06:07 An exception occurred while executing 'INSERT INTO "wallabag_user" (usernam
Jan 07 13:06:07 e, username_canonical, email, email_canonical, enabled, salt, password, las
Jan 07 13:06:07 t_login, confirmation_token, password_requested_at, roles, id, name, create
Jan 07 13:06:07 d_at, updated_at, authCode, googleAuthenticatorSecret, backupCodes, emailTw
Jan 07 13:06:07 oFactor) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'
Jan 07 13:06:07 with params ["wallabag", "wallabag", "wallabag@wallabag.io", "wallabag@wall
Jan 07 13:06:07 abag.io", 1, "yTKGajcCg2ZB5DWhze65lWr3gzcfMtgv..Mdi356UD4", "NoUPD28bFUVSuZ
Jan 07 13:06:07 emcAd+ULVhrYbwcSpkfdb5QXILrfk0v7AaLKKtn3yUSJBKdwjor8s27PO8j5f9juzJgs387A=="
Jan 07 13:06:07 , null, null, null, "a:2:{i:0;s:9:\"ROLE_USER\";i:1;s:16:\"ROLE_SUPER_ADMIN
Jan 07 13:06:07 \";}", 473, null, "2021-01-07 18:06:07", "2021-01-07 18:06:07", null, null,
Jan 07 13:06:07 null, 0]:
Jan 07 13:06:07
Jan 07 13:06:07 SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates u
Jan 07 13:06:07 nique constraint "uniq_1d63e7e592fc23a8"
Jan 07 13:06:07 DETAIL: Key (username_canonical)=(wallabag) already exists.
Jan 07 13:06:07
Jan 07 13:06:07
Jan 07 13:06:07 In PDOStatement.php line 131:
Jan 07 13:06:07
Jan 07 13:06:07 SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates u
Jan 07 13:06:07 nique constraint "uniq_1d63e7e592fc23a8"
Jan 07 13:06:07 DETAIL: Key (username_canonical)=(wallabag) already exists.
Jan 07 13:06:07
Jan 07 13:06:07
Jan 07 13:06:07 In PDOStatement.php line 129:
Jan 07 13:06:07
Jan 07 13:06:07 SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates u
Jan 07 13:06:07 nique constraint "uniq_1d63e7e592fc23a8"
Jan 07 13:06:07 DETAIL: Key (username_canonical)=(wallabag) already exists.
Jan 07 13:06:07
Jan 07 13:06:07
Jan 07 13:06:07 + /usr/local/bin/gosu www-data:www-data php bin/console doctrine:migrations:migrate --env prod --no-interaction
Jan 07 13:06:08
Jan 07 13:06:08 Application Migrations
Jan 07 13:06:08
Jan 07 13:06:08
Jan 07 13:06:08 Migrating up to 20200428072628 from 20190425115043
Jan 07 13:06:08
Jan 07 13:06:08 ++ migrating 20190510141130
Jan 07 13:06:08
Jan 07 13:06:08 -> ALTER TABLE "wallabag_oauth2_access_tokens" DROP CONSTRAINT FK_368A4209A76ED395
Jan 07 13:06:08 -> ALTER TABLE "wallabag_oauth2_access_tokens" ADD CONSTRAINT FK_368A4209A76ED395 FOREIGN KEY (user_id) REFERENCES "wallabag_user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
Jan 07 13:06:08 -> ALTER TABLE "wallabag_oauth2_clients" DROP CONSTRAINT idx_user_oauth_client
Jan 07 13:06:08 Migration 20190510141130 failed during Execution. Error An exception occurred while executing 'ALTER TABLE "wallabag_oauth2_clients" DROP CONSTRAINT idx_user_oauth_client':
Jan 07 13:06:08
Jan 07 13:06:08 SQLSTATE[42704]: Undefined object: 7 ERROR: constraint "idx_user_oauth_client" of relation "wallabag_oauth2_clients" does not exist
Jan 07 13:06:08 18:06:08 ERROR [console] Error thrown while running command "doctrine:migrations:migrate --env prod --no-interaction". Message: "An exception occurred while executing 'ALTER TABLE "wallabag_oauth2_clients" DROP CONSTRAINT idx_user_oauth_client':
Jan 07 13:06:08
Jan 07 13:06:08 SQLSTATE[42704]: Undefined object: 7 ERROR: constraint "idx_user_oauth_client" of relation "wallabag_oauth2_clients" does not exist" ["exception" => Doctrine\DBAL\Exception\DriverException { …},"command" => "doctrine:migrations:migrate --env prod --no-interaction","message" => """ An exception occurred while executing 'ALTER TABLE "wallabag_oauth2_clients" DROP CONSTRAINT idx_user_oauth_client':\n \n SQLSTATE[42704]: Undefined object: 7 ERROR: constraint "idx_user_oauth_client" of relation "wallabag_oauth2_clients" does not exist """]
Jan 07 13:06:08
Jan 07 13:06:08 In AbstractPostgreSQLDriver.php line 89:
Jan 07 13:06:08
Jan 07 13:06:08 An exception occurred while executing 'ALTER TABLE "wallabag_oauth2_clients
Jan 07 13:06:08 " DROP CONSTRAINT idx_user_oauth_client':
Jan 07 13:06:08
Jan 07 13:06:08 SQLSTATE[42704]: Undefined object: 7 ERROR: constraint "idx_user_oauth_cli
Jan 07 13:06:08 ent" of relation "wallabag_oauth2_clients" does not exist
Jan 07 13:06:08
Jan 07 13:06:08
Jan 07 13:06:08 In PDOConnection.php line 91:
Jan 07 13:06:08
Jan 07 13:06:08 SQLSTATE[42704]: Undefined object: 7 ERROR: constraint "idx_user_oauth_cli
Jan 07 13:06:08 ent" of relation "wallabag_oauth2_clients" does not exist
Jan 07 13:06:08
Jan 07 13:06:08
Jan 07 13:06:08 In PDOConnection.php line 86:
Jan 07 13:06:08
Jan 07 13:06:08 SQLSTATE[42704]: Undefined object: 7 ERROR: constraint "idx_user_oauth_cli
Jan 07 13:06:08 ent" of relation "wallabag_oauth2_clients" does not exist
Jan 07 13:06:08
Jan 07 13:06:08
Jan 07 13:06:08 doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--db DB] [--em EM] [--shard SHARD] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<version>]
```

Any help would be appreciated!

**Comment by nebulade** [comment] 2021-01-07 18:21
Just to add a bit more context, since other users probably have hit this as well: https://forum.cloudron.io/topic/4145/latest-update-not-working

**Comment by Kdecherf** [comment] 2022-02-16 17:48
Hello @nebulade, do you still encounter this issue with 2.4.3?

**Comment by nebulade** [comment] 2022-02-17 15:07
I forgot about this issue here. The problem is gone for us.

**Comment by Kdecherf** [comment] 2022-02-17 15:40
Nice to hear, I'll close this issue then :)

**Closed by Kdecherf** 2022-02-17 15:40 UTC
Labels: Awaiting response, Upgrade
