### ISSUE TITLE
Error of installing via docker

### ISSUE THREAD

**Issue by starsareintherose** [wallabag/wallabag#5078] opened 2021-02-24 16:44 UTC
* **Version**: latest
* **Installation**:docker
* **PHP version**:7.4
* **OS**:CentOS7
* **Database**:mysql

### What steps will reproduce the bug?
```
[root@helix ~]# docker run --name wallabagtest --link mysql:mysql -e "MYSQL_ROOT_PASSWORD=my_password" -e "SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql" -e "SYMFONY__ENV__DATABASE_HOST=wallabag-db" -e "SYMFONY__ENV__DATABASE_PORT=3306" -e "SYMFONY__ENV__DATABASE_NAME=wallabag" -e "SYMFONY__ENV__DATABASE_USER=wallabag" -e "SYMFONY__ENV__DATABASE_PASSWORD=wallapass" -e "SYMFONY__ENV__DATABASE_CHARSET=utf8mb4" -e "SYMFONY__ENV__DOMAIN_NAME=https://read.malacology.net" -p 8080:8080 --add-host=dockerhelix:My_IP wallabag/wallabag
```

Enter details about your bug and how to reproduce it
```
[WARNING]: Found both group and host with same name: localhost
[WARNING]: Platform linux on host localhost is using the discovered Python
interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change this. See https://docs.ansible.com/ansible/2.9/referen
ce_appendices/interpreter_discovery.html for more information.
```
As you see, I change the localhost name, so what's wrong.

**Comment by j0k3r** [comment] 2021-02-25 12:02
Duplicate of https://github.com/wallabag/docker/issues/251

**Closed by j0k3r** 2021-02-25 12:02 UTC
