### ISSUE TITLE
Send contents of article by email

### ISSUE THREAD

**Issue by ajkessel** [wallabag/wallabag#7010] opened 2023-10-04 20:46 UTC
Has the idea of allowing the user to share the contents of an article by email already been discussed/rejected? I see a number of threads on _receiving_ articles by email (either the contents of the email, or via an emailed URL), and there is existing functionality that allows you to, e.g., send a public-link URL via email, but nothing to allow sending contents by email. I can understand that you might want this disabled on the public wallabag instance, but could it be something self-hosted installers could enable? This should avoid wallabag for being on the hook for spam/abuse or copyright issues.

There used to be a service https://www.emailthis.me/ that did something like this, but the site is dead and even though it accepts payment, it doesn't work.

There do not appear to be any publicly-available browser plugins with this functionality either.

**Comment by j0k3r** [comment] 2023-10-05 06:38
That feature only exist on wallabag.it as of now.
Duplicate of #239

**Closed by j0k3r** 2023-10-05 06:38 UTC
Labels: Feature

**Comment by HolgerAusB** [comment] 2023-10-05 12:40
There is already a `share > email` but this only sends a link to the original article. There should be a choice:
- mail a link to original article
- mail a link to the wallabag item (you can already generate such a link and send it manually)
- mail both links, original site and wallabag
- mail as PDF (convert to pdf already exist)
- mail content

The last one might be difficult to realize, because that could be heavily mail-client-depended coding. Remember: HTML is not originally part of the email standards. The others just do some simple mailto-voodoo I think, where full content would be too much data to just re-use that method.

**Comment by ajkessel** [comment] 2023-10-05 13:10
Right. I note above you can share the link, but not the article. I would be happy with a solution that just attached the Wallabag formatted article as an HTML MIME part attachment.
