### ISSUE TITLE
Parent/group tags

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#1129] opened 2015-02-22 21:47 UTC
A tag could be the parent for other tags. As in exemple below.

> I, for myself, have created a nomenclature, that mimic sub-categories.
> For example, I use "tool/requirejs" and '"tool/browserify". But if later I try to add an article about bower, which needs a new tag, I may mistakenly create "tools/bower" 'cause it's a new one, and I don't get a clue about my past nomenclature… do you follow me ?
> 
> Anyhow, tags that could group other tags would be by far the best feature ! ;)
> Than I would have create the tag group "tool" and add to it "requirejs", "browserify" and the likes.

**Comment by nicosomb** [comment] 2017-02-16 16:25
Hello @tcitworld. Thank you for your interest about wallabag. 
It seems that your issue is a duplicate of #767 ✈️ 

Feel free to reopen if I'm wrong 😗 

See you soon on wallabag.

**Closed by nicosomb** 2017-02-16 16:25 UTC
Labels: Feature
