### ISSUE TITLE
webhooks

### ISSUE THREAD

**Issue by tctlrd** [wallabag/wallabag#7651] opened 2024-09-01 14:43 UTC
here is a +1 for a webhook feature in wallabag.

My use is to have wallabag article origin links automatically sent to [linkding](/sissbruecker/linkding) with tags and possibly article docs to [paperless-ngx](/paperless-ngx/paperless-ngx) via webhook. I may have a self-hosted [n8n](/n8n-io/n8n) instance receive the webhook to customize the integration.

### workarounds
1. DB row trigger: Have a webhook triggered by changes to the database via [nocodb](/nocodb/nocodb) (or similar). https://docs.nocodb.com/automation/webhook/webhook-overview
2. RSS feed trigger: Interval checking the wallabag RSS feed with n8n (or similar). https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-base.rssfeedreadtrigger

### webhooks.fyi
[webhooks.fyi](/ngrok/webhooks.fyi) is a great resource for all things webhook.

> Webhooks.fyi is a one-stop shop for information on how to build, consume, secure, maintain, and overall function with webhooks. While we've started with a heavy security focus with an eye towards future maintainability, we want to expand this into a clearing house for the best and worst practices you will see in the wild.

**Comment by j0k3r** [comment] 2024-09-02 07:23
You already told us about it.

Duplicate of #500

**Closed by j0k3r** 2024-09-02 07:23 UTC
Labels: Feature
