### ISSUE TITLE
Email feature seems to be missing

### ISSUE THREAD

**Issue by legolasdimir** [wallabag/wallabag#6561] opened 2023-05-29 13:05 UTC
I am using the docker image from https://github.com/wallabag/docker that is being hosted and maintained by a friend of mine and the emailing feature that lets you email urls to wallabag seems to be missing. This feature is mentioned on the blog at wallabag.it [here](https://www.wallabag.it/en/news/week-18-whats-new-on-wallabag-it) but I do not see it in the config section of my instance. Does this feature need to be enabled or is it something special they set up on their platform?

**Comment by j0k3r** [comment] 2023-05-29 19:27
It's a special feature not available in the open source version. Only in wallabag.it.

**Comment by nicosomb** [comment] 2023-06-13 08:59
I can close this issue, as it's a duplicate of this feature request: https://github.com/wallabag/wallabag/issues/239

**Closed by nicosomb** 2023-06-13 08:59 UTC
