### ISSUE TITLE
Add support for MathJax when fetching

### ISSUE THREAD

**Issue by pVesian** [wallabag/wallabag#3234] opened 2017-06-16 09:51 UTC
Hi,

### Issue details

Fetching articles with math formulas powered by MathJax seems not to work. The same behavior is observed on https://f43.me/feed/test. In the example below, _Σ_ (amongst more than 100 others) is transformed into _$\Sigma$_.

### Environment

wallabagit

### Steps to reproduce/test case

Fetch https://zestedesavoir.com/tutoriels/1669/statistique-descriptive-a-une-dimension/ and look at the sentence starting with "En particulier, comprendre l’indice de sommation".

Thanks!

**Comment by nicosomb** [comment] 2017-06-16 19:41
I close, it's a duplicate of #1408 ;-)

**Closed by nicosomb** 2017-06-16 19:41 UTC
