### ISSUE TITLE
annotation function not reachable on mobile browser like safari

### ISSUE THREAD

**Issue by wirsel** [wallabag/wallabag#3659] opened 2018-05-30 10:19 UTC
### Issue details

Annotation function in wallabag's web app supports annotations ( highlighting text and adding comments ). This works fine using chrome on windows laptop. But when using the wallabag web app via mobile browser (Safari or iCabMobile) on iPad adding annotations does not work. You can select text, but I guess the mobile browser shows only the build in context menu from the underlying mobile OS, means wallabags icon to add an annotations does not show up like it does on Chrome running on windows.

### Environment
* 14 day trail account on https://app.wallabag.it/
* iOS 11.3.1
* ipad
* Safari browser or iCabMobile

### Steps to reproduce/test case

* login to your wallabag account on  https://app.wallabag.it/ using Safari on ipad
* select an article
* select a text-> the annotation icon (see attached screen shot) does not appear
![wallabag annotation icon](https://user-images.githubusercontent.com/5762887/40714647-85247832-6403-11e8-9b07-a40d8ed11c34.jpg)

**Comment by pheraph** [comment] 2019-01-25 13:17
Duplicate of #2749.

**Closed** 2019-01-25 13:20 UTC
