### ISSUE TITLE
Wrong display in wallabag

### ISSUE THREAD

**Issue by j0k3r** [wallabag/wallabag#3906] opened 2019-03-12 12:40 UTC
*Sent by Randy Haupt and automatically created by email*

---

https://superuser.com/questions/276873/how-do-i-remove-the-recent-places-icon-from-my-windows-7-desktop

**Comment by Kdecherf** [comment] 2019-03-12 21:33
Could be a duplicate of #3644

**Closed** 2019-03-13 08:30 UTC
Labels: Site Config
