### ISSUE TITLE
Orphaned tags.

### ISSUE THREAD

**Issue by Rurik19** [wallabag/wallabag#2270] opened 2016-09-07 08:33 UTC
### Issue details

After deleting article with unique tag, this tag remains in the tags table, accessible from nowhere.
API and UI the have the same behaviour

**Comment by j0k3r** [comment] 2016-10-07 20:19
Are you sure about from the web interface?
Because we should remove the tag if no entries are associated: https://github.com/wallabag/wallabag/pull/1663 (see https://github.com/wallabag/wallabag/commit/567421af5019bf5937aa2b4214b405d87a1f1f86#diff-ebd626b4b8a67462013f01007d7a4637R70)

**Comment by Rurik19** [comment] 2016-10-09 11:21
Just checked web interface:

- add new tag to the article
- delete article (by clicking on trash icon on article card)
- i still see the tag in database with phpmyadmin

**Comment by j0k3r** [comment] 2016-10-09 11:59
Did you try on the master directly? Because, as the milestone says, it'll be released with the 2.1.2 version which is not yet available.

**Comment by Rurik19** [comment] 2016-10-10 03:59
Yes, that is on 2.1.1 from master.

**Comment by j0k3r** [comment] 2016-10-10 05:14
Master is the upcoming 2.1.2.
Are you sure that tag isn't associated to an other entry?

**Comment by Rurik19** [comment] 2016-10-10 06:22
Yes, that was "Just_for_test" tag :)

**Comment by j0k3r** [comment] 2016-10-10 07:07
Well, it works for me, so..
@nicosomb @tcitworld could you please try on your side?

**Comment by nicosomb** [comment] 2016-10-10 09:53
I have the problem with SQLite too.

**Comment by j0k3r** [comment] 2016-10-11 19:07
@Rurik19 could you please tell me step by step all action to reproduce the bug? I've tried on PostgreSQL, MySQL & SQLite and it works every time.

**Comment by Rurik19** [comment] 2016-10-12 04:45
**@j0k3r**
0) PHP Version 5.6.24-0+deb8u1
    MySQL ver: 5.5.52-0+deb7u1
1) git pull origin master
2) SYMFONY_ENV=prod composer install  -o --prefer-dist
3) add tag to article
4) delete article
![image](https://cloud.githubusercontent.com/assets/1955806/19297542/60201c4a-905f-11e6-8cd2-fcada7adbb9d.png)
5) look at phpmyadmin
![image](https://cloud.githubusercontent.com/assets/1955806/19297598/03390202-9060-11e6-99d3-591f1b6f19f6.png)

**Comment by nicosomb** [comment] 2016-10-15 12:55
In fact, what is the problem with this behavior?
The tag is still in database because maybe it's used by an other user (a tag has no relation with a user). 
It stays in database but if we affect this tag to a new article, this tag will be used.

**Comment by Kdecherf** [comment] 2019-01-16 17:04
Is this issue still relevant?

**Closed** 2019-06-05 13:28 UTC
Labels: Bug
