### ISSUE TITLE
Wrong display in wallabag (fodors.com)

### ISSUE THREAD

**Issue by RayBB** [wallabag/wallabag#5148] opened 2021-03-13 22:06 UTC
**Before submitting the issue, please read:**
If wallabag can't parse / extract content for a given link, please first read the documentation about it:
http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

We have a lot of requests about fetching config issue. It'll help us A LOT if you give a try to fix it on your own following the doc.
If you failed to fix it yourself, tick the following boxes:
- [x] I've tried myself without success
- [x] I've replaced `HOST` in the issue title with the host of the URL that can't be fetched (ie: `nytimes.com`, `20minutes.fr`, `bbc.com`, etc.)

**Content related:**
 - URL: https://www.fodors.com/news/coronavirus/i-planned-to-move-to-hawaii-and-then-i-realized-why-i-shouldnt
 - wallabag version: wallabag.it hosted version as of Mar 13, 2020

**Describe what's wrong:**
Wallabag shows this error instead of body content:
`error code: 1005`

Testing of f43.me shows "error_message: | Forbidden"

I figure even if this is just an anti-scraping measure we can't work around then there still may be a different bug since this strange error code is displaying in GUI

**Comment by Kdecherf** [comment] 2021-03-13 22:37
@RayBB I'm unable to reproduce this issue, the article is fetched successfully on two of my instances.

**Comment by RayBB** [comment] 2021-03-13 22:43
@Kdecherf can you reproduce it on https://f43.me/feed/test ?

**Comment by Kdecherf** [comment] 2021-03-14 00:52
@RayBB I can reproduce your error on f43.me.

The returned error ("1005") looks like a ban from Cloudflare. Unfortunately there's not much to do.

**Comment by RayBB** [comment] 2021-03-14 02:58
I see so it's related to #1399 

Are there instructions I can share to the maintainer of the website that would allow saving in wallabag?
I imagine this may be a setting in cloudflare to add wallabag.it IPs to an allowlist or something.

**Comment by j0k3r** [comment] 2023-04-13 09:23
Duplicate of #5423

**Closed by j0k3r** 2023-04-13 09:23 UTC
Labels: Site Config
