### ISSUE TITLE
Relative URL support for /wallassets?

### ISSUE THREAD

**Issue by 4oo4** [wallabag/wallabag#3512] opened 2017-12-16 17:37 UTC
### Issue details
After upgrading to 2.3.0, certain fonts were failing to load from `/wallassets` and breaking the UI, I noticed in my access logs that there were a lot of 404s since Wallabag was sending those to `/wallassets`, even though I specified the subdirectory I run Wallabag from `/wallabag/web` during the upgrade. For now, I'm able to get around it with an nginx rewrite rule, I didn't know if there was something else I need to do so it resolves the asset URLs correctly?

`rewrite ^(/wallassets/)(.*)$ https://example.com/wallabag/web/wallassets/$2 permanent;`

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.0
* How did you install wallabag? Via `git clone` or by downloading the package? `git checkout 2.3.0; make update`
* Last wallabag version that did not exhibit the issue (if applicable): 2.2.3
* php version: PHP 7.1.12-3
* OS: Ubuntu 16.04
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case

Upgrade wallabag from 2.2.3 to 2.3.0

### Access logs
```
xxx.xxx.xxx.xxx - - [16/Dec/2017:11:33:39 -0600] "GET /wallassets/fonts/MaterialIcons-Regular.woff HTTP/2.0" 404 241 "https://example.com/wallabag/web/wallassets/material.css" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"
xxx.xxx.xxx.xxx - - [16/Dec/2017:11:33:39 -0600] "GET /wallassets/fonts/Roboto-Bold.woff HTTP/2.0" 404 231 "https://example.com/wallabag/web/wallassets/material.css" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"
xxx.xxx.xxx.xxx - - [16/Dec/2017:11:33:39 -0600] "GET /wallassets/fonts/Roboto-Medium.woff HTTP/2.0" 404 233 "https://example.com/wallabag/web/wallassets/material.css" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"
xxx.xxx.xxx.xxx - - [16/Dec/2017:11:33:39 -0600] "GET /wallassets/fonts/Roboto-Regular.woff HTTP/2.0" 404 234 "https://example.com/wallabag/web/wallassets/material.css" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"
xxx.xxx.xxx.xxx - - [16/Dec/2017:11:33:39 -0600] "GET /wallassets/fonts/Roboto-Light.woff HTTP/2.0" 404 232 "https://example.com/wallabag/web/wallassets/material.css" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"
xxx.xxx.xxx.xxx - - [16/Dec/2017:11:33:39 -0600] "GET /wallassets/fonts/MaterialIcons-Regular.ttf HTTP/2.0" 404 240 "https://example.com/wallabag/web/wallassets/material.css" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"
```

### Screenshots:
![selection_009](https://user-images.githubusercontent.com/15698835/34072734-63e96d72-e252-11e7-85bf-db5e69f138cb.png)
![selection_010](https://user-images.githubusercontent.com/15698835/34072898-06486490-e255-11e7-97aa-862c487726b3.png)

**Comment by prolibre** [comment] 2017-12-17 08:38
https://github.com/wallabag/wallabag/issues/3485

**Comment by nicosomb** [comment] 2017-12-17 09:52
This issue is a duplicate of #3485.

**Closed by nicosomb** 2017-12-17 09:52 UTC
Labels: Bug

**Comment by 4oo4** [comment] 2017-12-17 15:27
Thanks, I'll add my nginx rewrite over there in case anyone else needs it.
