### ISSUE TITLE
Can't fetch articles from Forbes.com

### ISSUE THREAD

**Issue by TRox1972** [wallabag/wallabag#1978] opened 2016-04-24 23:03 UTC
When trying to fetch articles from Forbes.com, [like this one](http://www.forbes.com/sites/jacobmorgan/2014/08/19/privacy-is-completely-and-utterly-dead-and-we-killed-it/#980f7b6dfbd6), it only fetches the welcome page; the title becomes "Forbes Welcome" and the content "wallabag can't retrieve contents for this article. Please report this issue to us." I am running version 2.0.3 on desktop.

**Comment by benages** [comment] 2016-05-10 12:46
Duplicate of issue https://github.com/wallabag/wallabag/issues/1452

**Comment by nicosomb** [comment] 2016-05-10 12:54
:+1:

**Closed by nicosomb** 2016-05-10 12:54 UTC
Labels: Site Config
