### ISSUE TITLE
tag cant be added on the page if the article

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#2706] opened 2016-12-16 12:35 UTC
### Issue details
WE cant add tag on article, with the mobile display 
### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.5
* How did you install wallabag? Via `git clone` or by downloading the package? Git
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7
* OS:debian 5.8
* type of hosting (shared or dedicated):dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): postgresql

### Steps to reproduce/test case
When displaying an article, we can't edit the article to add tags

**Comment by nicosomb** [comment] 2016-12-16 12:36
Duplicate of https://github.com/wallabag/wallabag/issues/2376 ;-) 
Fixed and will be available in 2.2.

**Closed by nicosomb** 2016-12-16 12:36 UTC

**Comment by foxmask** [comment] 2016-12-16 12:43
Ok. I searched un thé opened issue . I'm clumsy ;)

**Comment by nicosomb** [comment] 2016-12-16 12:43
You searched a thé? I only drink ☕️, sorry!

**Comment by foxmask** [comment] 2016-12-16 12:46
I spent most of mytime to fix typo bikose of ze non anglish kiborde 😎
