### ISSUE TITLE
Download the original content as well

### ISSUE THREAD

**Issue by gerroon** [wallabag/wallabag#3715] opened 2018-09-05 01:59 UTC
Hi

It would be so nice if Wallabag also captures the original site (complete html and screenshot), in case the page disappears, or the content is not retrieved proerly or just for comparison purposes.

thanks

**Comment by Kdecherf** [comment] 2018-09-05 09:10
Hello,

Maybe a link to the nearest capture on the wayback machine could be enough?

**Comment by gerroon** [comment] 2018-09-05 15:04
Hi, not sure would not be nice to have the actual copy locally?

**Comment by childnode** [comment] 2018-11-05 21:02
hi, <sup>_stumbling over this issue while searching new tools that can consume my old [ScrapBook](https://addons.mozilla.org/de/firefox/addon/scrapbook/) backups ;)_</sup>

@gerroon I'm not sure, if your usecase is similar to mine: wallabag is not the right product for that "archiving" thing right away if you ask me, perhaps you might find s.th. here [/iipc/awesome-web-archiving](/iipc/awesome-web-archiving) or [//archive.today](//archive.today) 🕺

**Comment by kai11** [comment] 2019-08-26 11:36
Combination of wallabag and https://archivebox.io/ should work.
Set up archive box to work with wallabag rss

**Comment by gdesmott** [comment] 2020-12-30 11:09
I'm also interested in this feature. Neither option could do (link to wayback machine or archivebox integration) but I'd like to avoid having two enter each link in two places. Is that currently possible?

**Comment by Kdecherf** [comment] 2022-11-11 15:55
Duplicate of #1660

**Closed by Kdecherf** 2022-11-11 15:55 UTC
