### ISSUE TITLE
unable to authenticate : OAuth2 authentication required

### ISSUE THREAD

**Issue by gpapin** [wallabag/wallabag#2768] opened 2017-01-19 11:39 UTC
### Issue details

When I use the chrome extension to add something to wallabag it comes back with a red error box saying :  Failed to get tags https://wallabag.company.com/api/tags.json
{"error":"access_denied","error_description":"OAuth2 authentication required"}

### Environment

* wallabag version : 2.1.5
* How did you install wallabag? Docker image
* Last wallabag version that did not exhibit the issue (if applicable): not applicable
* php version: whatever is used in the latest docker image
* OS: not applicable
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): docker default

One detail that might be important is that wallabag is not exposed to the world it's internal only.

The weird thing is I can see wallabag and the extension are talking to each other ans access seems to be granted: 

![developer wallabag](https://cloud.githubusercontent.com/assets/3064311/22105407/bac9d012-de3b-11e6-9de9-74998d8f352a.png)
![wallabag extension](https://cloud.githubusercontent.com/assets/3064311/22105406/bac83aea-de3b-11e6-9966-1c39fd33b306.png)

**Comment by nicosomb** [comment] 2017-01-19 12:49
Hello @gpapin, 

> One detail that might be important is that wallabag is not exposed to the world it's internal only.

So the Chrome addon can't connect to your wallabag instance.

**Comment by gpapin** [comment] 2017-01-19 13:07
> So the Chrome addon can't connect to your wallabag instance.

And why would that be ? from the option screenshot above you can see that it can connect and even get a token.

When I use this extension I'm always either connected to the same network or using a VPN. the DNS is always up to date so wallabag.company.com is always pointing to the webserver.

The only thing that would make sense is that if the chrome extension need to push the content through a external api somewhere and that this api would then have to talk to my internal server. But I don't see why would that be the case and the error message I have doesn't seems to indicate that it is a connection error.

**Comment by nicosomb** [comment] 2017-01-19 13:09
The extension uses the API of your wallabag installation. 

Did you create your token thanks to the Chrome addon or directly in your wallabag web application?

**Comment by gpapin** [comment] 2017-01-19 13:10
In fact they can **connect** it's the **authentication** I have problem with, I get this in the server's log when trying to save something: 

```
::ffff:172.18.0.10 - - [19/Jan/2017:13:08:41 +0000] "POST /oauth/v2/token HTTP/1.1" 200 275 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36"
::ffff:172.18.0.10 - - [19/Jan/2017:13:08:41 +0000] "GET /api/tags.json HTTP/1.1" 401 89 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36"
::ffff:172.18.0.10 - - [19/Jan/2017:13:08:41 +0000] "POST /api/entries.json HTTP/1.1" 401 89 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36"
```

The token was created using the chrome extension directly

**Comment by nicosomb** [comment] 2017-01-19 13:14
Do you have some errors in your wallabag/var/logs files?

**Comment by gpapin** [comment] 2017-01-19 13:16
I just realised I use [this extension ](https://chrome.google.com/webstore/detail/wallabagger/gbmgphmejlcoihgedabhgjdkcahacjlj)
and the one from the "about" page of my installation is [this one](https://chrome.google.com/webstore/detail/wallabagit/peehlcgckcnclnjlndmoddifcicdnabm) : 

Will have a look at logs right now

**Comment by nicosomb** [comment] 2017-01-19 13:17
Oops, the about page is out dated.

**Comment by gpapin** [comment] 2017-01-19 13:29
Not sure I look in the right place there is not much in /var/log

/var/log/nginx/error.log -> empty
/var/log/nginx/access.log -> empty
/var/log/php-fpm.log -> 
```
[17-Jan-2017 22:35:12] NOTICE: fpm is running, pid 265
[17-Jan-2017 22:35:12] NOTICE: ready to handle connections
[18-Jan-2017 22:05:35] NOTICE: Terminating ...
[18-Jan-2017 22:05:35] NOTICE: exiting, bye-bye!
[18-Jan-2017 23:28:19] NOTICE: fpm is running, pid 265
[18-Jan-2017 23:28:19] NOTICE: ready to handle connections
```
/var/log/php7/ -> folder empty

Do you know where is stored the wallabag symfony's logs in the docker image ?

**Comment by nicosomb** [comment] 2017-01-19 13:30
something like `/var/www/wallabag/var/logs`?

**Comment by gpapin** [comment] 2017-01-19 13:31
found the folder but it's empty appart from a .gitkeep file

**Comment by j0k3r** [comment] 2017-01-20 07:28
Could you
- change [that line](https://github.com/wallabag/wallabag/blob/master/app/config/config_prod.yml#L18) and replace `error` by `warning`
- clear your cache `rm -rf var/cache/*`

And try again? (it might take a bit longer to re-display the first page because of the empty cache)

**Comment by gpapin** [comment] 2017-01-20 11:23
Ok so I had to go even lower than warning to have something, here is the trace that correspond to me clicking the chrome extension - I hope it will help solve this mystery :) 

```
[2017-01-20 11:21:03] request.INFO: Matched route "fos_oauth_server_token". {"route":"fos_oauth_server_token","route_parameters":{"_controller":"fos_oauth_server.controller.token:tokenAction","_route":"fos_oauth_server_token"},"request_uri":"http://wallabag.privateweb.fr/oauth/v2/token","method":"POST"} []
[2017-01-20 11:21:03] request.INFO: Matched route "api_get_tags". {"route":"api_get_tags","route_parameters":{"_controller":"Wallabag\\ApiBundle\\Controller\\TagRestController::getTagsAction","_format":"json","_route":"api_get_tags"},"request_uri":"http://wallabag.privateweb.fr/api/tags.json","method":"GET"} []
[2017-01-20 11:21:03] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-01-20 11:21:03] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:70)"} []
[2017-01-20 11:21:03] security.DEBUG: Calling Authentication entry point. [] []
[2017-01-20 11:21:03] request.INFO: Matched route "api_post_entries". {"route":"api_post_entries","route_parameters":{"_controller":"Wallabag\\ApiBundle\\Controller\\EntryRestController::postEntriesAction","_format":"json","_route":"api_post_entries"},"request_uri":"http://wallabag.privateweb.fr/api/entries.json","method":"POST"} []
[2017-01-20 11:21:03] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-01-20 11:21:03] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:70)"} []
[2017-01-20 11:21:03] security.DEBUG: Calling Authentication entry point. [] []
```

**Comment by nicosomb** [comment] 2017-02-14 17:08
@Simounet @Rurik19 any idea about this issue?

**Comment by Rurik19** [comment] 2017-02-15 04:48
Hmm.... We should see what /oauth/v2/token request returns. Is there authentication token OK?
@gpapin Don't  you want to update wallabagger to v1.3?

**Comment by gpapin** [comment] 2017-02-16 10:22
The docker image is up to date but now I can't even login... it says : 
```
Materialize.toast('An exception occurred while executing &#039;SELECT t0.username AS username_1, t0.username_canonical AS username_canonical_2, t0.email AS email_3, t0.email_canonical AS email_canonical_4, t0.enabled AS enabled_5, t0.salt AS salt_6, t0.password AS password_7, t0.last_login AS last_login_8, t0.confirmation_token AS confirmation_token_9, t0.password_requested_at AS password_requested_at_10, t0.roles AS roles_11, t0.id AS id_12, t0.name AS name_13, t0.created_at AS created_at_14, t0.updated_at AS updated_at_15, t0.authCode AS authCode_16, t0.twoFactorAuthentication AS twoFactorAuthentication_17, t0.trusted AS trusted_18, t19.id AS id_20, t19.theme AS theme_21, t19.items_per_page AS items_per_page_22, t19.language AS language_23, t19.rss_token AS rss_token_24, t19.rss_limit AS rss_limit_25, t19.reading_speed AS reading_speed_26, t19.pocket_consumer_key AS pocket_consumer_key_27, t19.action_mark_as_read AS action_mark_as_read_28, t19.list_mode AS list_mode_29, t19.user_id AS user_id_30 FROM &quot;wallabag_user&quot; t0 LEFT JOIN &quot;wallabag_config&quot; t19 ON t19.user_id = t0.id WHERE t0.username_canonical = ? LIMIT 1&#039; with params [&quot;gpapin&quot;]:

SQLSTATE[HY000]: General error: 1 no such column: t19.action_mark_as_read', 4000)
```
The schema obviously changed and it hasn't been updated when I updated the docker image

**Comment by gpapin** [comment] 2017-02-16 10:36
So after installing dependencies and updating the database manually I was able to login again.

Here is the commands to run: 

First get into the docker image:
```docker exec -it wallabag /bin/ash```

Then cd to the app directory:
```cd var/www/wallabag/```

Install dependencies
```composer install```

update the database
```php bin/console doctrine:schema:update --force```

**Comment by gpapin** [comment] 2017-02-16 10:48
@Rurik19 I've sorted my issue while I was upgrading I am using wallabager v1.3 already.
I was running wallabag 2.1.5 when the problem occurred and now I am on wallabag 2.2.1 but I still have the same issue.

**Comment by Simounet** [comment] 2017-02-16 11:19
Hi,
Is your page saved? I mean we are getting the tags after saving the page. I'm trying to know why it fails.
Do you have any error on Wallabagger block in `chrome://extensions/`?

**Comment by gpapin** [comment] 2017-02-16 11:39
No the page is not saved as I can't authorize against the server so even if the extension request the tags the server answers with a 401. I've tried to add a page directly though the server and it gives me a error 500...

```Setting "download_images_enabled" couldn't be found.``` 

I go from a error to another 😞  ...

**Comment by gpapin** [comment] 2017-02-16 11:51
Ok so since the upgrade I can't see articles previously saved, save new ones or deleting them so basically can't do anything.

At this point it's so broken that I think it's probably worth doing a fresh install...

**Comment by gpapin** [comment] 2017-02-16 12:03
Right so after a bit of digging I've found [this post ](https://wallabag.org/en/news/new-release-wallabag-2-2-1)I then ran this command : 
```php bin/console doctrine:migrations:migrate --no-interaction -e=prod``` and that seems to fix all issues about settings not set, so now I can now use the webserver again but the extension still can't authorize..

**Comment by Massedil** [comment] 2017-10-24 14:46
Same problem for me, but without a Docker image : I'm just using PHP FPM.

Can I give you some data to help you identifying the problem ?

**Comment by sparunakian** [comment] 2018-03-24 13:24
Hi,

I encounter the same issue (Wallabag 2.3.2, php-fpm 7.2.3, Apache) with the API (Android app and Wallabager). I do not encounter this issue with mod_php and I don't have errors in php logs.

In the logs when requesting the API via Wallabager with the "Get token" button:
```
[2018-03-24 13:32:17] request.INFO: Matched route "fos_oauth_server_token". {"route":"fos_oauth_server_token","route_parameters":{"_controller":"fos_oauth_server.controller.token:tokenAction","_route":"fos_oauth_server_token"},"request_uri":"https://wallabag/oauth/v2/token","method":"POST"} []
[2018-03-24 13:32:22] request.INFO: Matched route "api_get_tags". {"route":"api_get_tags","route_parameters":{"_controller":"Wallabag\\ApiBundle\\Controller\\TagRestController::getTagsAction","_format":"json","_route":"api_get_tags"},"request_uri":"https://wallabag/api/tags.json","method":"GET"} []
[2018-03-24 13:32:24] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-03-24 13:32:24] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /usr/share/webapps/wallabag/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:68)"} []
[2018-03-24 13:32:24] security.DEBUG: Calling Authentication entry point. [] []
```

During the test, I've used mitmproxy to dump http headers:
```
POST https://wallabag/oauth/v2/token

Request:
Host:             wallabag
User-Agent:       Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
Accept:           application/json
Accept-Language:  fr
Accept-Encoding:  gzip, deflate, br
content-type:     application/json
origin:           moz-extension://79a724b7-1655-4319-93b4-61d94c5d9f52
Content-Length:   209
DNT:              1
Connection:       keep-alive
JSON
{
    "client_id": "CLIENT_ID",
    "client_secret": "CLIENT_SECRET",
    "grant_type": "password",
    "password": "PASSWORD",
    "username": "USER"
}

Response:
Date:                         Sat, 24 Mar 2018 12:32:19 GMT
Server:                       Apache
Cache-Control:                no-store, private
Pragma:                       no-cache
Access-Control-Allow-Origin:  moz-extension://79a724b7-1655-4319-93b4-61d94c5d9f52
Upgrade:                      h2
Connection:                   Upgrade, Keep-Alive
X-Robots-Tag:                 noindex, nofollow
Keep-Alive:                   timeout=5, max=100
Transfer-Encoding:            chunked
Content-Type:                 application/json
JSON                                                                                                                                                                    [m:auto]
{
    "access_token": "ACCESS_TOKEN",
    "expires_in": 3600,
    "refresh_token": "REFRESH_TOKEN",
    "scope": null,
    "token_type": "bearer"
}
```

```
GET https://wallabag/api/tags.json

Request:
Host:             wallabag
User-Agent:       Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
Accept:           application/json
Accept-Language:  fr
Accept-Encoding:  gzip, deflate, br
content-type:     application/json
authorization:    Bearer ACCESS_TOKEN
origin:           moz-extension://79a724b7-1655-4319-93b4-61d94c5d9f52
DNT:              1
Connection:       keep-alive

Response:
Date:                         Sat, 24 Mar 2018 12:32:24 GMT
Server:                       Apache
WWW-Authenticate:             Bearer realm="Service", error="access_denied", error_description="OAuth2 authentication required"
Cache-Control:                no-store, private
Pragma:                       no-cache
Access-Control-Allow-Origin:  moz-extension://79a724b7-1655-4319-93b4-61d94c5d9f52
X-Robots-Tag:                 noindex, nofollow
Keep-Alive:                   timeout=5, max=99
Connection:                   Keep-Alive
Transfer-Encoding:            chunked
Content-Type:                 application/json
JSON
{
    "error": "access_denied",
    "error_description": "OAuth2 authentication required"
}
```

When using curl to make a GET request on the API, with the previous token in parameter, it works:
```
curl --get "https://wallabag/api/tags.json?access_token=ACCESS_TOKEN"
[]%
```
(I don't have any tags)

But when using the "authorization" header, it doesn't work:
```
curl --get -H 'authorization: Bearer ACCESS_TOKEN' "https://wallabag/api/tags.json"
{"error":"access_denied","error_description":"OAuth2 authentication required"}%
```
Let me known if I can provide you with more elements or if I can be of any help concerning this issue!

**Comment by eatallthegames** [comment] 2018-08-03 15:00
Same issue as sparunakian

**Comment by j0k3r** [comment] 2018-10-02 09:17
@nilsglow your PR will be very welcome :+1:

**Comment by j0k3r** [comment] 2018-10-15 09:03
As the problem is solved and the doc have been updated, I'm closing the issue.

**Closed by j0k3r** 2018-10-15 09:03 UTC
Labels: Bug
