### ISSUE TITLE
Wishlist: Show article creation date

### ISSUE THREAD

**Issue by ngosang** [wallabag/wallabag#2827] opened 2017-02-01 21:14 UTC
I would like to have the article creation date at the top of the article, just below the title. I mean the date in the original article, not the date it was fetched.
Related https://github.com/wallabag/android-app/issues/414

**Comment by j0k3r** [comment] 2017-02-02 08:11
There is a working in progress on that point https://github.com/j0k3r/graby/pull/68
But it'll be hard to find the date creation of each article.

Also, a duplicate of https://github.com/wallabag/wallabag/issues/2590

**Closed by j0k3r** 2017-02-02 08:11 UTC

**Comment by ngosang** [comment] 2017-03-07 21:55
> But it'll be hard to find the date creation of each article.

I think it's easier than you think. Most articles have a date tagged with "<time>" tag.

**Comment by j0k3r** [comment] 2017-03-08 07:56
We'll see :slightly_smiling_face:
