### ISSUE TITLE
EPUB export - special char in chapter titles breaks TOC

### ISSUE THREAD

**Issue by mcgohier** [wallabag/wallabag#2512] opened 2016-10-29 11:46 UTC
### Issue details

When the title of an article contains a special html character (such as an "&") and the article is exported as an epub ebook, the table of content in the epub is broken.
### Environment
- wallabag version (or git revision) that exhibits the issue: 2.1.2
- How did you install wallabag? Via git clone
- Last wallabag version that did not exhibit the issue (if applicable): unknown
- php version: 7.0.12
- OS: Arch linux
- type of hosting (shared or dedicated): dedicated
- which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite
### Steps to reproduce/test case

Add an "&" in the title of an article. Export it as an ebook with the epub format.
When I read the ebook then on the Table of Content: 
- in the firefox extension EPUBreader, an XML parsing error appears on the page
- on FBreader with my tablet, the title of the chapter is not complete ans the following chapters do not appear in the TOC.
### Another problem about the chapter titles

The title of the article appears in the Table of Content but it does not appear at the beginning of the article. When reading, and switching from an article to the following one, it is difficult to know which article is read.

**Comment by Kdecherf** [comment] 2019-01-06 18:05
I can't reproduce this issue anymore, can we close it?

**Comment by Kdecherf** [comment] 2019-03-17 14:49
Closing this issue as there hasn't been much activity on it. Feel free to re-open if it's still relevant.

**Closed by Kdecherf** 2019-03-17 14:49 UTC
Labels: Awaiting response, Bug, good first issue
