### ISSUE TITLE
Create .deb package

### ISSUE THREAD

**Issue by theonlydoo** [wallabag/wallabag#1853] opened 2016-04-05 09:17 UTC
And why not a .deb repository with signed debs ?

**Comment by nicosomb** [comment] 2016-04-05 09:35
See https://github.com/liip/sf2debpkg

**Comment by theonlydoo** [comment] 2016-04-05 09:38
roger that!

**Comment by nicosomb** [comment] 2016-11-30 08:51
Duplicate of https://github.com/wallabag/wallabag/issues/1014

**Closed by nicosomb** 2016-11-30 08:51 UTC
Labels: Feature
