### ISSUE TITLE
Duplicate tags on import

### ISSUE THREAD

**Issue by jlnostr** [wallabag/wallabag#1981] opened 2016-04-25 09:57 UTC
### Issue details
After I migrated my data from Pocket I saw that some tags are duplicated. 

![image](https://cloud.githubusercontent.com/assets/5391936/14779928/bb2129d2-0ada-11e6-811f-d03879f13892.png)
wallabag can't count, eh? :D

Access over the API:
![Access over API](https://cloud.githubusercontent.com/assets/5391936/14779492/a5df2012-0ad8-11e6-9e3f-c27008d71d4e.png)

### Environment
* wallabag version (or git revision) that exhibits the issue: 2.0.3
* How did you install wallabag? Via `git clone` or by downloading the package? downloading
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 5.5.10
* OS: CentOS
* type of hosting (shared or dedicated): shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

**Comment by nicosomb** [comment] 2016-04-27 19:55
In `ContentProxy::assignTagsToEntry`, we have `$tagEntity = $this->tagRepository->findOneByLabel($label);` to check if tag already exists. 
But in fact, when we create a tag via the import, all data are not yet really stored in database until we flush data. 

@j0k3r any idea?

**Comment by j0k3r** [comment] 2016-04-27 20:18
Maybe http://stackoverflow.com/a/7879164/569101 ?

**Comment by erixtekila** [comment] 2016-05-17 09:28
Same error here.
Do you need my json file to test ?

**Comment by j0k3r** [comment] 2016-05-17 09:56
@erixtekila no it's ok, we already know how to reproduce the bug. Thanks.

**Comment by erixtekila** [comment] 2016-05-17 10:41
@j0k3r Will it be fixed in a next release, please ?

**Comment by j0k3r** [comment] 2016-05-17 11:30
@erixtekila I've no idea.

**Comment by lapineige** [comment] 2016-07-20 08:12
I've the same issue when importing Wallabag v1 json file. Debian Jessie, wallabag 2.0.5, MySQL/MariaDB

Only a few tags are duplicated, and not sorted correctly, and always with a tag with all the articles, and all the other with just 1.
I can give the list if needed (privately).

I hope this helps :)

**Comment by lapineige** [comment] 2016-07-28 16:53
Up :)

Do you know if there is any way to fix this ?

**Comment by lapineige** [comment] 2016-08-19 13:02
Up :)

**Comment by j0k3r** [comment] 2016-08-19 13:27
Still nothing, sorry. We need to find a way.

**Comment by lapineige** [comment] 2016-08-19 13:40
Ok, thanks for the information :)

**Comment by lapineige** [comment] 2016-08-22 16:52
(Should I open another ticket ?)
Do you know if there is any way to remove all articles from the database ? (From the command-line ?)
It might help me to test this bug several times, without re-installing all the time.
Thanks :)

**Comment by j0k3r** [comment] 2016-08-22 19:01
@lapineige don't bother in testing it, we'll do on our side 😉

**Comment by lapineige** [comment] 2016-08-25 20:22
Oh and also, it's not possible to filter by any tag, they are not click-able - even when not duplicated.

**Comment by lapineige** [comment] 2016-08-25 21:24
And after an export and import in another instance, the tags were all lost. I don't know how the management of the tags is done, but it seems like there is an issue during storage or reading/exporting.

**Comment by lapineige** [comment] 2016-08-28 16:42
@j0k3r do you think I should open an issue for that:
>   it's not possible to filter by any tag, they are not click-able - even when not duplicated.

Or do you think is related to the issue of duplication ?

**Comment by j0k3r** [comment] 2016-08-28 20:06
It's already done in the upcoming 2.1: https://github.com/wallabag/wallabag/issues/1798

**Comment by lapineige** [comment] 2016-08-29 08:37
Oh great, I was thinking it was a bug as it was available in 1.9. If I understand well, a lot of thing are still rebuild / improved.
(the 2.1 milestone list of lot of great tags improvements)

So let's wait for 2.1, great :)

--------
For this bug, if you need me to do any test, please just ping me ;)

**Comment by lapineige** [comment] 2016-09-24 12:38
Any update ? Can I help you in any way ? Thanks :-)

**Comment by j0k3r** [comment] 2016-09-25 07:41
This is in fact partially solve by the async import that will be available in the 2.1.

**Comment by lapineige** [comment] 2016-09-25 07:51
Cool, so I will update this issue after testing the 2.1 :)

**Comment by j0k3r** [comment] 2016-09-25 20:34
Will be fixed in 2.1, even for non async import.

**Comment by lapineige** [comment] 2016-10-09 18:25
I confirm, it's fixed even for non async import :) (in fact I wasn't able to test with async import)

**Comment by lapineige** [comment] 2016-10-09 18:26
(Sorry, I did a mistake with the issue status)

To test again with async import, I would like to remove all the articles. Is there a way (SQL command ?) to do it ? Thanks :)

**Closed by lapineige** 2016-10-09 18:25 UTC
Labels: Bug

**Comment by tcitworld** [comment] 2016-10-09 18:28
`DELETE * FROM entries` or something like that ?

**Comment by lapineige** [comment] 2016-10-09 18:51
Thanks. Now where should I apply it ? on /data/db/wallabag.sqlite ? (and how ? I'm not a big SQL user ^^)

**Comment by tcitworld** [comment] 2016-10-09 18:54
Yup.

**Comment by lapineige** [comment] 2016-10-09 19:16
I probably do it in a wrong way, nothing happen. Could you give me the full bash command ? Thanks a lot :)

**Comment by tcitworld** [comment] 2016-10-09 19:30
You must do `sqlite3 data/db/wallabag.sqlite`
Then, 
* `DELETE FROM wallabag_entry_tag;`
* `DELETE FROM wallabag_entry;`
* `DELETE FROM wallabag_tag;`

Should do it. Next version (major ?) will come with a button to reset your account.

**Comment by nicosomb** [comment] 2016-10-09 19:32
Next minor version 😜  2.2

**Comment by lapineige** [comment] 2016-10-09 20:03
I tried with entries instead of entry ^^ :/

What's the difference between  wallabag_entry_tag and wallabag_tag ? One for the entries, one for the entries sorted by tags ?

Thanks for your help, I will try again with Regis import.

@nicosomb I just updated to 2.1.1, but I can't wait to see the next one, major or minor ;)

**Comment by nicosomb** [comment] 2016-10-09 20:09
![](http://s1.dmcdn.net/4R7A.jpg)

(Regis import 😂 )

**Comment by lapineige** [comment] 2016-10-09 20:10
Excellent ^^
(fixed :D)

**Comment by tcitworld** [comment] 2016-10-09 20:28
> What's the difference between wallabag_entry_tag and wallabag_tag ? One for the entries, one for the entries sorted by tags ?

The second lists the tags, the first connects the entries to the tags.

**Comment by lapineige** [comment] 2016-10-09 20:31
Ok thx.

But in my case, clearing those list did nothing :(
Any idea ?

**Comment by tcitworld** [comment] 2016-10-09 20:33
Are you sure you're using sqlite ? o_0

**Comment by lapineige** [comment] 2016-10-09 20:38
Yeah. I had to install sqlite3, and did `sqlite3 wallabag.sqlite` and the delete command you gave to me.

**Comment by lapineige** [comment] 2016-10-11 11:21
Another info: the database size didn't changed. But when I do a `SELECT * FROM wallabag_tag` (for instance, same for the 2 others) there is no result.
Are my articles coming from a black-hole ?
Maybe it's Re*g*is import fault :laughing:

**Comment by lapineige** [comment] 2016-10-12 18:12
Up :)
Should I try to remove the complete database ? (to test it)

**Comment by lapineige** [comment] 2016-10-16 19:36
ping @tcitworld :)

**Comment by tcitworld** [comment] 2016-10-16 20:05
In `app/config/parameters.yml`, what is the value of `database_driver` ?

**Comment by lapineige** [comment] 2016-10-17 21:23
it's `pdo_mysql`
(also database_path is null)

**Comment by lapineige** [comment] 2016-10-24 14:58
ping @charno6

**Comment by lapineige** [comment] 2016-10-26 16:16
Up :)

Does someone knows how/where my articles are stored ? As cleaning the database change nothing.

**Comment by j0k3r** [comment] 2016-10-27 07:48
If it's `pdo_mysql` it must be saved in the MySQL server defined in `app/config/parameters.yml`.

**Comment by lapineige** [comment] 2016-10-27 08:21
Thanks for you reply.

> If it's pdo_mysql it must be saved in the MySQL server defined in app/config/parameters.yml.

Is there any default path ? Because it's `null` ...
And the name in this config file is wallabag2. I searched the entire disk for it, now way to find it.

edit: maybe I found something: In `/var/lib/mysql/wallabag2/` I have files like `tag.frm` `tag.ibd`, and the same for user, entry, tagging_rule...
Is it the right directory ?
Is so, how can I remove all entries/tags ? By deleting the files ?

**Comment by j0k3r** [comment] 2016-10-27 08:23
What's your parameters.yml?

**Comment by lapineige** [comment] 2016-10-27 08:25
`database_driver: pdo_mysql`
`database_host: 127.0.0.1`
`database_port: 3306`
`database_name: wallabag2`
`database_user: wallabag2`
`database_path: null`
`database_table_prefix: null`

**Comment by j0k3r** [comment] 2016-10-27 08:28
No password? Replace `PASSWORD` with the password

```
mysql -u wallabag2 -p PASSWORD
```

Once connected:

```
use wallabag2;
DELETE FROM entry_tag;
DELETE FROM entry;
DELETE FROM tag;
```

**Comment by lapineige** [comment] 2016-10-27 08:31
> No password? Replace PASSWORD with the password

No I mean, I have one, I didn't included it in the list.

**Comment by j0k3r** [comment] 2016-10-27 08:33
Then replace PASSWORD in the command I wrote and run the query. It should remove all entries and tags.
By the way, you password is safe even if you write it here, we won't access your localhost :wink:

**Comment by nicosomb** [comment] 2016-10-27 08:39
> you password is safe even if you write it here

unless you use it for all your accounts... :)

**Comment by lapineige** [comment] 2016-10-27 08:43
> unless you use it for all your accounts... :) 

ah ah I'm not mad ^^
(and it looks like a randomly generated one)

---

Just to be sure, where should I run your command @j0k3r ? If I try on /data/db/wallabag.sqlite I have access denied, as well as inside of /var/lib/mysql/wallabag2

**Comment by j0k3r** [comment] 2016-10-27 09:23
Run that: `mysql -u wallabag2 -p PASSWORD`
Then you'll have something like `mysql>` and then write all commands I put after ...

**Comment by lapineige** [comment] 2016-10-27 09:28
> Run that: mysql -u wallabag2 -p PASSWORD

Ok I found the issue: it was trying to connect the database PASSWORD.
I had to do use --password=PASSWORD

and... it worked ! Thanks a lot :)
