### ISSUE TITLE
Retriving oauth token won't work after url-prefix PR.

### ISSUE THREAD

**Issue by jpalczewski** [wallabag/wallabag#2214] opened 2016-08-10 16:37 UTC
### Issue details

After applying #2181 wallabag works flawlessly(i.e. adding articles, reading), problem appears when I tried wallabag_api in order to use API - but all runs of sample script were unsuccessful:

```
Starting new HTTPS connection (1): <domain>
Starting new HTTP connection (1): <domain>
Traceback (most recent call last):
  File "demo.py", line 12, in <module>
    token = Wallabag.get_token(host=my_host, **params)
  File "/usr/lib/python2.7/site-packages/wallabag_api/wallabag.py", line 333, in get_token
    return cls.handle_json_response(r)['access_token']
  File "/usr/lib/python2.7/site-packages/wallabag_api/wallabag.py", line 97, in handle_json_response
    for error in json_data['errors']:
KeyError: 'errors'
```

After further investigation and a bit of pythond debugging I discovered, that /oauth/v2/token request returns 302:

```
$ http POST https://$DOMAIN/$PREFIX/wallabag/oauth/v2/token test=test      
HTTP/1.1 302 Found
Cache-Control: private, must-revalidate
Connection: keep-alive
Content-Type: text/html; charset=UTF-8
Date: Wed, 10 Aug 2016 16:07:24 GMT
Location: http://$DOMAIN/$PREFIX/wallabag/login
Server: nginx/1.10.1
Set-Cookie: PHPSESSID=3s7tuqkkmif293ug9o915iige4; path=/; HttpOnly
Strict-Transport-Security: max-age=15768000
Transfer-Encoding: chunked
X-Frame-Options: ALLOW
X-Powered-By: PHP/7.0.9
expires: -1
pragma: no-cache

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="1;url=http://$DOMAIN/$PREFIX/wallabag/login" />

        <title>Redirecting to http://$DOMAIN/$PREFIX/wallabag/login</title>
    </head>
    <body>
        Redirecting to <a href="$DOMAIN$PREFIX/wallabag/login">http://$DOMAIN/$PREFIX/wallabag/login</a>.
    </body>
</html>
```

There's one thing worth pointing out: As you can see in example above, wallabag doesn't like HTTPS so all links generated by him are for http - when I first tried to run "bag it!" bookmarklet(which didn't work for me, either) link in it pointed for http too, despite the fact that session was over HTTPS.  
### Environment
- wallabag version (or git revision) that exhibits the issue: PR #2181 
- How did you install wallabag? Via `git clone` or by downloading the package? Git clone and some bash magic for changing to PR. 
- Last wallabag version that did not exhibit the issue (if applicable): n/a
- php version: 7.0.9
- OS: archlinux
- type of hosting (shared or dedicated): dedicated(I have root access)
- which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MariaDB
### Steps to reproduce/test case
1. Cloning wallabag with pull request mentioned above.
2. My case is bit specific at all, because my wallabag runs as nginx virtual host behind reverse proxy - config which I'm using is available in #2181. 
3. And wallabag script/httpie example can reproduce it. 

Further notes:
Wallabag extension to firefox works and adding new articles is possible, either running oauth url in browser results in:

```
{"error":"invalid_request","error_description":"Invalid grant_type parameter or parameter missing"}
```

so, the problem is possibly with logging procedure at all.

**Comment by j0k3r** [comment] 2016-08-11 07:59
Just a quick question, does it work with latest 2.0.6 and HTTPS?
I mean, we never tested wallabag over HTTPS so maybe the problem is related to HTTPS instead of the base_path PR.

**Comment by Rurik19** [comment] 2016-08-11 08:10
v 2.0.6 works perfect with https, both site and api

**Comment by j0k3r** [comment] 2016-08-11 08:13
Thanks for that @Rurik19.
So maybe @alanpearce should test its PR using HTTPS.

Otherwise we'll have to take a closer look.

**Comment by alanpearce** [comment] 2016-08-11 08:36
HTTPS works fine for me, both through the web interface and the Android application. I will take a look at why that particular route is redirecting incorrectly.

**Comment by jpalczewski** [comment] 2016-08-11 23:25
For the record, I can explain why in my case Firefox extension works:
The reason why is REMEMBERME cookie(result of logging into app?) which is added by Firefox to that request - there's no reason to redirect to login page, so I got token back. So, when I create new Firefox profile and don't log into web application(and paste client id/secret id from another source than Developer tab - and Firefox don't have cookie mentioned above) extension seems to be not responsible, but Fiddler shows the truth: there's 301 to /login from server.

**Comment by alanpearce** [comment] 2016-08-20 16:58
@jpalczewski Did you happen to try with the updates I committed last week?

**Comment by jpalczewski** [comment] 2016-08-20 21:45
@alanpearce big sorry for the delay- today I tried your commit without success - these symptoms(`KeyError` and redirects to login page) aren't fixed by one.

**Comment by Kdecherf** [comment] 2019-01-16 18:08
Hello there, is this issue still relevant?

**Closed** 2020-04-13 13:32 UTC
Labels: API, Awaiting response, Bug
