### ISSUE TITLE
More api/entries filter parameters

### ISSUE THREAD

**Issue by bigretromike** [wallabag/wallabag#2136] opened 2016-06-06 07:54 UTC
It would be great to have ability to filter more pages out before retrieve. Domain_Name would be great for more automated solutions.

Currently this is only thing missing what I used to use with pocket. Long live the wallabag!

**Comment by j0k3r** [comment] 2016-06-06 08:05
Could be a good idea !

**Comment by bigretromike** [comment] 2016-06-14 12:45
currently there is a need to use tools like 'jq' to parse json, extract each domain_name related items, and move to next page to see if there is any left one. Making wallabag just throw only domain_name related entries would be great.

**Comment by nicosomb** [comment] 2016-11-30 09:10
Duplicate of https://github.com/wallabag/wallabag/issues/1313.

**Closed by nicosomb** 2016-11-30 09:10 UTC
Labels: API, Feature
