### ISSUE TITLE
Change links to wallabaged articles

### ISSUE THREAD

**Issue by pmaziere** [wallabag/wallabag#725] opened 2014-06-12 12:27 UTC
Enhancement proposal:
When using the "wallabag this link" button, it would be nice to change the said link in the referring article to the newly wallabaged referred article rather than keeping the original link.

**Comment by pmaziere** [comment] 2015-03-16 14:26
@nicosomb I guess so 
@tcitworld can't see how the issue you talk about is related to this one
(sorry for the very late answer)

**Comment by tcitworld** [comment] 2015-03-16 17:53
I meant, related to.

OK, still feasible, though.

**Comment by nicosomb** [comment] 2017-02-16 17:02
Hello @pmaziere 

It seems to be a duplicate of #671
Feel free to reopen it if I'm wrong.

**Closed by nicosomb** 2017-02-16 17:02 UTC
Labels: Improvement
