### ISSUE TITLE
Failure to fetch article from The New Yorker

### ISSUE THREAD

**Issue by smnthermes** [wallabag/wallabag#4208] opened 2019-12-01 13:22 UTC
### Issue details
wallabag failed to fetch that article: http://www.newyorker.com/magazine/2012/03/26/the-song-machine

However, it doesn't seem to be due to paywall, since the same article saved on archive.today also failed to be fetched: https://archive.is/z79zU 

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.8
* How did you install wallabag? Via `git clone` or by downloading the package? Not applicable: public instance (wallabag.fossdaily.xyz)

**Comment by j0k3r** [comment] 2019-12-04 00:47
Duplicate of #3768

**Closed by j0k3r** 2019-12-04 00:48 UTC
