### ISSUE TITLE
Unable to retrieve article

### ISSUE THREAD

**Issue by rgugliel** [wallabag/wallabag#2211] opened 2016-08-07 19:11 UTC
### Issue details
Cannot retrieve this article:
http://readwrite.com/2013/10/02/github-for-beginners-part-2/

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.5
* How did you install wallabag? git
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 5.6.24-1
* OS: Ubuntu 14.04.4
* type of hosting (shared or dedicated): Dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):

### Steps to reproduce/test case
Try to add the article.
Wallabag then says: "wallabag can't retrieve contents for this article. Please report this issue to us.…"

**Comment by j0k3r** [comment] 2016-08-08 07:18
It seems they have a _bot_ detection, until we found how to properly bypass this human detection, we won't be able to retrieve content :confused: 

```
HTTP/1.1 405 Not Allowed
Server: nginx
Date: Mon, 08 Aug 2016 07:15:46 GMT
Content-Type: text/html
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
Vary: Accept-Encoding
X-User-Agent: standard
X-Cache-Config: 0 0
X-Cache-Status: HIT
X-Distil-CS: HIT
```

**Comment by raf64flo** [comment] 2016-08-15 23:19
Hi, I have similar problem with this URL using v2.0.5: https://ploum.net/216-le-bepo-sur-le-bout-des-doigts/
Few months ago v1.9.2 correctly fetched The article. Don't know if The problem is related to wallabag config or to a change on ploum.net.

**Comment by j0k3r** [comment] 2016-08-17 08:34
@raf64flo could you open a separate issue for that?

For the record, the problem came from ploum.bet, it returns a http 500 instead of 200:

```
HTTP/1.1 500 Internal Server Error
Server: Apache/2.4.18
Link: <https://ploum.net/wp-json/>; rel="https://api.w.org/", <https://ploum.net/?p=232>; rel=shortlink
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Date: Wed, 17 Aug 2016 08:33:44 GMT
Connection: keep-alive
Via: 1.1 varnish
Age: 0
```

**Comment by j0k3r** [comment] 2016-09-28 09:50
Looks like readwriteweb article are fetched now.

![image](https://cloud.githubusercontent.com/assets/62333/18908881/ae3d6822-8571-11e6-867c-82d5fcbafc68.png)

Closing issue.

**Closed by j0k3r** 2016-09-28 09:50 UTC
Labels: Site Config
