### ISSUE TITLE
Question/Feature Request: Save site "as is" and enable reading mode manually if desired

### ISSUE THREAD

**Issue by githtz** [wallabag/wallabag#4067] opened 2019-07-25 12:17 UTC
When I browse the web and I decide to save an article that I'd like to read later, sometimes I'd like to read the article "as is" without the reading mode enabled. Is that currently possible and if not, would it be possible to implement it?

**Comment by j0k3r** [comment] 2019-07-25 15:57
You mean, read the article inside wallabag without the ready mode?
In the view article, we display a link to the original article, should this be enough?

**Comment by githtz** [comment] 2019-07-25 16:02
As long as the original article is available, yes. But since the web is constantly changing and sometimes stuff becomes inaccessible, it would be nice if the original article was persisted, too.

**Comment by j0k3r** [comment] 2019-07-25 16:15
Duplicate of #3715

**Closed by j0k3r** 2019-07-25 16:15 UTC
