### ISSUE TITLE
Suggestion: Sharing to other User(s)

### ISSUE THREAD

**Issue by christianreiss** [wallabag/wallabag#2970] opened 2017-03-09 10:35 UTC
Hello folks,

Wallabag is awesome.
The only thing I am currently missing is the ability to share items between users. We are using it with several friends and at some point I just want to share some subset/ an item with another user. I am aware of the public link, but an internal sharing would be awesome.

As Cpt Picard said: Make it so! :)
Cheers!
-Chris.

**Comment by nicosomb** [comment] 2017-03-09 10:48
Hello @christianreiss ! 

Thank you for your post. 

Your idea is a duplicate of this one https://github.com/wallabag/wallabag/issues/679
Feel free to add your wishes on this issue if it's necessary.

**Closed by nicosomb** 2017-03-09 10:48 UTC
