### ISSUE TITLE
Blank entry found when trying to save a reddit post.

### ISSUE THREAD

**Issue by Romanmir** [wallabag/wallabag#4824] opened 2020-12-12 00:17 UTC
### Issue details
Blank entry found when trying to save a reddit post.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.4.0 docker/sqlite
* How did you install wallabag? docker pull
* Last wallabag version that did not exhibit the issue (if applicable): 2.3.8 on bare metal.
* php version: whatever the docker version has (7.3.25?)
* OS: docker on debian 10
* type of hosting (shared or dedicated): shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

1. Press the "Add link" button
2. Paste in reddit post link (external link or self post, doesn't matter.)
3. Hit "GO"
4. Wait <15 Seconds
5. Note the new card with "No title found" and when clicked you are taken to a blank entry.

prod.log shows a 502 error during the curl to the link submitted. I can re-pro the curl error in the container as well as the host OS. f43 .me testing is unable to reproduce this issue.

**Comment by j0k3r** [comment] 2020-12-14 14:06
Duplicate of #4115

**Closed by j0k3r** 2020-12-14 14:06 UTC
