### ISSUE TITLE
Make command produced errors breaking installation

### ISSUE THREAD

**Issue by gosocial2** [wallabag/wallabag#4734] opened 2020-11-14 20:00 UTC
### Issue details

Installation failed following instructions in README.md

> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
PHP Fatal error:  Cannot redeclare mb_str_split() in /Users/gokhan/Dev181920GOiM/PHPDev1920/wallabag/vendor/wallabag/php-mobi/MOBIClass/RecordFactory.php on line 119
PHP Stack trace:
PHP   1. {main}() /Users/gokhan/Dev181920GOiM/PHPDev1920/wallabag/vendor/sensio/distribution-bundle/Resources/bin/build_bootstrap.php:0
PHP   2. require_once() /Users/gokhan/Dev181920GOiM/PHPDev1920/wallabag/vendor/sensio/distribution-bundle/Resources/bin/build_bootstrap.php:56
PHP   3. require() /Users/gokhan/Dev181920GOiM/PHPDev1920/wallabag/app/autoload.php:9
PHP   4. ComposerAutoloaderInit7bfa7be8e7aa951f0eb82950da9599ca::getLoader() /Users/gokhan/Dev181920GOiM/PHPDev1920/wallabag/vendor/autoload.php:7
PHP   5. composerRequire7bfa7be8e7aa951f0eb82950da9599ca() /Users/gokhan/Dev181920GOiM/PHPDev1920/wallabag/vendor/composer/autoload_real.php:59
PHP   6. require() /Users/gokhan/Dev181920GOiM/PHPDev1920/wallabag/vendor/composer/autoload_real.php:69

Fatal error: Cannot redeclare mb_str_split() in /Users/gokhan/Dev181920GOiM/PHPDev1920/wallabag/vendor/wallabag/php-mobi/MOBIClass/RecordFactory.php on line 119

Call Stack:
    0.0013     401976   1. {main}() /Users/gokhan/Dev181920GOiM/PHPDev1920/wallabag/vendor/sensio/distribution-bundle/Resources/bin/build_bootstrap.php:0
    0.0024     403728   2. require_once('/Users/gokhan/Dev181920GOiM/PHPDev1920/wallabag/app/autoload.php') /Users/gokhan/Dev181920GOiM/PHPDev1920/wallabag/vendor/sensio/distribution-bundle/Resources/bin/build_bootstrap.php:56
    0.0035     404848   3. require('/Users/gokhan/Dev181920GOiM/PHPDev1920/wallabag/vendor/autoload.php') /Users/gokhan/Dev181920GOiM/PHPDev1920/wallabag/app/autoload.php:9
    0.0049     418344   4. ComposerAutoloaderInit7bfa7be8e7aa951f0eb82950da9599ca::getLoader() /Users/gokhan/Dev181920GOiM/PHPDev1920/wallabag/vendor/autoload.php:7
    0.0442    3590808   5. composerRequire7bfa7be8e7aa951f0eb82950da9599ca() /Users/gokhan/Dev181920GOiM/PHPDev1920/wallabag/vendor/composer/autoload_real.php:59
    0.0456    3619256   6. require('/Users/gokhan/Dev181920GOiM/PHPDev1920/wallabag/vendor/wallabag/php-mobi/MOBIClass/MOBI.php') /Users/gokhan/Dev181920GOiM/PHPDev1920/wallabag/vendor/composer/autoload_real.php:69

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap handling the post-cmd event terminated with an exception

                                                         
  [RuntimeException]                                     
  An error occurred when generating the bootstrap file.  
                                                         

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

PHP Fatal error:  Cannot redeclare mb_str_split() in /Users/gokhan/Dev181920GOiM/PHPDev1920/wallabag/vendor/wallabag/php-mobi/MOBIClass/RecordFactory.php on line 119
PHP Stack trace:
PHP   1. {main}() /Users/gokhan/Dev181920GOiM/PHPDev1920/wallabag/bin/console:0
PHP   2. require() /Users/gokhan/Dev181920GOiM/PHPDev1920/wallabag/bin/console:17
PHP   3. require() /Users/gokhan/Dev181920GOiM/PHPDev1920/wallabag/app/autoload.php:9
PHP   4. ComposerAutoloaderInit7bfa7be8e7aa951f0eb82950da9599ca::getLoader() /Users/gokhan/Dev181920GOiM/PHPDev1920/wallabag/vendor/autoload.php:7
PHP   5. composerRequire7bfa7be8e7aa951f0eb82950da9599ca() /Users/gokhan/Dev181920GOiM/PHPDev1920/wallabag/vendor/composer/autoload_real.php:59
PHP   6. require() /Users/gokhan/Dev181920GOiM/PHPDev1920/wallabag/vendor/composer/autoload_real.php:69

Fatal error: Cannot redeclare mb_str_split() in /Users/gokhan/Dev181920GOiM/PHPDev1920/wallabag/vendor/wallabag/php-mobi/MOBIClass/RecordFactory.php on line 119

Call Stack:
    0.0014     398784   1. {main}() /Users/gokhan/Dev181920GOiM/PHPDev1920/wallabag/bin/console:0
    0.0021     400376   2. require('/Users/gokhan/Dev181920GOiM/PHPDev1920/wallabag/app/autoload.php') /Users/gokhan/Dev181920GOiM/PHPDev1920/wallabag/bin/console:17
    0.0022     401496   3. require('/Users/gokhan/Dev181920GOiM/PHPDev1920/wallabag/vendor/autoload.php') /Users/gokhan/Dev181920GOiM/PHPDev1920/wallabag/app/autoload.php:9
    0.0024     415696   4. ComposerAutoloaderInit7bfa7be8e7aa951f0eb82950da9599ca::getLoader() /Users/gokhan/Dev181920GOiM/PHPDev1920/wallabag/vendor/autoload.php:7
    0.0234    3588128   5. composerRequire7bfa7be8e7aa951f0eb82950da9599ca() /Users/gokhan/Dev181920GOiM/PHPDev1920/wallabag/vendor/composer/autoload_real.php:59
    0.0236    3616576   6. require('/Users/gokhan/Dev181920GOiM/PHPDev1920/wallabag/vendor/wallabag/php-mobi/MOBIClass/MOBI.php') /Users/gokhan/Dev181920GOiM/PHPDev1920/wallabag/vendor/composer/autoload_real.php:69

make: *** [install] Error 255

### Environment

* wallabag version (or git revision) that exhibits the issue: 5dc435d
* How did you install wallabag? Via `git clone` or by downloading the package?  git clone https://github.com/wallabag/wallabag.git
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7.4
* OS: macOS 10.13
* type of hosting (shared or dedicated): local machine with specs above (custom vietual host: https://wallabag/ )
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL (PDO)

### Steps to reproduce/test case

As per instructions in README.MD:
git clone https://github.com/wallabag/wallabag.git
cd wallabag && make install

**Comment by j0k3r** [comment] 2020-11-16 11:06
Duplicate of #4271

**Closed by j0k3r** 2020-11-16 11:06 UTC
