### ISSUE TITLE
Feature request: Sort articles in the list

### ISSUE THREAD

**Issue by ngosang** [wallabag/wallabag#3785] opened 2018-11-25 19:37 UTC
Add an option to sort articles in the list.
Now, the articles al always listed by addition date (from newest to older). For me, will be very useful to reverse the order (from older to newest). You can add more sorting options like: reading time (asc, desc), domain (asc, desc)...

The button should be here:
![imagen](https://user-images.githubusercontent.com/10577978/48983622-85f4d600-f0f1-11e8-97c6-7b41d01d190e.png)

**Comment by Kdecherf** [comment] 2018-11-25 20:00
Hello @ngosang,

It seems that your issue duplicates #2178, I'm closing it in favor of the former one.

**Closed by Kdecherf** 2018-11-25 20:00 UTC

**Comment by Kdecherf** [comment] 2018-11-25 20:02
Duplicate of #2178
