### ISSUE TITLE
need to enter username/password at login screen after browser restart

### ISSUE THREAD

**Issue by gunnersson** [wallabag/wallabag#890] opened 2014-10-28 20:37 UTC
current configuration:
Microsoft Windows 7 64bit Professional
Mozilla Firefox 33.0.1 / Waterfox 32.0.3
wallabag 1.2 Firefox add-on
wallabag account at <https://www.framabag.org/>
wallabag username/password for framabag server stored permanently(!) in Firefox/Waterfox

But when I close Firefox/Waterfox (is set to clean cookies, cache, history at browser shutdown - does not touch permanently saved username/password), restart browser and want to open wallabag, I have to enter username/password at login screen.

Other Firefox add-ons offer solutions to this problem...

**Comment by azrdev** [comment] 2015-06-17 11:55
I also suffer from my self-hosted wallabag always requesting my firefox to log in anew. I don't have the password saved in the browser.
wallabag 1.9.0

**Comment by tgrosinger** [comment] 2015-06-17 14:15
Duplicate of #769

**Comment by tcitworld** [comment] 2015-06-17 14:19
The first message is different though. If the user deletes cookies, it's logical he ends up disconnected. In the long term we will have the API and access token should be remembered by the Firefox extension.

The second message and issue #769 are the same, though.

**Comment by nicosomb** [comment] 2015-08-05 19:21
I think this issue can be close, right?

**Comment by modos189** [comment] 2015-08-05 19:23
I can this? =) Then yes

**Closed by modos189** 2015-08-05 19:23 UTC
Labels: Bug
