### ISSUE TITLE
Division by zero warnings in nginx error log

### ISSUE THREAD

**Issue by tmelikoff** [wallabag/wallabag#1880] opened 2016-04-07 12:55 UTC
### Issue details

After importing old wallabag v1.9.1, during navigation between articles, at each click these warnings appear:

```
2016/04/07 14:42:40 [error] 6072#6072: *572 FastCGI sent in stderr: "PHP message: PHP Warning:  Division by zero in /var/www/wallabag/var/cache/prod/twig/1a/1a984f7807246e16405eacdebeb164ac7bfde2e9c1797913ed75b23fc94f3327.php on line 127
PHP message: PHP Warning:  Division by zero in /var/www/wallabag/var/cache/prod/twig/1a/1a984f7807246e16405eacdebeb164ac7bfde2e9c1797913ed75b23fc94f3327.php on line 127
PHP message: PHP Warning:  Division by zero in /var/www/wallabag/var/cache/prod/twig/1a/1a984f7807246e16405eacdebeb164ac7bfde2e9c1797913ed75b23fc94f3327.php on line 127
PHP message: PHP Warning:  Division by zero in /var/www/wallabag/var/cache/prod/twig/1a/1a984f7807246e16405eacdebeb164ac7bfde2e9c1797913ed75b23fc94f3327.php on line 127
PHP message: PHP Warning:  Division by zero in /var/www/wallabag/var/cache/prod/twig/1a/1a984f7807246e16405eacdebeb164ac7bfde2e9c1797913ed75b23fc94f3327.php on line 127
PHP message: PHP Warning:  Division by zero in /var/www/wallabag/var/cache/prod/twig/1a/1a984f7807246e16405eacdebeb164ac7bfde2e9c1797913ed75b23fc94f3327.php on line 127
PHP message: PHP Warning:  Division by zero in /var/www/wallabag/var/cache/prod/twig/1a/1a984f7807246e16405eacdebeb164ac7bfde2e9c1797913ed75b23fc94f3327.php on line 127
PHP message: PHP Warning:  Division by zero in /var/www/wallabag/var/cache/prod/twig/1a/1a984f7807246e16405eacdebeb164ac7bfde2e9c1797913ed75b23fc94f3327.php on line 127
PHP message: PHP Warning:  Division by zero in /var/www/wallabag/var/cache/prod/twig/1a/1a984f7807246e16405eacdebeb164ac7bfde2e9c1797913ed75b23fc94f3327.php on line 127
PHP message: PHP Warning:  Division by zero in /var/www/wallabag/var/cache/prod/twig/1a/1a984f7807246e16405eacdebeb164ac7bfde2e9c1797913ed75b23fc94f3327.php on line 127
PHP message: PHP Warning:  Division by zero in /var/www/wallabag/var/cache/prod/twig/1a/1a984f7807246e16405eacdebeb164ac7bfde2e9c1797913ed75b23fc94f3327.php on line 127
PHP messa
2016/04/07 14:42:49 [error] 6072#6072: *572 FastCGI sent in stderr: "PHP message: PHP Warning:  Division by zero in /var/www/wallabag/var/cache/prod/twig/1a/1a984f7807246e16405eacdebeb164ac7bfde2e9c1797913ed75b23fc94f3327.php on line 127
PHP message: PHP Warning:  Division by zero in /var/www/wallabag/var/cache/prod/twig/1a/1a984f7807246e16405eacdebeb164ac7bfde2e9c1797913ed75b23fc94f3327.php on line 127
PHP message: PHP Warning:  Division by zero in /var/www/wallabag/var/cache/prod/twig/1a/1a984f7807246e16405eacdebeb164ac7bfde2e9c1797913ed75b23fc94f3327.php on line 127
PHP message: PHP Warning:  Division by zero in /var/www/wallabag/var/cache/prod/twig/1a/1a984f7807246e16405eacdebeb164ac7bfde2e9c1797913ed75b23fc94f3327.php on line 127
PHP message: PHP Warning:  Division by zero in /var/www/wallabag/var/cache/prod/twig/1a/1a984f7807246e16405eacdebeb164ac7bfde2e9c1797913ed75b23fc94f3327.php on line 127
PHP message: PHP Warning:  Division by zero in /var/www/wallabag/var/cache/prod/twig/1a/1a984f7807246e16405eacdebeb164ac7bfde2e9c1797913ed75b23fc94f3327.php on line 127
PHP message: PHP Warning:  Division by zero in /var/www/wallabag/var/cache/prod/twig/1a/1a984f7807246e16405eacdebeb164ac7bfde2e9c1797913ed75b23fc94f3327.php on line 127
PHP message: PHP Warning:  Division by zero in /var/www/wallabag/var/cache/prod/twig/1a/1a984f7807246e16405eacdebeb164ac7bfde2e9c1797913ed75b23fc94f3327.php on line 127
PHP message: PHP Warning:  Division by zero in /var/www/wallabag/var/cache/prod/twig/1a/1a984f7807246e16405eacdebeb164ac7bfde2e9c1797913ed75b23fc94f3327.php on line 127
PHP message: PHP Warning:  Division by zero in /var/www/wallabag/var/cache/prod/twig/1a/1a984f7807246e16405eacdebeb164ac7bfde2e9c1797913ed75b23fc94f3327.php on line 127
PHP message: PHP Warning:  Division by zero in /var/www/wallabag/var/cache/prod/twig/1a/1a984f7807246e16405eacdebeb164ac7bfde2e9c1797913ed75b23fc94f3327.php on line 127
PHP messa
```

### Environment

wallabag version (or git revision) that exhibits the issue: wallabag-2.0.0.tar.gz (md5 hash: b61762d28a9b99a64ea4906fd8f93a58)
How did you install wallabag? Via composer create-project or by downloading the package? Downloading the package
Last wallabag version that did not exhibit the issue (if applicable): n/a
php version: PHP 5.6.19-0+deb8u1
OS: Raspbian Jessie
type of hosting (shared or dedicated): dedicated (Raspberry Pi 2)
which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

I've imported my v1 backup and warnings starts to appear in nginx error.log.

As @tcitworld suggested, I've changed read speed to 200, saved, then reverted to 100 and the warnings are gone.

**Comment by nicosomb** [comment] 2016-04-08 11:02
Hello @tmelikoff, 

You said you installed wallabag via the package. I checked, and the package provides good data to use the application (the `Division by zero warning` seems to be due to the `readingSpeed` value). 
Can you reproduce the warning and open the cache file given in the warning to display the line 127 please?

**Comment by tmelikoff** [comment] 2016-04-11 12:42
@nicosomb done, here's line 127
`$context["readingTime"] = ($this->getAttribute($context["entry"], "readingTime", array()) / $this->getAttribute($this->getAttribute($this->getAttribute((isset($context["app"]) ? $context["app"] : null), "user", array()), "config", array()), "readingSpeed", array()));`

**Comment by j0k3r** [comment] 2016-10-02 16:19
This was due to a mis-creating of user's config.
It should be fixed by now.

**Closed by j0k3r** 2016-10-02 16:19 UTC
Labels: Bug
