### ISSUE TITLE
Export/Import automatic tagging rules

### ISSUE THREAD

**Issue by lapineige** [wallabag/wallabag#3408] opened 2017-11-07 21:23 UTC
Right now it's not possible to save or transfer tagging rules.

It can be useful to be able to backup them, and to be able to import/export them, for instance to transfer it to another installation (and maybe to share it to other people ?

If it's not a specific import/export tool/format, it could be a way to copy/paste multiple rules at the same time. You probably now better than me what's the most interesting option :)

Thanks :)

**Comment by tcitworld** [comment] 2019-05-17 12:14
Duplicate of #2284

**Closed by tcitworld** 2019-05-17 12:14 UTC
Labels: Feature
