### ISSUE TITLE
Wallabag 1.9.2 can not export as JSON

### ISSUE THREAD

**Issue by dariottolo** [wallabag/wallabag#2638] opened 2016-11-22 19:14 UTC
### Issue details

I am trying to export my 900 articles from a 1.9.2 version of Wallabag to import them into a newest installation. The JSON is created, but it contains no data.
### Environment

* wallabag version (or git revision) that exhibits the issue: 1.9.2
* How did you install wallabag? Via `git clone` or by downloading the package? downloaded and installed manually
* Last wallabag version that did not exhibit the issue (if applicable): not applicable
* php version: 5.6
* OS: n/a
* type of hosting (shared or dedicated): shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL 5.5

### Steps to reproduce/test case
I log into wallabag (I am the only user), visit the "config" tab and click on the link "JSON export".
Few seconds later I am prompted by the browser to download the file, which is empty.
I found this log:
[22-Nov-2016 19:08:46 UTC] PHP Warning:  rmdir(/srv/data/web/vhosts/www.diludovico.it/htdocs/wallabag/cache/b2/0a): Directory not empty in /srv/data/web/vhosts/www.diludovico.it/htdocs/wallabag/inc/poche/Tools.class.php on line 428

The directory wallabag/cache is full of 2 letters directory, but none of the is created today.

**Comment by tcitworld** [comment] 2016-11-22 20:41
The log line is not related to your issue.

**Comment by dariottolo** [comment] 2016-11-23 00:00
Ok. Maybe I tried to empty the cache too and that caused the error in the log.

Unfortunately I can not see any other errors related to the export (that fails) or wallabag in general.

**Comment by nicosomb** [comment] 2016-11-30 09:26
Duplicate of https://github.com/wallabag/wallabag/issues/1747.

**Closed by nicosomb** 2016-11-30 09:26 UTC
