### ISSUE TITLE
Wrong display in wallabag (wsj.com)

### ISSUE THREAD

**Issue by hightide591** [wallabag/wallabag#6949] opened 2023-09-16 18:59 UTC
**Before submitting the issue, please read:**
If wallabag can't parse / extract content for a given link, please first read the documentation about it:
http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

We have a lot of requests about fetching config issue. It'll help us A LOT if you give a try to fix it on your own following the doc.
If you failed to fix it yourself, tick the following boxes:
- [x] I've tried myself without success
- [x] I've replaced `HOST` in the issue title with the host of the URL that can't be fetched (ie: `nytimes.com`, `20minutes.fr`, `bbc.com`, etc.)

**Content related:**
 - URL: https://www.wsj.com/arts-culture/music/streaming-is-changing-the-sound-of-music-182dc907
 - wallabag version: 2.6.6

**Describe what's wrong:**
Wallabag only displays the first paragraph of the article, same on f43.me

**Comment by hightide591** [comment] 2023-09-16 19:02
I am also getting the same issue with this link: https://www.wsj.com/arts-culture/film/is-marvels-politics-left-or-right-c307e8dc

**Comment by HolgerAusB** [comment] 2023-09-16 19:57
if you are a subscriber of wsj.com you could try to use wallabagger. See #6511

**Comment by hightide591** [comment] 2023-09-16 20:12
> if you are a subscriber of wsj.com you could try to use wallabagger. See #6511

I am having the same issue even when I load the full page on firefox and save with wallabagger.

**Comment by HolgerAusB** [comment] 2023-09-17 04:48
I have no problem with wallabagger while logged-in to wsj.com
- are you a subscriber of wsj.com and logged-in to wsj in Firefox? We have no other way to deal with their paywall at the moment.
- did you activate 'Content fetching from the browser' in the plugin settings of wallabagger, either by domain wsj.com or by default?

**Comment by hightide591** [comment] 2023-09-17 14:53
@HolgerAusB Activating content fetching works. Thank you!

**Comment by HolgerAusB** [comment] 2023-10-03 13:22
@hightide591 would you please close this issue.

**Closed** 2023-10-03 13:24 UTC
Labels: Site Config

**Comment by FahadBinHussain** [comment] 2024-01-07 12:48
The problem is back again @HolgerAusB

**Comment by HolgerAusB** [comment] 2024-01-07 14:41
As this wasn't your issue, you should get more concrete, @FahadBinHussain. Baybe opening a new issue. Which wallabag version, which browser, which article (URL), which problem? Are you a subscriber of WSJ?

I am not a subscriber, so I can only test the teaser and this works for me, both paragraphs are fetched with wallabagger. So we need more input.

@hightide591 what about you? Is WSJ still working for you not?

**Comment by FahadBinHussain** [comment] 2024-01-08 10:52
> As this wasn't your issue, you should get more concrete, @FahadBinHussain. Maybe opening a new issue. Which wallabag version, which browser, which article (URL), which problem? Are you a subscriber of WSJ?
> 
> I am not a subscriber, so I can only test the teaser and this works for me, both paragraphs are fetched with wallabagger. So we need more input.
> 
> @hightide591 what about you? Is WSJ still working for you or not?

https://www.wsj.com/tech/personal-tech/things-to-do-our-12-top-tech-tips-of-2023-ab4e9899

I am not a subscriber. And browser is not related to this problem, I think.

**Comment by HolgerAusB** [comment] 2024-01-08 13:24
@FahadBinHussain The WSJ has a paywall, that wallabag can't lift. So, if you don't have a subscription with WSJ, you only get the first one or two paragraphs.

Using the amp-URL instead has unfortunately not been working for a few months now. WSJ has fixed that weak point.

**Comment by FahadBinHussain** [comment] 2024-01-08 14:33
> @FahadBinHussain The WSJ has a paywall, that wallabag can't lift. So, if you don't have a subscription with WSJ, you only get the first one or two paragraphs.
> 
> Using the amp-URL instead has unfortunately not been working for a few months. WSJ has fixed that weak point.

I know that is already what you said. But what I came here for is if there is a way to go around the paywall, which can be implemented by code in the Wallabag API. The workaround is related to a request named "referrer".

**Comment by HolgerAusB** [comment] 2024-01-08 15:19
If that is not illegal, you should tell us more about the workaround. So we can see, if it is easy to implement. But that should really be a new issue. Because this one is already closed.
