### ISSUE TITLE
Export in PDF: problem with inline images

### ISSUE THREAD

**Issue by rgugliel** [wallabag/wallabag#1627] opened 2016-01-24 13:48 UTC
In the v2, I bag this article: http://jeremykun.com/2013/01/22/depth-and-breadth-first-search/
On the web page, everything is displayed correctly. However, in the exported PDF, inline images are replaced by black rectangles (see attached file, end of page 2).

[Unread articles.pdf](https://github.com/wallabag/wallabag/files/102351/Unread.articles.pdf)

**Comment by tcitworld** [comment] 2016-01-24 14:54
Seems to be linked to pictures generated by wordpress mathjax feature. Maybe they don't like us downloading them. Will do some tries to see if it's something on wallabag's side or on the library we use to produce PDFs.

**Comment by tcitworld** [comment] 2016-01-24 17:58
I have reproduced it without wallabag, so it's an issue with the tcpdf library that we use. The maintainer is not quite active these days, hope he'll see my report.

**Comment by rgugliel** [comment] 2016-01-24 20:53
@tcitworld >> Thanks for the update.

**Comment by j0k3r** [comment] 2016-01-31 13:01
@tcitworld could you link your _report_ here? So it'll be easy to follow it. Thanks :)

**Comment by tcitworld** [comment] 2016-01-31 13:12
It's short, but I had to retype it at least 4 times because Sourceforce is so bad.

https://sourceforge.net/p/tcpdf/bugs/1112/

**Comment by nicosomb** [comment] 2017-02-04 14:38
I close this issue. Feel free to reopen it if necessary.

**Closed by nicosomb** 2017-02-04 14:38 UTC
Labels: Awaiting response, Bug
