### ISSUE TITLE
Unable to install on dedicated host with PostgreSQL

### ISSUE THREAD

**Issue by rmenessec** [wallabag/wallabag#2254] opened 2016-09-01 04:56 UTC
### Issue details

I'm receiving this error when attempting to provide basic configuration details during the Wallabag installation:

```
[Exception]
The command "doctrine:database:create" terminated with an error code: 1.
```
### Environment
- wallabag version (or git revision) that exhibits the issue:
- **How did you install wallabag?** git clone
- **Last wallabag version that did not exhibit the issue (if applicable):** n/a
- **php version:** 7.0.8
- **OS:** Ubuntu 16.04 LTS
- **type of hosting (shared or dedicated):** dedicated
- **which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):** PostgreSQL 
### Steps to reproduce/test case

No special steps. I followed the directions exactly, up to the point that I was asked to answer these questions:

```
Creating the "app/config/parameters.yml" file
Some parameters are missing. Please provide them.
database_driver (pdo_sqlite): pdo_pgsql
database_host (127.0.0.1): 
database_port (null): 
database_name (symfony): [name]
database_user (root): [user]
database_password (null): [password]
database_path ('%kernel.root_dir%/../data/db/wallabag.sqlite'): 
database_table_prefix (wallabag_): 
mailer_transport (smtp): 
mailer_host (127.0.0.1): 
mailer_user (null): 
mailer_password (null): 
locale (en): 
secret ([secret]): 
twofactor_auth (true): 
twofactor_sender (no-reply@wallabag.org): 
fosuser_confirmation (true): 
from_email (no-reply@wallabag.org):
```

I didn't have an MTA available at the time, so I left the mailer_\* fields blank. I don't know what to do about an error code '1'.

The PostgreSQL server is working fine; it also hosts a [Zabbix](http://www.zabbix.com/) database that works perfectly. I created a new user with a random name for Wallabag to use, created a table for it, and gave that user full permissions to access the table. When the installation failed, I tried deleting the table and temporarily giving the Wallabag database user permission to create tables. I re-ran the installation script, and it failed exactly the same way.

I don't know what, if anything, I should have entered for the database_path variable. Unfortunately, I don't know what other information to provide, because error code '1' is not defined in the documentation, and there is no troubleshooting information provided in the documentation, either.

(Or, if there is, I couldn't find it with a search engine and a few minutes. If it does exist and I missed it, apologies in advance - hopefully, you can point me in the right direction.)

Thanks in advance.

**Comment by j0k3r** [comment] 2016-09-01 06:57
The error code "1" just mean the command failed.

Can you define `database_path` to `''` in your parameters.yml, clearing the folder `var/cache/*` and try again?
If it doesn't work, could you manually launch `php bin/console doctrine:database:create --env=prod` and come back with error?

**Comment by vco1** [comment] 2016-09-02 20:15
Since there haven't been a response by the original poster (yet), I'm chiming in. Same issue here with MySQL. Gave up after several attempts, one of them creating the database manually.
Since I removed all Wallabag files from my server I can't reproduce the error I got when running `php bin/console doctrine:database:create --env=prod` but iirc it was something like it was unable to find a class.

**Comment by rmenessec** [comment] 2016-09-02 21:26
@j0k3r , can you be more specific about what under /var/cache you'd like me to remove? Almost the entire contents are completely unrelated to Postgres, PHP, or Wallabag, and about 90% of the subfolders are owned by system packages.

**Comment by rmenessec** [comment] 2016-09-02 21:32
Unfortunately, the results are only slightly different:
```
Step 2 of 5. Setting up database.
Creating database and schema, clearing the cache
The command "doctrine:database:create" terminated with an error code: 1.

                                                                            
  [Exception]                                                               
  The command "doctrine:database:create" terminated with an error code: 1.  
                                                                            

doctrine:database:create [--shard SHARD] [--connection [CONNECTION]] [--if-not-exists] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

**Comment by j0k3r** [comment] 2016-09-03 06:41
@rmenessec can you try the second option I talked about in my previous post please?

**Comment by rmenessec** [comment] 2016-09-03 17:09
@j0k3r , right, sorry. Here's the output:
```
[InvalidArgumentException]
Connection does not contain a 'path' or 'dbname' parameter and cannot be dropped.
```

**Comment by j0k3r** [comment] 2016-09-03 17:16
Could you share your `app/config/parameters.yml`?
Looks like you misconfigured the database connection.

**Comment by rmenessec** [comment] 2016-09-03 17:25
Here you go.

[parameters.txt](https://github.com/wallabag/wallabag/files/453496/parameters.txt)

**Comment by j0k3r** [comment] 2016-09-04 09:56
Setting the port at null won't force PDO to use the socket version. If you want to use the socket it's an other configuration.

I don't see wrong things in your file 😕 
Maybe put `database_path: null` instead of `database_path: ''`

**Comment by vco1** [comment] 2016-09-04 13:22
The following suggestion helped solving the problem for me:

> `database_path` should be set to null for MySQL

After that I had troubles getting the site running with Apache (404 for app.php). So I gave up (again). It's really way too much work to get this up and running (and it's not the first web app I'm installng).

**Comment by j0k3r** [comment] 2016-09-04 13:23
Sorry to hear that 😞 
Did you setup your Apache configuration following the doc http://doc.wallabag.org/en/master/user/installation.html#configuration-on-apache ?

**Comment by vco1** [comment] 2016-09-04 13:34
Yes, I followed the instructions. Also Googled for generic Symfony advice. Either got the directory listing or a 404 for app.php. My configuration is pretty straightforward: simple server with apache and some applications in /var/www/XYZ. Apache config files in etc/sites-available (and enabled obviously). It's the fact that frameworks have different root directories (web, app. what have you) that's causing issues.

Before Wallabag I installed a web application which was build on Laravel. That also gave me issues because it couldn't properly handle a reverse proxy. All these frameworks are probably fine for developers, but not very flexible when you trying to run the application in a different environment.

Will likely try again when I have more patience and time. Wallabag looks interesting and I want to move away from Pocket. ;)

**Comment by j0k3r** [comment] 2016-09-04 13:37
All right. Hope you'll fix your problem with Apache.
Don't hesitate to open an other issue later.
I close this one

**Comment by rmenessec** [comment] 2016-09-04 16:08
@j0k3r , my issue is not fixed. Please reopen.

**Comment by j0k3r** [comment] 2016-09-04 17:06
@rmenessec Don't worry I still get some notifications.
Maybe you can answer my question?

**Comment by rmenessec** [comment] 2016-09-04 18:01
@j0k3r , I managed to get past the database config portion by making the change you suggested - much appreciated - but that still leaves the question of why a connection to the PostgreSQL instance on localhost via the default port didn't work.

PostgreSQL is also configured to allow password and MD5 hash logins on localhost using TCP, and remote connections over TCP using password or MD5 hash. I can use pgAdmin III to administrate the PostgreSQL instance from another machine, so I'm reasonably confident that authentication is set up correctly...

**Comment by foxmask** [comment] 2016-09-05 05:57
I use pg too, i'll post my xonf Later this morning to show you hlw i did.

**Comment by be-neth** [comment] 2016-09-07 16:05
Same issue here.

Symfony cannot connect to my Postgresql database.

- parameters.yml :

parameters:
    database_driver: pdo_pgsql
    database_host: 127.0.0.1
    database_port: 5432
    database_name: [Hidden]
    database_user: [Hidden]
    database_password: [Hidden]
    database_path: null
    database_table_prefix: wallabag_

I can connect without issue using psql and TCP socket using :
(Note the -h 127.0.0.1 to let psql use the TCP connection instead of unix socket)
$ psql -U [Hidden] -W -h 127.0.0.1
Password for user [Hidden]:

psql (9.4.9)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

[Hidden]=>


The command "php bin/console doctrine:database:create --env=prod" Give the following message :
  [InvalidArgumentException]
  Connection does not contain a 'path' or 'dbname' parameter and cannot be dropped.

I have set path to null, and database_name.

**Comment by j0k3r** [comment] 2016-09-07 16:21
This is really strange.
Here is [our config for test in Travis](https://github.com/wallabag/wallabag/blob/master/app/config/tests/parameters_test.pgsql.yml) (if you avoid the `test_` prefix): 

```yaml
parameters:
    test_database_driver: pdo_pgsql
    test_database_host: localhost
    test_database_port:
    test_database_name: wallabag_test
    test_database_user: travis
    test_database_password: ~
    test_database_path: ~
```

**Comment by foxmask** [comment] 2016-09-07 18:01
Is there on your Ubuntu a system like on redhat called "SELinux" ?
Often this one block network connection even locally ...
it's a real pain

**Comment by rmenessec** [comment] 2016-09-07 18:23
@foxmask [Sort of](https://help.ubuntu.com/community/AppArmor).

I didn't note any errors logged regarding AppArmor during the installation issue, though.

If Wallabag or any of its components do require one or more AppArmor profiles, though, I'd appreciate it if you'd share those. I'm about to start working on setting up the Apache httpd vhost - the localhost-only test with PHP's inbuilt web server seemed to work fine - and I'd appreciate a heads-up if I'm about to run into more issues.

**Comment by rmenessec** [comment] 2016-09-07 18:26
@be-neth , I'm wondering if there's a problem with the PDO PostgreSQL driver not supporting encryption properly. I have the PostgreSQL connector set up to use TLSv1.2 and ECDHE-RSA-AES256-GCM-SHA384, same as you. ;)

**Comment by rmenessec** [comment] 2016-09-07 19:07
@foxmask , There's no reason to disable AppArmor. If the AA module were denying operations, I'd see warnings logged in **/var/log/syslog**, **/var/log/dmesg**, and/or **/var/log/kern.log**. I've seen no AppArmor output so far.

The default configuration for AppArmor in Ubuntu is much the same as SELinux in, say, Fedora or Red Hat; all attempted operations that were blocked by the security module get logged so that you can see what's causing the problem.

I appreciate the suggestion, though.

**Comment by foxmask** [comment] 2016-09-07 19:18
psql -U user db -h 127.0.0.1 -p 5433
psql (9.4.9)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

I restarted the postgresql server with ssl option and updated to 2.0.8 just right now and still dont have issue :/

**Comment by be-neth** [comment] 2016-09-08 08:23
> @be-neth , I'm wondering if there's a problem with the PDO PostgreSQL driver not supporting encryption properly. I have the PostgreSQL connector set up to use TLSv1.2 and ECDHE-RSA-AES256-GCM-SHA384, same as you. ;)

@rmenessec I have another web application that use the PHP pdo_pgsql without any problem. So I don't think the issue is in the connector.

**Comment by rmenessec** [comment] 2016-09-13 00:39
@be-neth Sorry, sloppy phrasing on my part. I was referring to the PDO configuration; not the driver itself as installed on my server. As I mentioned, I also have Zabbix' DB backend running on the same PostgreSQL instance where I've been trying to get Wallabag working.

The PostgreSQL instance worked fine for Zabbix from the off. No special configuration necessary.

**Comment by j0k3r** [comment] 2019-06-05 12:08
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Closed by j0k3r** 2019-06-05 12:08 UTC
Labels: Bug
