### ISSUE TITLE
Import fails with white screen

### ISSUE THREAD

**Issue by funkenstrahlen** [wallabag/wallabag#1405] opened 2015-08-27 06:58 UTC
I installed a fresh wallabag 1.9.1. I then uploaded my Pocket export with about 800 entries by using the import functionality.

At first it looked fine. It started to import the links and refreshed the progress itself. Then suddenly the page went white and nothing happend any more. Reloading the page required me to login again.

There were a lot of links shown with "Click to continue import". Each time I click on any of them the page gets white again and I have to relad + relogin. The import does not work any more.

Any help? How can I debug?

**Comment by jessaimaya** [comment] 2015-09-26 23:45
Exactly the same here.

**Comment by bertbalcaen** [comment] 2015-09-27 22:12
Same thing for me. Was importing from Instapaper. Culprit for me was a Facebook entry. It just deleted it from the db, so no further details on the root cause. The rest of my 700+ entries imported did import without issues.

Fixed it with some caveman debugging: added a var_dump($entries) in the retrieveUnfetchedEntries() function inc/poche/Database.class.php, around line 307. The first element in the array should be the one causing trouble.

**Comment by gdm85** [comment] 2016-01-02 08:47
I think this is a duplicate of #1213

**Comment by tcitworld** [comment] 2016-01-02 09:42
I don't think so. #1213 was an issue with import page not refreshing. Here we have issues when an URL fails to grab content for some reason.

**Comment by gdm85** [comment] 2016-01-03 12:26
@tcitworld yes, sorry that issue is unrelated. I am also experiencing many "Click here to import" saved URLs (actually more than half of the ~600 I imported from pinboard with a Netscape export).

However, the main issue I have is that I cannot really help troubleshooting as I couldn't individuate where logs are saved (if any).

1. does wallabag have a log file? I was expecting to find some output in php5-fpm.log but nothing is going there, even when toggling catch workers output in `www.conf`
2. is it possible to enable some debug output since there are still some bugs around?

I haven't yet looked at 2.0, if you think it's better to work on that one instead - please say so

**Comment by j0k3r** [comment] 2016-01-03 12:45
@gdm85 It's better to look at the v2 since I don't know if it'll have an other v1.9.x version. Also, import isn't yet ready on v2 (see #1493).

**Comment by nicosomb** [comment] 2016-01-24 09:19
This issue affects wallabag v1. This version won't move anymore.

**Closed by nicosomb** 2016-01-24 09:19 UTC
Labels: Bug
