### ISSUE TITLE
Sending emails using Gmail fails with error: Connection could not be established with host smtp.gmail.com [Operation timed out #110] [] []

### ISSUE THREAD

**Issue by cmonty14** [wallabag/wallabag#3752] opened 2018-10-17 13:47 UTC
### Issue details

I have configured Gmail smtp settings in _app/config/parameters.yml_:
````
...
    mailer_transport: gmail
    mailer_host: smtp.gmail.com:587
    mailer_user: <gmail-user-account>
    mailer_password: <gmail-app-passwd>
...
````
However I don't receive any email from wallabag, e.g. for 2-Factor-Authentication.

In the logfile _var/logs/prod.log_ I find this relevant entry:
````
[2018-10-17 13:18:40] app.ERROR: Exception occurred while flushing email queue: Connection could not be established with host smtp.gmail.com [Operation timed out #110] [] []
````

To start troubleshooting this issue I have verified if the Gmail account is working, mean I installed SSMTP on the same server and sent an email with this simple command:
`ssmtp <user@example.com> < /tmp/mail.txt`

This worked w/o issues and confirmed the correct Gmail user name and password.

### Environment

* wallabag version (or git revision) that exhibits the issue:
latest git
* How did you install wallabag? Via `git clone` or by downloading the package?
git
* php version:
7.2.11
* OS:
Alpine Linux 3.8
* type of hosting (shared or dedicated):
dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):
MariaDB

### Steps to reproduce/test case

1. Activate 2-Factor-Authentication for user account
2. Try to login with this user account

**Question:**
How can I validate if wallabag can send emails with the used configuration?
Is there a CLI command for sending emails?

THX

**Comment by j0k3r** [comment] 2018-10-17 14:48
You can't validate if wallabag configuration for email is ok and there is no command to send email.
You don't seems to be the only one with that kind of problem: https://www.google.fr/search?q=swiftmailer+%22Connection+could+not+be+established+with+host+smtp.gmail.com%22

I'm closing this issue as the error is not related to wallabag.

**Comment by 74cmonty** [comment] 2018-10-17 14:59
I don't like the way you handle this issue.
With wallabag you're using some functionality from Swiftmail for sending emails.
Your statement is that this is not related to wallabag, however it is.
I mean if you use a functionality that is not working, than you should either collaborate with the provider of this functionality to fix it or replace it with something that is working.

**Comment by Kdecherf** [comment] 2018-10-17 15:08
@74cmonty do you have any SELinux enabled? Did you set the tls security mode for the port 587?

**Comment by 74cmonty** [comment] 2018-10-17 15:29
THIS is the correct question to ask.
To answer it: No, I don't have any SELinux policy.

But I also did not set TLS for port 587 (which I did for SSMTP).

How can I do this?

**Comment by j0k3r** [comment] 2018-10-17 15:56
Actually you can't.
It'll be available in the 2.4.0: https://github.com/wallabag/wallabag/blob/2.4/app/config/parameters.yml.dist#L34

But, you can edit `app/config/config.yml` and add this line with the correct port: https://github.com/wallabag/wallabag/blob/2.4/app/config/config.yml#L86

**Comment by Kdecherf** [comment] 2018-10-17 16:30
Could you try to replace `mailer_host` with `smtp.gmail.com` and add `mailer_port: 587`?

Also, don't forget to clear the cache after changing these files.

**Comment by 74cmonty** [comment] 2018-10-17 16:46
OK.
I found the root cause.

With the settings
````
    mailer_transport: gmail
    mailer_host: smtp.gmail.com:587
    mailer_encryption: tls
    mailer_auth_mode: login
    mailer_user: <gmail-user-account>
    mailer_password: <gmail-app-passwd>
````
communication to Gmail (smtp.gmail.com) is **on port 465**.

Please check this tcpdump output:
````
ct121-wallabag:~# tcpdump -i eth0 port 465
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
18:43:56.063959 IP ct121-wallabag.<mydoman>.lan.51802 > 108.177.127.108.465: Flags [S], seq 4183255243, win 29200, options [mss 1460,sackOK,TS val 4032416351 ecr 0,nop,wscale 7], length 0
18:43:57.082174 IP ct121-wallabag.<mydoman>.lan.51802 > 108.177.127.108.465: Flags [S], seq 4183255243, win 29200, options [mss 1460,sackOK,TS val 4032417370 ecr 0,nop,wscale 7], length 0
18:43:59.098179 IP ct121-wallabag.<mydoman>.lan.51802 > 108.177.127.108.465: Flags [S], seq 4183255243, win 29200, options [mss 1460,sackOK,TS val 4032419386 ecr 0,nop,wscale 7], length 0
18:44:03.162174 IP ct121-wallabag.<mydoman>.lan.51802 > 108.177.127.108.465: Flags [S], seq 4183255243, win 29200, options [mss 1460,sackOK,TS val 4032423450 ecr 0,nop,wscale 7], length 0
18:44:11.354172 IP ct121-wallabag.<mydoman>.lan.51802 > 108.177.127.108.465: Flags [S], seq 4183255243, win 29200, options [mss 1460,sackOK,TS val 4032431642 ecr 0,nop,wscale 7], length 0
````

There's no communication on the expected port 587.
And my wallabag server is located in DMZ where only selected ports are open, this means 465 is closed by firewall settings.

**Comment by 74cmonty** [comment] 2018-10-17 16:57
Update:
After modifying the settings to
````
    mailer_transport: gmail
    mailer_host: smtp.gmail.com
    mailer_port: 587
    mailer_encryption: tls
    mailer_auth_mode: login
    mailer_user: <gmail-user-account>
    mailer_password: <gmail-app-passwd>
````
the communication is still on port 465.

This indicates a hardcoded smtp default communication on port 465.

**Comment by 74cmonty** [comment] 2018-10-17 16:59
@j0k3r 
Please reopen this issue.

As the root cause is now identified it should be easier to provide a fix.

**Comment by Kdecherf** [comment] 2018-10-17 17:04
Did you edit the definition of swiftmailer in `config.yml`? 'cause, there's no support in our current stable version (and it won't be fixed in the 2.3 branch).

**Comment by 74cmonty** [comment] 2018-10-17 17:08
No, I didn't.
But I feas Swiftmailer is only supporting port 25 and 465.
Check this [docu](https://symfony.com/doc/current/reference/configuration/swiftmailer.html).
````
port¶
type: string default: 25 or 465 (depending on encryption)

The port when using smtp as the transport. This defaults to 465 if encryption is ssl and 25 otherwise.
````

**Comment by Kdecherf** [comment] 2018-10-17 17:10
This only says that without specifying `port` it will use value 25 or 465 regarding on the value of `encryption`.

**Comment by Kdecherf** [comment] 2018-10-17 17:11
Anyway you must edit the file `config.yml` is your case until the release of the branch 2.4.

**Comment by j0k3r** [comment] 2018-10-17 18:28
Regarding the Symfony doc: https://symfony.com/doc/3.3/email/gmail.html
You should define:

```yaml
#app/config/parameters.yml
parameters:
    mailer_transport: gmail
    mailer_user: user@gmail.com
    mailer_password: gmail-password # or app password if you use 2-Step-Verification
```

- are you using 2step verification on your gmail account?
- what does `telnet smtp.gmail.com 465` says? (port 25 is dead from my machine for example)
- are you 100% port 25/465/587 are open?

**Comment by Kdecherf** [comment] 2018-10-17 20:40
There's an easier way of checking connectivity to a given port:

`nc -vz -w1 {host} {port}`

In our case: `nc -vz -w1 smtp.gmail.com 587`

As a side note, port 465 is for SMTP over SSL and port 587 is for SMTP with STARTTLS.

**Comment by 74cmonty** [comment] 2018-10-17 23:18
Let me share again the findings:
1. My server is located in DMZ
2. Firewall rules restrict communication over port 587 only, port 465 is closed
3. This is working w/o issues using SMTP client SSMTP, means I can send emails using the same Gmail account with command `sendmail`

So, for this setup there can be two solutions:
a) someone shares a working configuration for SwiftMailer using Gmail over STARTTLS (port 587)
b) I use the working SMTP client installed on this server for sending emails from wallabag

Of course I could modify DMZ rules and open port 465, but this is not a solution for this issue; this would be a workaround only.

I didn't expect that wallabag is restricted to email communication over port 25 / 465 only.

**Comment by nicosomb** [comment] 2023-08-02 07:51
Hello @cmonty14 

As we don't use Swiftmailer anymore, I close this issue. 
If you still have an issue with email configuration with last wallabag release, feel free to open a new issue.

**Closed by nicosomb** 2023-08-02 07:51 UTC
