### ISSUE TITLE
Import from Pocket duplicates entries

### ISSUE THREAD

**Issue by Suncatcher** [wallabag/wallabag#2407] opened 2016-10-09 13:09 UTC
### Issue details

Wallabag duplicates imported entries after error (#2408) when I try to import articles from Pocket

### Environment

* wallabag version: 2.1.1
* Install type: via `git clone`
* Last wallabag version that did not exhibit the issue (if applicable): none
* php version: 5.6.26
* OS: Amazon Linux
* type of hosting: dedicated AWS EC2
* which storage system you choose at install: SQLite

### Steps to reproduce/test case

I am trying to import via "Migrate from Pocket" located on Quick Start page. Pocket consumer key is valid and has "Retrieve" permission.
First time it failed to import **any** and threw this error, the second time it imported 420 items out of 500 and again threw the error, the third time it duplicated 100+ entries and threw the error again.

Original Pocket item count: 500
Current Wallabag item count: 620
Host at issue: http://52.57.95.146/ (default credentials)

**Comment by j0k3r** [comment] 2016-10-09 13:31
This is weird.
Thanks for reporting, we'll take a closer look.

**Comment by j0k3r** [comment] 2016-10-19 21:22
Closing as duplicate of https://github.com/wallabag/wallabag/issues/2232 (I've put a comment on the other one to explain the issue).
Thanks for reporting btw!

**Closed by j0k3r** 2016-10-19 21:22 UTC
Labels: Bug
