### ISSUE TITLE
Send content to wallabag, instead of URL

### ISSUE THREAD

**Issue by biva** [wallabag/wallabag#2228] opened 2016-08-22 13:20 UTC
### Issue details

If I want to "bag" a page, whose URL is not specific, but related to what I loaded before, I can't do it. 

For example after an online check-in process for a flight, the URL will not be specific (e.g.: https://checkin.brusselsairlines.com/CI/WebForms/Confirmation.aspx). If I try to "bag" it, the page will not be stored with my information, but with an error page. I would like to be able to "bag" the page I see (with my seat number, the QR-code, the flight schedule, ...).

Is it possible to send the content of the HTML page to wallabag, instead of the URL? Could we use a specific bookmarklet for this? And/or the browser extension?

**Comment by tcitworld** [comment] 2016-08-22 13:22
Duplicate of https://github.com/wallabag/wallabag/issues/1634.

**Closed by tcitworld** 2016-08-22 13:22 UTC
