### ISSUE TITLE
Error 500 with importing from Wallabag v1

### ISSUE THREAD

**Issue by ddeimeke** [wallabag/wallabag#1860] opened 2016-04-05 13:23 UTC
### Issue details

Please provide issue details here.
Remember, this is _not_ a place to ask questions. For that, go to http://gitter.im/wallabag/wallabag.

### Environment

* wallabag version (or git revision) that exhibits the issue: v2 (2.0.0)
* How did you install wallabag? Via `composer create-project` or by downloading the package? git clone, php bin/console wallabag:install --env=prod
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 5.6.20
* OS: CentOS 7.2.1511, recent patch level
* type of hosting (shared or dedicated): decicated server
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case

Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies, if possible).

Export from Wallabag 1.9.1 fails to be imported into Wallabag 2.0.0, nothing found in the Apache error.log

**Comment by nicosomb** [comment] 2016-04-05 13:27
Duplicate of #1764 
Can you have a look to this https://github.com/wallabag/wallabag/issues/1764#issuecomment-205765377 please?

**Closed by nicosomb** 2016-04-05 13:27 UTC
