### ISSUE TITLE
Sync read position between clients

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#1336] opened 2015-08-12 19:55 UTC

**Comment by j0k3r** [comment] 2015-08-12 19:58
You mean read position inside a content ?

**Comment by tcitworld** [comment] 2015-08-12 20:00
Yup. Like the current *default* theme does, return to the position in the text where you left.

**Comment by nicosomb** [comment] 2015-08-12 20:01
baggy does also does it. 
But here, the feature is to sync between web app and smartphone app.

**Comment by nicosomb** [comment] 2015-08-12 20:01
https://twitter.com/h1ro/status/631551090840993793

**Comment by j0k3r** [comment] 2015-08-12 20:02
Baggy does that? hu

**Comment by nicosomb** [comment] 2015-08-12 20:03
yes! open an article, scroll down, go to unread and return to your article \o/

**Comment by tcitworld** [comment] 2015-08-12 20:06
> Baggy does that? hu

It's here : https://github.com/wallabag/wallabag/blob/master/themes/_global/js/restoreScroll.js

**Comment by j0k3r** [comment] 2015-08-12 20:09
Oh localStorage, I see.

**Comment by nicosomb** [comment] 2016-11-30 08:42
Duplicate of https://github.com/wallabag/wallabag/issues/2643 
Opened PR: https://github.com/wallabag/wallabag/pull/2644

**Closed by nicosomb** 2016-11-30 08:42 UTC
Labels: Feature
