### ISSUE TITLE
fails to fetch articles from 

### ISSUE THREAD

**Issue by MyMyrtle** [wallabag/wallabag#4551] opened 2020-09-01 13:23 UTC
### Environment

* wallabag version (or git revision) that exhibits the issue: Couldnt find in your web. Sorry. What about putting the number next to your logo :-)
* How did you install wallabag? You are hosting
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:
* OS: 
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):

### Steps to reproduce/test case

Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies, if possible).

Try fetchin any article in [elperiodicodelaenergia.com](https://elperiodicodelaenergia.com/endesa-se-adjudica-el-suministro-de-gas-natural-para-el-parque-movil-del-estado/)

**Comment by j0k3r** [comment] 2021-02-01 13:16
Cloudflare issue

Duplicate of #1399

**Closed by j0k3r** 2021-02-01 13:16 UTC
Labels: Site Config
