### ISSUE TITLE
How export all links 

### ISSUE THREAD

**Issue by Iriamu19** [wallabag/wallabag#3935] opened 2019-04-22 08:52 UTC
Hi,

I would like to know if it's possible to export/save all the links of Wallabag ? Just links, not the content.

**Comment by j0k3r** [comment] 2019-04-23 08:58
No you can't.
But you can export all the contents (which includes link) and then remove the extra data from the export to only keep links.

**Comment by j0k3r** [comment] 2019-06-05 10:04
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Closed by j0k3r** 2019-06-05 10:04 UTC
Labels: Awaiting response

**Comment by Iriamu19** [comment] 2019-06-05 16:57
OK, thanks for the answer

**Comment by kn-f** [comment] 2022-02-12 13:58
If you're selfhosting actually you can do it with a simple SQL statement:
`SELECT url FROM wallabag_entry`
Of course you'll have to be connected to the wallabag DBMS (be it sqlite, MySQL or whatever you're using)
There're also other fields taht hold the URL but I'm not sure that they're for:
- origin_url
- given_url

**Comment by crh0831** [comment] 2022-02-22 15:04
You can use [jq](https://stedolan.github.io/jq/)

Export articles from Wallabag as json, then use the following to pull the title and URL from each article

```shell
cat <exported-file>.json | jq -r '.[] | {title, url} | join("    ")'
```

Export Example:

```text
The curious case of the Raspberry Pi in the network closet    https://blog.haschek.at/2018/the-curious-case-of-the-RasPi-in-our-network.html
Eric’s Scratch Monkey Story    https://edp.org/monkey.htm
Vim Creep    https://rudism.com/vim-creep/
```

**Comment by phpmoli** [comment] 2026-09-02 02:40
I would like to export all my links from a self-hosted instance, which i do **not have linux access to**. What are my options?

**Comment by j0k3r** [comment] 2026-09-02 04:46
You need to enable exports in internal settings: `/settings#set-export`
Then the export button will appear.

**Comment by phpmoli** [comment] 2026-09-02 05:55
> You need to enable exports in internal settings: `/settings#set-export` Then the export button will appear.

Since i do not own the server, it replies:

> Oops! An Error Occurred
> The server returned a "403 Forbidden".
> Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused. 

But, i found the export button, it is disguised as the generic download icon. Thanks!
Is there any way to export all my data, and not just _unread_ articles?

**Comment by chawl3y** [comment] 2026-09-02 13:37
Under the main menu on the left (Unread, Starred, Archive...etc), select "All Entries", then do your export. 
Keep the export in .json format if you want to be able to restore that file back into Wallbag.

**Comment by phpmoli** [comment] 2026-09-03 08:10
Wow, never would have thought that. OK, not never, but maybe only after thinking about it and sleeping on it for a month. Thank you!
The .json thing is great info too, would have only known about it, when it is too late, and i would have to write an xml2json converter.

Is there a way to omit the article body/content? My export is 21 MB

**Comment by chawl3y** [comment] 2026-09-03 12:20
I don't think so, but you could do it after the export with `jq`:

```bash
cat All\ articles.json | jq 'map(del(.content))' > All\ articles\ No\ Content.json
```

Would filter out the content field (making the resulting `.json` smaller

**Comment by phpmoli** [comment] 2026-09-03 13:09
The problem is the wasted internet traffic of a gratis server, i am only a tolerated freeloader on. It would save 88.4% of the traffic.
Edit: Forgot about compression, it would save 92.6%
