### ISSUE TITLE
Feature request: add ability to share articles between users

### ISSUE THREAD

**Issue by jamietanna** [wallabag/wallabag#3111] opened 2017-05-12 12:01 UTC
If would be useful to be able to either specify tags that can be shared between users / everyone on the installation, or at least having the ability to share directly to another user

**Comment by nicosomb** [comment] 2017-05-12 12:48
Hello @jamietanna ! 

Thank you for your idea. Your issue is a duplicate of https://github.com/wallabag/wallabag/issues/679 ;-) .

Have a nice day.

**Closed by nicosomb** 2017-05-12 12:48 UTC
