### ISSUE TITLE
Error when trying to save and now I can't even view articles.

### ISSUE THREAD

**Issue by mathwhiz1212** [wallabag/wallabag#1138] opened 2015-02-25 18:02 UTC
I get this error: 
Fatal error: Call to a member function fetchAll() on a non-object in /var/www/wallabag/inc/poche/Database.class.php on line 190

**Comment by tcitworld** [comment] 2015-02-25 20:31
Duplicate of  #1121.

**Closed by tcitworld** 2015-02-25 20:31 UTC

**Comment by mathwhiz1212** [comment] 2015-02-25 21:51
So... How do I fix this and is there any way to retrieve my data if there isn't a way to fix this.
Using MySQL

**Comment by tcitworld** [comment] 2015-02-25 21:52
I didn't start yet to try and reproduce the problem, I'm not available at the moment. But I will find the problem, promise. :)

**Comment by mathwhiz1212** [comment] 2015-02-25 21:53
Ok, I just realised how dependent on this I am :) and Thank you for you help.

**Comment by tcitworld** [comment] 2015-02-25 21:54
You can use SQLite for now if you really need it. Or use Framabag. ;)

**Comment by mathwhiz1212** [comment] 2015-02-25 22:20
Mainly I'm concerned that I might have done something that would make my files irrecoverable.

**Comment by tcitworld** [comment] 2015-02-25 22:21
You can always access content via phpMyAdmin.

**Comment by mathwhiz1212** [comment] 2015-02-27 04:37
btw my setup is Wallabag v.1.9, PHP 5.4.36, mysql Ver 14.14 running on a raspberry pi with raspbian.

**Comment by tcitworld** [comment] 2015-03-01 19:43
Your MySQL version is quite... unusual. :p

**Comment by tcitworld** [comment] 2015-03-01 19:45
It's the *Distrib* information we'll need. ;)
