### ISSUE TITLE
Repeat Icons for starring, marking read and deleting at the end of the article

### ISSUE THREAD

**Issue by ddeimeke** [wallabag/wallabag#1986] opened 2016-04-26 08:16 UTC
If you read a long article on a Tablet in "Portrait mode", you have to scroll back to the very beginning of the article to mark it as starred, read or deleted.

It would be great to have the menu you find at the top of the page as well at the bottom.

Please consider this very low prioritized.

**Comment by nicosomb** [comment] 2016-04-26 09:20
Low prioritized, but easy bug.

**Comment by nicosomb** [comment] 2016-11-30 08:58
Duplicate of https://github.com/wallabag/wallabag/issues/1986

**Comment by nicosomb** [comment] 2016-11-30 08:58
Duplicate of https://github.com/wallabag/wallabag/issues/2647

**Closed by nicosomb** 2016-11-30 08:58 UTC
Labels: Easy bug, Improvement
