### ISSUE TITLE
[V2] - Error on deleting an item alpha in 2.0.0-alpha

### ISSUE THREAD

**Issue by bibi99** [wallabag/wallabag#1531] opened 2015-12-10 09:46 UTC
I've been testing deleting an article on http://v2.wallabag.org from the article page 
I got an error message but the article is deleted when I return on home page.

Version: 2.0.0-alpha
--
Oops! An Error Occurred
The server returned a "404 Not Found".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by nicosomb** [comment] 2015-12-10 12:12
Hello @bibi99! Thank you for this issue. It seems to be a duplicate of #1512. I close, if it's necessary, you can reopen.

**Closed by nicosomb** 2015-12-10 12:12 UTC
