### ISSUE TITLE
Ability to share a link that includes my highlights/annotations?

### ISSUE THREAD

**Issue by ReessKennedy** [wallabag/wallabag#5219] opened 2021-04-14 20:43 UTC
Issue: 
I love being able to share a story from my own domain hosting Wallabag but I also want to be able to share my highlights from an article. 

Solution: 
* I Couldn't find discussion about this online. Did I miss something? Surely others want this too. 
* Instapaper doesn't allow this either, I don't think, and it's been a pain point for me
* Being that Wallabag is open source I figured that if it doesn't exist here and no one has worked on it, maybe I could work with someone on this

**Comment by lapineige** [comment] 2021-08-16 08:58
I would be interested too 🙂

**Comment by rocky-III** [comment] 2021-11-07 07:50
any news about this feature?

**Comment by Kdecherf** [comment] 2021-11-07 12:50
@rocky-III there's no work in progress on this issue

**Comment by Kdecherf** [comment] 2022-06-10 20:33
Duplicate of #4907

**Closed by Kdecherf** 2022-06-10 20:33 UTC
Labels: Feature
