### ISSUE TITLE
Wrong display in wallabag

### ISSUE THREAD

**Issue by j0k3r** [wallabag/wallabag#3933] opened 2019-04-19 17:36 UTC
*Sent by Florian Gerdes and automatically created by email*

---

www.dialogpur.com/2019/04/17/avm-fritzwlan-repeater-1750e-im-ausseneinsatz/

Pictures ar missing

Greetings,
Florian

**Comment by Kdecherf** [comment] 2019-05-01 14:31
Duplicate of #3889

Closing this issue as upcoming PR #3943 and its dependencies fix it.

**Closed by Kdecherf** 2019-05-01 14:31 UTC
Labels: Site Config
