### ISSUE TITLE
Composer hangs on "updating dependencies"

### ISSUE THREAD

**Issue by giovi321** [wallabag/wallabag#1885] opened 2016-04-08 12:50 UTC
### Issue details

Composer hangs on "Updating dependencies" after the following command:
SYMFONY_ENV=prod ./composer.phar install --no-dev -o --prefer-dist

If I use the command 
root@GC04SRVR /var/www/wallabag # SYMFONY_ENV=prod **composer **install --no-dev -o --prefer-dist
I just get an error message of command not found.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0
* How did you install wallabag? Via `git clone`
* php version: PHP 5.4.45-0+deb7u2 
* OS: Debian 8
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): mysql

### Steps to reproduce/test case

root@SERVER /var/www/wallabag # SYMFONY_ENV=prod ./composer.phar install --no-dev -o --prefer-dist
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
Loading composer repositories with package information
Updating dependencies

**Comment by tcitworld** [comment] 2016-04-08 12:59
composer can really take a while to finish, how long did you consider ? Also, it uses a lot of memory. If you keep having issues with it, you can try downloading the package for shared hosting, but you'll need extra configuration if you need to use something else than SQLite.

**Comment by nicosomb** [comment] 2016-04-08 13:48
You will have a problem with your PHP version: you need PHP > 5.5.9.

**Comment by j0k3r** [comment] 2016-04-08 20:09
Kind of duplicate of https://github.com/wallabag/wallabag/issues/1883

**Closed by j0k3r** 2016-04-08 20:09 UTC
