### ISSUE TITLE
Capacity to add tags via entries view

### ISSUE THREAD

**Issue by klorydryk** [wallabag/wallabag#2246] opened 2016-08-26 19:32 UTC
On Wallabag v2.0.7, we need to open an article to categorise it with tags. It should be great to be able to do it (a list of existing tags should be enough, or the current text line actually used ?) directly via the entry view.

Indeed, if I want to categorise a lot of articles (known to be "tech", for example), for now I need to open each of them consecutively, even though I dont want to read them.

Improvement of #2166 ?

**Comment by tcitworld** [comment] 2016-08-28 09:33
You mean select all the articles you want to tag (for instance with check boxes) and then select the tag. Right.

**Comment by lapineige** [comment] 2016-08-28 16:37
> You mean select all the articles you want to tag (for instance with check boxes) and then select the tag. 
That would be a great addition
But also tagging from the overview (and having a view of the tags) would be useful - it's faster than opening the article, tagging, coming back.
It might also be useful to see if we tagged an article or not.

**Comment by klorydryk** [comment] 2016-09-07 20:15
I was not necessarily thinking about selecting multiple articles at one time (but good idea ! :) ). At least avoiding open each article to tag should be enough !

**Comment by nicosomb** [comment] 2016-09-08 06:49
So, is this issue a duplicate of #1109?

**Comment by nicosomb** [comment] 2017-05-02 10:01
Duplicate of #1109.

**Closed by nicosomb** 2017-05-02 10:01 UTC
Labels: Feature

**Comment by jpbaril** [comment] 2018-07-27 04:18
That was a duplicate but the other issue was closed so we need at least one of the two to stay open.
