### ISSUE TITLE
bulk action

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#3528] opened 2017-12-23 22:08 UTC
### Issue details

now that we have to confirm each deletion, it becomes hard to delete 100 articles one by one :(

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3

### Feature request:

possibility to select as many as article we want and then select the appropriate action, deletion, adding a tag, removing a tag , etc

**Comment by nicosomb** [comment] 2017-12-24 11:51
Your issue is a duplicate of https://github.com/wallabag/wallabag/issues/3118

**Closed by nicosomb** 2017-12-24 11:51 UTC
