### ISSUE TITLE
[PDF EXPORT] Export to pdf with Chinese text, will make it unreadable (duplicate with #5432)

### ISSUE THREAD

**Issue by 1itt1eB0y** [wallabag/wallabag#6093] opened 2022-11-23 08:40 UTC
### Environment

* **Version**: Latest
* **Installation**: Docker
* **PHP version**: Docker embeadded
* **OS**: Docker embeadded
* **Database**: Sqlite
* **Parameters**:

### What steps will reproduce the bug?

URL for example: https://mp.weixin.qq.com/s/XQSOVOqtUvuv9DL28YeCCw

PDF exported: [huai yun hui gai bian nu xing de da nao chan hou1nian cai neng hui fuhuan qiu ke xue yao wen.pdf](https://github.com/wallabag/wallabag/files/10073822/huai.yun.hui.gai.bian.nu.xing.de.da.nao.chan.hou1nian.cai.neng.hui.fuhuan.qiu.ke.xue.yao.wen.pdf)

Screenshot with webpage: 
![图片](https://user-images.githubusercontent.com/29831189/203502856-741824e8-c63a-47c2-8e24-5f4ee14337cc.png)

**Comment by KevinSJ** [comment] 2023-05-19 10:38
I think this is actually a duplicate of #2113 , because the font bundled with tcpdf also does not support Chinese character by default. Can we consider supporting custom font for use when exporting pdf, or switch to use a different font as mentioned in #2113 ? I'm willing to give it a go and try to implement either option.

**Closed** 2023-05-22 07:41 UTC
Labels: feat: export/pdf
