### ISSUE TITLE
Changing view mode causes Error 500 response

### ISSUE THREAD

**Issue by MacLemon** [wallabag/wallabag#3669] opened 2018-06-10 18:48 UTC
### Issue details

In any list view, like unread, or in a tag list, clicking the view-mode button, causes an error 500 response. That makes a call to /config/view-mode
When going back with the browser back-button and then reloading the page the view-mode has been successfully changed though. This behaviour is the same for toggling view-mode either way.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.2
* How did you install wallabag? Via `git clone` or by downloading the package?: git-clone
* Last wallabag version that did not exhibit the issue (if applicable): n/a this is my first wallabag installation
* php version: PHP 7.1.18
* OS: FreeBSD 11.1-RELEASE-p10
* type of hosting (shared or dedicated): dedicated, self-hosted
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): PostgreSQL

### Steps to reproduce/test case
In any list view, like unread, or in a tag list, clicking the view-mode button, causes an error 500 response.

Error message presented to the user is:
500: Internal Server Error
Cannot redirect to an empty URL.

The nginx `access-log` shows these lines:
```
/var/nginx/hostname.example.com/app.php > GET /config/view-mode HTTP/2.0
/var/nginx/hostname.example.com/app.php > GET /js/routing?callback=fos.Router.setData HTTP/2.0
```

**Comment by j0k3r** [comment] 2018-06-11 12:42
Could you look into the `PATH/TO/WALLABAG/var/logs/prod.log` and see if you got the error log about that 500?
Thanks

**Comment by Paulikid** [comment] 2018-08-15 15:00
same here on Ubuntu 16.04.1. 
Wallabag version 2.3.3, PHP 7.0.30, MySQL Database. This is the line from the prod.log of my wallabag instance: 

`[2018-08-15 16:23:50] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Cannot redirect to an empty URL." at /var/www/html/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/RedirectResponse.php line 86 {"exception":"[object] (InvalidArgumentException(code: 0): Cannot redirect to an empty URL. at /var/www/html/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/RedirectResponse.php:86)"} []'

**Comment by Kdecherf** [comment] 2018-09-01 16:02
The issue is caused by an empty Referer header on your browser. What's your browser? Do you have any addon or custom setting regarding the referer data?

**Comment by joshp23** [comment] 2018-11-13 05:18
@Kdecherf thanks! Running nginx and had `add_header Referrer-Policy no-referrer;` in a global ssl config. Commented that out and all is running well.

**Comment by j0k3r** [comment] 2019-01-11 12:37
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Closed by j0k3r** 2019-01-11 12:37 UTC
Labels: Awaiting response

**Comment by Paulikid** [comment] 2019-02-03 20:42
> @Kdecherf Sorry for the late reply. Same on apache, commented out `Header always set Referrer-Policy "no-referrer"`in wallabag vhost config and the issue was gone. 

Thanks again.
