### ISSUE TITLE
Option not to display post thumbnail 

### ISSUE THREAD

**Issue by iGormilhit** [wallabag/wallabag#2492] opened 2016-10-23 07:50 UTC
Depending on the originals articles, I find the "Title Image" or "Post Thumbnail" irrelevant, adding no information, and sometimes pixelised and ugly.  And I find not so much usefull that when I clic on this image, it display the title, but not the article itself, as I would expect.

I do understand that this feature exists, but I would like to have an option to deactivate it.

**Comment by nicosomb** [comment] 2016-10-26 11:34
Is that a duplicate of #1874?

**Comment by iGormilhit** [comment] 2016-10-26 11:43
@nicosomb I would say it related to it, sure, but I would even like to have the option to disable the feature, I find this post thumbnail annoying, from a usabillity and a readability point of view. Sometimes the images are ugly, but it's not always because of the size, but because of the image itself... And the title, and the begining of the article are more useful information than an image. At least for me...

![selection_455](https://cloud.githubusercontent.com/assets/1557213/19724698/ff70ddca-9b81-11e6-9479-0010ee705538.png)

**Comment by nicosomb** [comment] 2016-10-26 11:58
@tcitworld @j0k3r @modos189 If we don't display preview pictures, what should we display? Extract of the article? Or just the title?

**Comment by j0k3r** [comment] 2016-10-26 12:04
Extract I guess

**Comment by nicosomb** [comment] 2016-11-10 19:04
Like that? 
![capture d ecran 2016-11-10 a 19 34 31](https://cloud.githubusercontent.com/assets/121870/20189285/bd52ec7e-a77c-11e6-9f64-e1c62d4d1419.png)

**Comment by iGormilhit** [comment] 2016-11-10 20:49
Yeah, like that, exactly ! But without the Trumps news, please. :smile:

**Comment by nicosomb** [comment] 2017-01-31 20:17
I think that `list view` (available in 2.2) fixed this issue. @iGormilhit can you confirm that? 
![capture d ecran 2017-01-31 a 21 15 47](https://cloud.githubusercontent.com/assets/121870/22482710/7a7a9280-e7fa-11e6-8e84-ae2074768a74.png)

**Comment by iGormilhit** [comment] 2017-02-01 05:54
@nicosomb I have to wait till thursday evening to upgrade. I'll confirm then. Thanks for all the works!

**Comment by iGormilhit** [comment] 2017-02-03 09:40
@nicosomb @j0k3r I've just upgraded wallabag (with full success :smile: ), and yes the `list view` is much better, in regards of the post thumbnail. But (yes, I know...), I'm missing some information, like the tags for instance. So, yes, the issue is kind of fixed. 👍

**Comment by nicosomb** [comment] 2017-02-03 09:41
> like the tags for instance

We have an issue for that, see https://github.com/wallabag/wallabag/issues/2808 ;-)

**Closed by nicosomb** 2017-02-03 09:41 UTC
Labels: Awaiting response, Improvement
