### ISSUE TITLE
Add api endpoint for create new user

### ISSUE THREAD

**Issue by bourvill** [wallabag/wallabag#3056] opened 2017-04-25 10:08 UTC
- [x] Is it possible to create a new API to add a user?
- [x] In the response I suggest the addition of a previously created client_id and client_secret

**Comment by tcitworld** [comment] 2017-04-28 08:35
I'm not sure the new password should pass through the API, what do you think ?

**Comment by bourvill** [comment] 2017-04-28 08:43
This suggestion is to save time on creating a new token for the customer.

Typically after the creation of the user this one will directly connect. 
But can we put it on another endpoint?

**Comment by nicosomb** [comment] 2017-05-02 09:48
The second part of your issue seems to be a duplicate of #3056 by @jlnostr, right?

**Comment by tcitworld** [comment] 2017-05-02 10:06
\o/ \o/
/o/ \o\
/oo\
|o|
\o/
Fusion !

**Comment by nicosomb** [comment] 2017-05-02 10:08
Yah ! 

> When a user wants to use the API from his third-party application, it's required to create an application in the backend. Maybe we can add an API endpoint that automatically creates a client with a specific name (related to #1765) when the login is successful. This way the user only needs to enter the URL of his wallabag instance and the credentials. The rest would be done by the API.

from @jlnostr

**Comment by j0k3r** [comment] 2017-05-30 13:27
First step done.

**Comment by nicosomb** [comment] 2017-05-30 13:36
@bourvill @di72nn @jlnostr  (and also @Rurik19 @Simounet maybe): you can now create a user through the API in your applications.

**Comment by j0k3r** [comment] 2017-05-30 13:38
Well, it'll be available in the 2.3.0 release :slightly_smiling_face:

**Comment by nicosomb** [comment] 2017-05-30 13:45
Sure, but they can prepare their applications, to be OK when we'll release 2.3 (I dream of a release of each of our applications when we publish a minor release of the web app)

**Closed** 2017-06-08 15:25 UTC
Labels: API, Feature
