### ISSUE TITLE
Pictures doubled at the beginning of an article

### ISSUE THREAD

**Issue by biva** [wallabag/wallabag#3498] opened 2017-12-13 11:18 UTC
### Issue details
For some articles including a picture, the picture may be doubled at the beginning of the article. See for example this article: http://www.lemonde.fr/pixels/article/2017/12/13/star-wars-si-vous-avez-rate-les-episodes-precedents_5228797_4408996.html

![image](https://user-images.githubusercontent.com/9964305/33936331-7db9d336-dfff-11e7-8753-5a6305711bf2.png)

I don't know if it's a fetching issue: I saw this issue only with lemonde.fr

### Environment
* wallabag 2.3 on Debian 9

**Comment by tcitworld** [comment] 2017-12-13 11:21
Pretty sure there's already an issue for that, but can't find it. :(

**Comment by Kdecherf** [comment] 2017-12-13 22:16
Duplicate of https://github.com/wallabag/wallabag/issues/1875

**Closed by Kdecherf** 2017-12-13 22:16 UTC
Labels: Bug
