### ISSUE TITLE
import list of urls

### ISSUE THREAD

**Issue by jeyca** [wallabag/wallabag#4571] opened 2020-09-07 10:56 UTC
is there a way to just import a list of links? in #599 there is a html import mentioned, but I cannot find it anymore

**Comment by wuuei** [comment] 2021-01-14 13:52
I've found this issue while searching for a way to import my link list.
You probably already solved this, but just in case.
As a, admittedly stupid (but it works 😄), workaround you could:

1. "Install" Firefox portable
2. Add the "Open Multiple URLs" addon to firefox
3. Open the links with the addon
4. Save all tabs as bookmarks
5. Export bookmarks as JSON
6. Import that file in wallabag

I've successfully used this to import my lists.

**Comment by bipox** [comment] 2021-02-19 14:57
@wuuei 

Thanks, this worked. 

And here's my vote for an "import text file" option

**Comment by Ablu** [comment] 2021-05-22 13:17
The mail based "adding" mechanism worked for me. It allows to import multiple entries per mail, one line being one entry :innocent:

**Comment by nicosomb** [comment] 2021-09-02 14:31
This issue is a duplicate of #3757.

**Closed by nicosomb** 2021-09-02 14:31 UTC

**Comment by HammyHavoc** [comment] 2023-11-26 12:14
> The mail based "adding" mechanism worked for me. It allows to import multiple entries per mail, one line being one entry 😇
> 
> **EDIT: It did not import all the links, I sent 240 links, but only 104 went through.**

I couldn't find any information on importing via mail, can you share how you did it?

**Comment by HolgerAusB** [comment] 2023-11-26 19:48
@HammyHavoc AFAIK that is for the hosted version app.wallabag.it only:
https://app.wallabag.it/premium/account
I never tried that
