### ISSUE TITLE
Cant put wallabag outside of webfolder

### ISSUE THREAD

**Issue by jonazc** [wallabag/wallabag#3472] opened 2017-12-11 13:34 UTC
### Issue details
When wallabag is installed in `/var/www/htdocs/wallabag` I can open it via https://example.com/wallabag/web. But of course I don't want to have it this way (with `/web`) and I don't want to put the source files in the document root. So I normally put symfony apps in `/var/www/wallabag` and then make a symbolic link from `/var/www/htdocs/wallabag` to  `/var/www/wallabag/web`

But here I get this error in error.log:

`[Mon Dec 11 14:18:07 2017] [warn] [client 217.6.72.38] mod_fcgid: stderr: PHP Warning:  file_get_contents(/var/www/virtual/user/walla.example.com/src/Wallabag/UserBundle/Resources/views/Security/login.html.twig): failed to open stream: No such file or directory in /var/www/virtual/user/wallabag/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 145`

yes, actually `/var/www/htdocs/wallabag` is `/var/www/virtual/user/walla.example.com` here, but in principle its the same, that I want to put the src files outside of the webfolder and then make a symbolic link to `wallabag/web`, but that seems not to work here.

**Comment by nicosomb** [comment] 2017-12-11 13:40
Hello @jonazc.

It seems to be a duplicate of #1075
Feel free to reopen it if I'm wrong.

**Closed by nicosomb** 2017-12-11 13:40 UTC
