### ISSUE TITLE
Add Mastodon as a sharing application

### ISSUE THREAD

**Issue by bepolymathe** [wallabag/wallabag#3388] opened 2017-10-24 12:40 UTC
Hi,

Just a suggestion. It would be great to add mastodon as a sharing application (like twitter and diaspora). 
Thanks for this application ;-)
Regards

**Comment by tcitworld** [comment] 2017-10-24 12:47
Duplicate of https://github.com/wallabag/wallabag/issues/3033

**Closed by tcitworld** 2017-10-24 12:47 UTC
