### ISSUE TITLE
wallabag reddit comment pages

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#692] opened 2014-05-16 10:06 UTC
Currently, awful display.

(via Leo Staley on Chrome Store)

**Comment by nicosomb** [comment] 2015-07-31 06:45
Assigned to [Tender discussion #203](http://support.wallabag.org/discussions/problems/203-reddit).

**Comment by j0k3r** [comment] 2016-04-10 19:01
Duplicate of https://github.com/wallabag/wallabag/issues/1229

**Closed by j0k3r** 2016-04-10 19:01 UTC
Labels: Site Config
