### ISSUE TITLE
Symlinked folders are not user friendly with FTP clients in shared hosting distribution

### ISSUE THREAD

**Issue by martin-damien** [wallabag/wallabag#2755] opened 2017-01-17 07:26 UTC
### Issue details

If you send the files using a simple FTP client on a shared hosting (Filezilla / OVH) you get a working copy of Wallabag but with theme issues.

In fact the symlink `/web/bundles/wallabagcore/themes/_global/img` is not copied as well.

The shared hosting distribution should provide a non symlinked folders copy.

The application works, but there is missing images (like the logo on the left).

### Environment

* wallabag version (or git revision) that exhibits the issue: latest-2.1.5
* How did you install wallabag? Via `git clone` or by downloading the package? shared hosting package
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7.1
* OS: Unknown (OVH)
* type of hosting (shared or dedicated): shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

- `wget http://wllbg.org/latest-v2-package && tar xvf latest-v2-package`
- Copy files through FTP using Filezilla

**Comment by nicosomb** [comment] 2017-01-17 10:02
Hello @martin-damien ! 

Thank you for your message. It's a duplicate of https://github.com/wallabag/wallabag/issues/2715 so I close it. 

Have a nice day.

**Closed by nicosomb** 2017-01-17 10:02 UTC
