### ISSUE TITLE
Saving images with v2?

### ISSUE THREAD

**Issue by gerroon** [wallabag/wallabag#2139] opened 2016-06-08 03:48 UTC
Hi

I cant find information about how to save images in an article in the database. 

I am using 2.0.3 on Debian.

thanks

**Comment by j0k3r** [comment] 2016-06-08 08:07
This feature hasn't been developped in the v2 yet.
But it is planned

**Comment by aymercury** [comment] 2016-10-03 14:25
Is this feature still not available? I cannot find any mention of it in any release notes (from 2.0.0 to 2.1.0)...

**Comment by j0k3r** [comment] 2016-10-03 14:26
It's in progress https://github.com/wallabag/wallabag/pull/2180
We hope to release it with 2.2.0

**Comment by j0k3r** [comment] 2016-10-03 14:27
Also, duplicate of https://github.com/wallabag/wallabag/issues/2033

**Comment by aymercury** [comment] 2016-10-03 14:27
Thanks! I am still on 1.9.0 because of this missing feature...

**Comment by j0k3r** [comment] 2016-10-03 14:28
We know, a lot of people are requiring it :wink:

**Closed by j0k3r** 2016-10-03 14:27 UTC
Labels: Feature
