### ISSUE TITLE
public list of articles/links with tags

### ISSUE THREAD

**Issue by xavierle** [wallabag/wallabag#812] opened 2014-08-15 10:57 UTC
is there a page where a registered user of wallabag can see all the articles/links saved in the wallabag installation ?
(according a public/private selection)

what is appreciated in those hosted solutions is that you easily get access to your selection but also discover from others selections

**Comment by nicosomb** [comment] 2016-01-24 08:09
Duplicate of #95

**Closed by nicosomb** 2016-01-24 08:09 UTC
Labels: Feature
