### ISSUE TITLE
wallassets fonts url Issue

### ISSUE THREAD

**Issue by softaculous** [wallabag/wallabag#3518] opened 2017-12-18 10:29 UTC
### Issue details
In 2.3.0 wallassets fonts mentioned in url are wrong. Fonts are not displayed correctly.

[https://github.com/wallabag/wallabag/issues/3485#issuecomment-351971104](https://github.com/wallabag/wallabag/issues/3485#issuecomment-351971104) script can be updated Instead of changing Apache or NGinx configuration ? In shared server users will not be able to make such changes. 

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.0
* How did you install wallabag? Via `git clone` or by downloading the package? : By downloading package
* php version: 5.5.9
* type of hosting (shared or dedicated): Shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case
Install Wallabag in sub-directory and after login it do not display fonts correctly

**Comment by nicosomb** [comment] 2017-12-18 10:39
Hello @softaculous team! 

Your issue is a duplicate of #3485.

**Closed by nicosomb** 2017-12-18 10:39 UTC

**Comment by softaculous** [comment] 2017-12-18 10:45
@nicosomb We have referenced that in issue. Our question is Instead of user modifying configuration Can Wallabag script handle this ?
