### ISSUE TITLE
Problem extracting package

### ISSUE THREAD

**Issue by gavygavy132456** [wallabag/wallabag#2715] opened 2016-12-21 09:32 UTC
### Issue details

Can't extract properly package wallabag-release-2.1.5.tar.gz.
Detected after install in shared hosting when logo didn't appear because folder "img" in the global theme is extracted as file : 
![wallabag](https://cloud.githubusercontent.com/assets/24694665/21383995/b9ffb67c-c768-11e6-88ba-ea6bb8ad4d5a.PNG)

Used 7zip.

### Environment

* Wallabag 2.1.5
* Downloaded package from http://doc.wallabag.org/en/master/user/installation.html => "shared hosting" => http://wllbg.org/latest-v2-package 
* php version: Prior to install
* OS: Windows
* type of hosting (shared or dedicated): Shared, but again, prior to install
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite,but again, prior to install

### Steps to reproduce/test case

1- Use http://wllbg.org/latest-v2-package link to get "wallabag-release-2.1.5.tar.gz"
2- Extract to get "wallabag-release-2.1.5.tar"
3- Extract again to get uncompressed ressources in file "release-2.1.5"

**Comment by sigmap** [comment] 2017-01-17 09:59
I'm also having the same issue, results in images failing to load

**Comment by nicosomb** [comment] 2017-02-07 11:49
In fact, it's a duplicate of wallabag/wallabag#2794, we have more details on the other issue.

**Closed by nicosomb** 2017-02-07 11:49 UTC
