### ISSUE TITLE
Adding URL with semicolon does not work

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#4117] opened 2019-09-14 10:11 UTC
### Issue details

Adding a URL with a semicolon does not work via web or via bookmarklet

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.8
* How did you install wallabag? Via `git clone` or by downloading the package? git
* Last wallabag version that did not exhibit the issue (if applicable): 
* php version: 7
* OS: debian
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): pg

### Steps to reproduce/test case

Try to add an article which article URL has a  semicolon in it, e.g. https://www.stimme.de/archiv/stadt-hn/sonstige-Schwaebischer-Kongo;art1925,374467

Edit: Oh, i have a log from the bookmarklet:
```

[2019-09-14 11:57:14] request.INFO: Matched route "bookmarklet". {"route":"bookmarklet","route_parameters":{"_controller":"Wallabag\\CoreBundle\\Controller\\EntryController::addEntryViaBookmarkletAction","_route":"bookmarklet"},"request_uri":"https://wallabag.linux4tw.de/bookmarklet?url=%22https%3A%2F%2Fwww.stimme.de%2Farchiv%2Fstadt-hn%2Fsonstige-Schwaebischer-Kongo%3Bart1925%2C374467","method":"GET"} []
[2019-09-14 11:57:14] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area"} []
[2019-09-14 11:57:14] security.DEBUG: User was reloaded from a user provider. {"username":"strubbl","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2019-09-14 11:57:15] app.DEBUG: Restricted access config enabled? {"enabled":0} []
[2019-09-14 11:57:15] graby.INFO: Graby is ready to fetch [] []
[2019-09-14 11:57:15] app.ERROR: Error while saving an entry {"exception":"[object] (Exception(code: 0): Url \"http://\"https//www.stimme.de/archiv/stadt-hn/sonstige-Schwaebischer-Kongo;art1925,374467\" is not valid. at /home/strubbl/git/wallabag/vendor/j0k3r/graby/src/Graby.php:497)","entry":"[object] (Wallabag\\CoreBundle\\Entity\\Entry: {})"} []
[2019-09-14 11:57:15] app.DEBUG: DownloadImages: Folder used for that Entry id {"folder":"/home/strubbl/git/wallabag/web/assets/images/1/9/191e3f3d","entryId":8876} []
[2019-09-14 11:57:15] app.DEBUG: DownloadImagesSubscriber: updated html. [] []
[2019-09-14 11:57:15] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
```

**Comment by Kdecherf** [comment] 2019-09-14 10:19
Interestingly, I am not able to reproduce this issue via web on a similar installation (_debian, php 7, pg_).

**Comment by Kdecherf** [comment] 2019-09-14 10:23
After reading the logs, I'm not sure that the issue is related to the semi-colon.

There is a `%22` prepended to the url sent to the bookmarklet which is incorrectly translated into `http://\"https//…`

**Comment by Strubbl** [comment] 2019-09-14 10:25
When i add the article via web interface, i get an error, which points me to a wrong TLS cert, the one you can see in the first screenshot in https://support.mozilla.org/en-US/kb/what-does-your-connection-is-not-secure-mean

**Comment by nicosomb** [comment] 2019-09-27 14:50
Seems ok for me on `master` branch. 

<img width="1006" alt="Capture d’écran 2019-09-27 à 16 50 07" src="https://user-images.githubusercontent.com/121870/65778820-e22bea80-e146-11e9-9950-68dae5a6724a.png">

**Comment by Strubbl** [comment] 2020-08-12 12:44
As this seems to be fixed on master, can this issue be added to the milestone 2.4?

**Comment by j0k3r** [comment] 2020-08-21 07:50
@Strubbl added.
So I'll close it, thanks for the notification!

**Closed by j0k3r** 2020-08-21 07:50 UTC

**Comment by Strubbl** [comment] 2020-12-16 23:34
This issue still exists at my machine with wallabag 2.4. I guess it is a bug in apache or php since i am seeing the following log messages in apache's log:

```
==> error.log <==
[Thu Dec 17 00:33:30.123732 2020] [core:notice] [pid 22562] AH00052: child pid 22568 exit signal Segmentation fault (11)
[Thu Dec 17 00:33:31.127075 2020] [core:notice] [pid 22562] AH00052: child pid 22563 exit signal Segmentation fault (11)
[Thu Dec 17 00:33:31.127233 2020] [core:notice] [pid 22562] AH00052: child pid 22564 exit signal Segmentation fault (11)
[Thu Dec 17 00:33:31.127273 2020] [core:notice] [pid 22562] AH00052: child pid 22600 exit signal Segmentation fault (11)
[Thu Dec 17 00:33:32.130940 2020] [core:notice] [pid 22562] AH00052: child pid 22566 exit signal Segmentation fault (11)
[Thu Dec 17 00:33:32.131360 2020] [core:notice] [pid 22562] AH00052: child pid 22567 exit signal Segmentation fault (11)
[Thu Dec 17 00:33:33.139354 2020] [core:notice] [pid 22562] AH00052: child pid 22565 exit signal Segmentation fault (11)
[Thu Dec 17 00:33:33.139607 2020] [core:notice] [pid 22562] AH00052: child pid 22623 exit signal Segmentation fault (11)
[Thu Dec 17 00:33:34.158088 2020] [core:notice] [pid 22562] AH00052: child pid 22629 exit signal Segmentation fault (11)
[Thu Dec 17 00:33:34.158515 2020] [core:notice] [pid 22562] AH00052: child pid 22630 exit signal Segmentation fault (11)

==> access.log <==
::1 - - [17/Dec/2020:00:33:35 +0100] "OPTIONS * HTTP/1.0" 200 110 "-" "Apache/2.4.38 (Debian) OpenSSL/1.1.1d (internal dummy connection)"

```

**Comment by j0k3r** [comment] 2020-12-17 08:35
Work fine on my side
![image](https://user-images.githubusercontent.com/62333/102463270-2e649280-404b-11eb-9230-5f32d2321799.png)

What about wallabag log?

**Comment by Strubbl** [comment] 2021-01-05 23:06
There is no new line added to the log, because i get the following error when adding this link via web:

![image](https://user-images.githubusercontent.com/97055/103709511-fa79ee80-4fb2-11eb-95a4-0e7625254504.png)

**Comment by Strubbl** [comment] 2021-01-05 23:44
The issue is also with https://www.stimme.de/ only. So this is no issue with the semi-colon or comma. It has to be a config issue combination on my and stimme.de's site.

**Comment by Strubbl** [comment] 2021-01-06 00:18
i attached gdb to the apache and found out that it is a problem within [libpcre2-8-0](https://packages.debian.org/buster/libpcre2-8-0)

```
(gdb) c
Continuing.
[New Thread 0x7f6b121ff700 (LWP 18163)]
[Thread 0x7f6b121ff700 (LWP 18163) exited]

Thread 1 "apache2" received signal SIGSEGV, Segmentation fault.
0x00007f6b23bdbb15 in ?? () from target:/lib/x86_64-linux-gnu/libpcre2-8.so.0
(gdb) backtrace
#0  0x00007f6b23bdbb15 in ?? () from target:/lib/x86_64-linux-gnu/libpcre2-8.so.0
#1  0x00007f6b135a9b7c in ?? ()
#2  0x7fffffff00000001 in ?? ()
#3  0x0000000000000000 in ?? ()
(gdb) c
Continuing.

Thread 1 "apache2" received signal SIGSEGV, Segmentation fault.
0x00007f6b23bdbb15 in ?? () from target:/lib/x86_64-linux-gnu/libpcre2-8.so.0
(gdb) c
Continuing.

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.
```

**Comment by Strubbl** [comment] 2021-01-06 00:47
The issue in libpcre2-8-0 is fixed in Debian testing already. No need to report an upstream bug. This issue is solved. Finally.
