### ISSUE TITLE
Porting to nextcloud

### ISSUE THREAD

**Issue by Matthias84** [wallabag/wallabag#3902] opened 2019-03-09 18:36 UTC
### Issue details

While I like wallabag, I also noticed that the maintenance for non PHP experienced admins on shared hoster isn't easy. Also I see that there is a lot of work that needs to be done, but the author can only spend a limited amount of Time.

So I suggest to move wallabag to become an Nextcloud app as some suggested it at #408. I see a lot of pros:
* using established framework (UI, IPC, APIs, user management, ...)
* using federation
* integration of existing mobile apps / account discovery / ... 

All in all, this allows to focus on what wallabags functionality (dumping webcontent) and will allow an easier setup for people that enjoy selfhosting.

**Comment by j0k3r** [comment] 2019-03-09 20:08
While it's interesting to have more feedback about that issue, I think it's better to post a comment in the issue itself instead of creating an other issue.

Duplicate of #408

**Closed by j0k3r** 2019-03-09 20:08 UTC
