### ISSUE TITLE
Saving to pdf doesn't work because it can't download a picture.

### ISSUE THREAD

**Issue by mathwhiz1212** [wallabag/wallabag#1190] opened 2015-05-05 17:48 UTC
Saving to pdf doesn't work because it can't download a picture, I would rather it just skip the picture.
The error: TCPDF ERROR: [Image] Unable to fetch image: https://help.ubuntu.com/community/IconsPage?action=AttachFile&do=get&target=warning.png

Wallabag v1.9.0, mysql  Ver 14.14 Distrib 5.5.43, PHP 5.4.39-0+deb7u2 and running raspbian on a raspberry pi 2.

**Comment by tcitworld** [comment] 2015-05-05 17:50
Duplicate of #1011. :)

We need to work on the librairy itself.

**Closed by tcitworld** 2015-05-05 17:50 UTC
