### ISSUE TITLE
Request features: Share to another wallabag account

### ISSUE THREAD

**Issue by disque-monde** [wallabag/wallabag#3428] opened 2017-11-21 12:20 UTC
Hi, Can tou add a function of share between accounts wallabag ?

**Comment by nicosomb** [comment] 2017-11-21 12:25
Hello @disque-monde ! 

Your idea is a duplicate of https://github.com/wallabag/wallabag/issues/679 ;-) 
Please add more infos in this issue if you think that it's necessary.

**Closed by nicosomb** 2017-11-21 12:25 UTC
