### ISSUE TITLE
render of cards a little bit cut

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#2462] opened 2016-10-16 14:18 UTC
![16 octobre 2016 161447 gmt 0200](https://cloud.githubusercontent.com/assets/208212/19418031/dd2f5ca0-93bb-11e6-9e58-0e2f20ed8752.png)
### Environment
- wallabag version (or git revision) that exhibits the issue:2.1.1
- How did you install wallabag? Via `git clone` or by downloading the package? Git
- Last wallabag version that did not exhibit the issue (if applicable):2.0.8
- php version:5.6
- OS:debian 8.6
- type of hosting (shared or dedicated):dedicated
- which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):postgresql

**Comment by foxmask** [comment] 2016-10-16 14:19
The footer are tuncated , image of trash and star Wars not complelty displayed

**Comment by tcitworld** [comment] 2016-10-16 16:05
What your screen resolution so I can test ? https://github.com/wallabag/wallabag/pull/2460 should fix.

**Comment by foxmask** [comment] 2016-10-16 16:08
Android 5.1.1 on nexus 10 (so 10" of résolution) with firefox  v49

**Comment by eppfel** [comment] 2016-11-01 19:22
I think this is a duplicate of #2394

**Comment by j0k3r** [comment] 2016-11-01 21:30
Good catch @eppfel !

**Closed by j0k3r** 2016-11-01 21:30 UTC
Labels: UI
