### ISSUE TITLE
Content of <ruby> html tags not fetched correctly (problem with Japanese furigana)

### ISSUE THREAD

**Issue by Najrim** [wallabag/wallabag#3710] opened 2018-09-01 00:48 UTC
First of all, I'm using wallabag.it but I'm guessing here is the appropriate place to report bugs. If not, please tell me and I will close this issue.

There is a problem when fetching articles containing Japanese text with furigana (Japanese character written above a word like a superscript to show the pronunciation). It seems that part of the "ruby"-tag containing the word with the furigana doesn't get fetched, so that only the superscript is there but not the actual word. Trying to fetch [this](https://www.tofugu.com/japan/japanese-buddhism/) article I noticed that the HTML of the original website where one of the words using furigana appears is:

```
<ruby><span lang="ja">華厳</span><rp><span lang="ja">（</span></rp><rt><span lang="ja">けごん</span></rt><rp><span lang="ja">）</span></rp></ruby>
```

but on wallabag.it all the span-elements are missing, like this:

```
<ruby><rp>（</rp><rt>けごん</rt><rp>）</rp></ruby>
```

I tested it on f43.me and it had the same problem when using the "internal" parser but not when using the "external" one. Looking at the HTML I can see that the span-element is gone but the word (華厳) is still there:

```
<ruby>華厳<rp>（</rp><rt>けごん</rt><rp>）</rp></ruby>
```

**Comment by techexo** [comment] 2018-12-05 14:46
Hi @Najrim 

There is indeed an issue here. There is a step where the parser deletes all span elements, and I suspect it also deletes the character inside at the same time. Another possibility could be an encoding error that makes the parser think that the span are empty, thus deleting them.

I'll try to have a look into it.

**Comment by Kdecherf** [comment] 2018-12-05 14:46
Hello there,

Could you try to use a site config for this site with `prune: no`?

**Comment by techexo** [comment] 2018-12-05 15:07
@Kdecherf Doesn't make a difference with `prune: no` and:or `tidy: no`.

There is some more trickery in this: when you look at the HTML source, there is no `<span class="ja">...</span>` in the code. Idem when you fetch the page with `wget`, so these `span` are probably added via some JS witchcraft.

So there is a place in the code where this characters are stripped, and `span` are not the reason.

**Comment by techexo** [comment] 2018-12-05 15:34
@Kdecherf The problem comes from the `cleanupXss` function in graby, more particularly the call the [`htmLawed`](https://github.com/j0k3r/graby/blob/b3dfd7b2eb08686182885b49dabc41795ca07346/src/Graby.php#L1010-L1020) that makes the characters disappear.

I logged everywhere the code, and I am positive it's here they disappear.

**Comment by techexo** [comment] 2018-12-05 16:04
I have been trying to do some tests with [htmLawed test page](http://www.bioinformatics.org/phplabware/internal_utilities/htmLawed/htmLawedTest.php) with this content:
```
<ruby>南都六宗<rp>（</rp><rt>なんとりくしゅう</rt><rp>）</rp></ruby>
<ruby>三論<rp>（</rp><rt>さんろん</rt><rp>）</rp></ruby>
<ruby>倶舎<rp>（</rp><rt>くしゃ</rt><rp>）</rp></ruby>
<ruby>法相 <rp>（</rp><rt>ほっそう</rt><rp>）</rp></ruby>
<ruby>華厳<rp>（</rp><rt>けごん</rt><rp>）</rp></ruby>
<ruby>律<rp>（</rp><rt>りつ</rt><rp>）</rp></ruby>
```
and it's parsed in
```
 <ruby><rp>（</rp><rt>なんとりくしゅう</rt><rp>）</rp></ruby>
<ruby><rp>（</rp><rt>さんろん</rt><rp>）</rp></ruby>
<ruby><rp>（</rp><rt>じょうじつ</rt><rp>）</rp></ruby>
<ruby><rp>（</rp><rt>くしゃ</rt><rp>）</rp></ruby>
<ruby> <rp>（</rp><rt>ほっそう</rt><rp>）</rp></ruby>
<ruby><rp>（</rp><rt>けごん</rt><rp>）</rp></ruby>
<ruby><rp>（</rp><rt>りつ</rt><rp>）</rp></ruby>
```

The origin of the issue is absolutely that, but I don't know how/if we can disable `xss_filter` via site configs, for example. @Kdecherf @j0k3r could maybe have an idea?

**Comment by techexo** [comment] 2018-12-06 08:38
The other way is figuring out why htmLawed does that.

**Comment by Najrim** [comment] 2018-12-07 20:15
@techexo, it seems to have more to do with the `ruby` tag than with Japanese characters. Inputting:

```
<ruby>test</ruby>
<span>明日</span>
```

into the htmLawed test page you linked to results in:

```
<ruby></ruby>
<span>明日</span>
```

I have no idea why it does this. htmLawed is supposed to clean up html, right? Looking at examples from [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ruby) and [w3schools](https://www.w3schools.com/tags/tag_ruby.asp), Tofugu is using the tag in the correct way (the htmLawed test page also removes the content from both those examples by the way).

**Comment by techexo** [comment] 2018-12-07 23:12
@Najrim thanks for you research. It is weird because ruby markups are explicitly cited as supported in htmLawed documentation! Is there a way to do a bit report there?

**Comment by techexo** [comment] 2018-12-07 23:37
@Kdecherf, and thanks for the rest of the work! I'm a bit afraid of the time that issue will take to be fixed in "normal" setups. Is it a dependancy called directly by composer or a php library?

**Comment by Kdecherf** [comment] 2018-12-07 23:41
htmlawed is currently a dependency of graby, using `fossar/htmlawed`: https://github.com/fossar/HTMLawed

**Comment by techexo** [comment] 2018-12-07 23:53
Oh OK, great! I hope they will be able to merge that soon so that we can pull it for, maybe, 2.3.5. Thanks again 🙂

**Comment by Kdecherf** [comment] 2018-12-10 22:04
Sorry, auto-close triggered by a commit on a master branch.

**Closed** 2018-12-14 17:02 UTC
Labels: Bug, Upstream
