### ISSUE TITLE
Error in install process.

### ISSUE THREAD

**Issue by mathwhiz1212** [wallabag/wallabag#1175] opened 2015-04-02 03:08 UTC
Notice: Undefined variable: handle in /var/www/wallabag/install/index.php on line 137

Fatal error: Call to a member function prepare() on a non-object in /var/www/wallabag/install/install_functions.php on line 101

Self-hosted, raspbian on a raspberry pi. no problems with the compatibility test, Permissions given through sudo chown -hR www-data folder, As far as I can tell this is regardless of browser as I have tried serveral.
mysql Ver 14.14 Distrib 5.5.41, PHP 5.4.39

**Comment by mathwhiz1212** [comment] 2015-04-02 03:15
Weird.. doing the install over with a different username and it works until I get this error when I try to log in: 
Fatal error: Call to a member function fetchAll() on a non-object in /var/www/wallabag/inc/poche/Database.class.php on line 190

**Comment by tcitworld** [comment] 2015-04-02 10:16
Hmm, seems to be the same thing as #1114 (sorry, french).

**Comment by xpac1985** [comment] 2015-04-07 19:38
Same problem here:
http://support.wallabag.org/discussions/problems/133-install-fails-with-mysql-on-self-hosted-server
and here:
http://support.wallabag.org/discussions/problems/131-problem-installing-on-self-hosted-server

**Comment by tcitworld** [comment] 2015-04-07 22:01
Still can't reproduce it, though my php and mysql versions are identical or nearly identical. What the heck ?

@xpac1985 Can you check if you have empty or nearly databases (just the tags table) too ?

Gonna go with a Virtual Machine with Wheezy in it to check what I do wrong.

**Comment by xpac1985** [comment] 2015-04-07 22:20
mysql> SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'wallabag';
+----------+
| COUNT(*) |
+----------+
|        0 |
+----------+

Or in short - nothing ;-)

**Comment by tcitworld** [comment] 2015-04-07 22:24
Nothing. Sigh.

If you're motivated, you can check [the alpha release](https://github.com/wallabag/wallabag/releases/tag/1.9.1alpha2) for the next version, but even though I made some changes to the system, I wouldn't expect it to change anything.

**Comment by tcitworld** [comment] 2015-04-07 23:37
Okay, I tested Wheezy inside a WM, and it worked, once again.

Quick questions : is the MySQL server different than localhost ? Is the database already created ? Does the user really exists ?

**Comment by xpac1985** [comment] 2015-04-08 07:32
HA!
The alpha version helped, as in showing some MySQL Error code, which simply said: "Access denied".
I was perfectly sure that I used the right username and password, but after re-GRANTing all rights to the user the current stable as well as the alpha install fine.
No idea how I could have miss-copy-pasted the username and password, but obviously I did.
Problem solved, at least for me.
Thanks a lot for your super quick support!

**Comment by tcitworld** [comment] 2015-04-08 07:59
Oooh, that's interesting. :) Now I know how to fix that. A huge thank you !

**Comment by xpac1985** [comment] 2015-04-08 08:00
Let me add some little things:
You may want to add
"php composer.phar update"
to your install instructions, as for some reason composer tends to not install the most current versions of the needed dependencies (at least on my system).

**Comment by tcitworld** [comment] 2015-04-08 08:02
I will look up what's updated before. :)

**Comment by tcitworld** [comment] 2015-04-08 14:56
This is now fixed in dev branch. :)

**Closed by tcitworld** 2015-04-08 14:56 UTC
Labels: Bug
