### ISSUE TITLE
Syntax Error on installing v2 package with all dependencies

### ISSUE THREAD

**Issue by roccostorm** [wallabag/wallabag#1852] opened 2016-04-05 07:40 UTC
### Issue details

When running wallabag:install with package containing all dependencies, syntax error occurs.

`[USER@SERVER wallabag]$ php bin/console wallabag:install --env=prod

PHP Warning:  Unsupported declare 'strict_types' in /var/www/virtual/USER/html/wallabag/vendor/ocramius/proxy-manager/src/ProxyManager/Configuration.php on line 19
PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /var/www/virtual/USER/html/wallabag/vendor/ocramius/proxy-manager/src/ProxyManager/Configuration.php on line 97

[USER@SERVER wallabag]$ php --version

PHP 5.5.5 (cli) (built: Mar 14 2014 17:55:12)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2013 Zend Technologies
    with Zend OPcache v7.0.3-dev, Copyright (c) 1999-2013, by Zend Technologies
`

### Environment

* wallabag version 2.0.0
* downloaded wallabag-2.0.0.tar.gz
* php version: 5.5.5
* type of hosting (shared or dedicated): uberspace
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): no change, sqlite

**Comment by nicosomb** [comment] 2016-04-05 08:05
Duplicate of #1843. Please use this existing issue to give use more information (when did you download the package?)

**Closed by nicosomb** 2016-04-05 08:05 UTC
