### ISSUE TITLE
Snap Linux package - Wallabag?

### ISSUE THREAD

**Issue by AngelBCN** [wallabag/wallabag#2844] opened 2017-02-05 20:10 UTC
Is it possible in the future to snap package from wallabag? Today Nextcloud and Wekan have it installed in less than 2 minutes

**Comment by nicosomb** [comment] 2017-02-06 07:59
Hello @AngelBCN! Is your issue a duplicate of #1014?

**Comment by tcitworld** [comment] 2017-02-06 09:34
Kindof.

**Closed by tcitworld** 2017-02-06 09:34 UTC

**Comment by AngelBCN** [comment] 2017-02-06 18:54
Thanks
