### ISSUE TITLE
Missing pictures from link + pdf generation complains

### ISSUE THREAD

**Issue by hanklank** [wallabag/wallabag#2365] opened 2016-10-04 23:48 UTC
### Issue details

Just trying out wallabag, and the link http://www.flashtro.com/index.php?e=page&c=Checksums&al=alias8436
is missing the images on. Also, generating a pdf from that gives an error message.
TCPDF ERROR: [Image] Unable to fetch image: http://www.flashtro.com/cr/images/resource1.png

The images are existing and valid at the link above so it shouldn't be a problem.
### Environment
- wallabag version (or git revision) that exhibits the issue: The official framebag instance
### Steps to reproduce/test case

Look at the link - see text and valid pictures. Save it in wallabag - no pictures. Try to do an pdf - get the error.

**Comment by j0k3r** [comment] 2016-10-05 05:32
For the PDF part, looks like it's related to https://github.com/wallabag/wallabag/issues/1627

**Comment by hanklank** [comment] 2016-10-06 15:04
The link works fine with pictures using the http://f43.me/feed/test (read that it uses almost the same way as wallabag to retrieve content in another issue).  Oh btw, bugs in TCPPDF seems unlikely to be fixed as it's seems to be rewritten as  tc-lib-pdf instead or at least so it says at sourceforge.

**Comment by tcitworld** [comment] 2016-10-06 15:06
@hanklank Thanks for the heads up on tc-lib-pdf. ;)

**Comment by nicosomb** [comment] 2016-11-06 09:36
> Just trying out wallabag, and the link http://www.flashtro.com/index.php?e=page&c=Checksums&al=alias8436
is missing the images on.

Fixed in 2.1.3. 
About PDF problem, it's a duplicate of #1627. 

Please reopen if necessary.

**Closed by nicosomb** 2016-11-06 09:36 UTC
Labels: Site Config
