### ISSUE TITLE
Can't grab content of cairn.info pages

### ISSUE THREAD

**Issue by FrapiFrance** [wallabag/wallabag#6055] opened 2022-11-03 16:08 UTC
I have the problem with all www.cairn.info pages, very interesting website with lots of feature articles.

https://www.cairn.info/revue-internationale-de-politique-comparee-2001-1-page-59.htm

This page works on f43.me, on **first call**. When I retry to retrieve the page, then even f43.me "failed to make this item readable".

Here is my graby.log

[graby.log](https://github.com/wallabag/wallabag/files/9930896/graby.log)

I self-host a dockerised wallabag 2.3.8 on a raspberry pi 3

**Comment by j0k3r** [comment] 2022-11-03 21:22
Duplicate of #3174

**Closed by j0k3r** 2022-11-03 21:22 UTC
