### ISSUE TITLE
unknown error while speaking to annotation store

### ISSUE THREAD

**Issue by TheOneValen** [wallabag/wallabag#2366] opened 2016-10-05 06:25 UTC
### Issue details

I tried the annotation feature but when saving the annotation an error occurs.
### Environment
- wallabag version (or git revision) that exhibits the issue: 2.1.1
- git clone; git checkout 2.1.1
- Last wallabag version that did not exhibit the issue (if applicable): not applicable (not tried)
- php version: 5.6.26
- OS: Funtoo
- type of hosting (shared or dedicated): dedicated
- which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL
### Steps to reproduce/test case
- open saved article
- mark passage
- click annotation icon
- type text
- press save
- popup (snackbar) with error message "unknown error while speaking to annotation store" appears

**Comment by nicosomb** [comment] 2016-10-05 07:17
Hello @TheOneValen! 
I can't reproduce on my computer or on http://v2.wallabag.org (demo platform). 

Can you empty the `var/cache` folder?

**Comment by TheOneValen** [comment] 2016-10-05 07:24
Hm. 

`rm -r var/cache/*`

did not help maybe I am missing a dependency/use flag. How are annotations saved normally?

**Comment by nicosomb** [comment] 2016-10-05 07:26
They are stored in the database, like the articles. 

@tcitworld any idea?

**Comment by TheOneValen** [comment] 2016-10-05 08:05
Is there a way I can get a more verbose error message?

**Comment by tcitworld** [comment] 2016-10-05 08:36
Can you open the browser console and check for issues ? (Ctrl + Maj + K on Firefox, Ctrl + Maj + J on Chromium).

**Comment by TheOneValen** [comment] 2016-10-05 09:22
I Identified 2 Problems
`app/Resources/build/material.browser.js` seems to be missing
and
Some responseText yielded "Depricated"

**Comment by tcitworld** [comment] 2016-10-05 10:04
>  app/Resources/build/material.browser.js seems to be missing

You shouldn't have this issue. Did you use version 2.1.0 before ?

**Comment by TheOneValen** [comment] 2016-10-05 11:21
yes, but 2.1.0 didn't work. I waited for 2.1.1 and did all the update steps again

**Comment by tcitworld** [comment] 2016-10-05 11:23
> yes, but 2.1.0 didn't work. I waited for 2.1.1 and did all the update steps again

Indeed, but did you `git checkout --force` ?

What makes you say that ?
>  app/Resources/build/material.browser.js seems to be missing

Can you post the exact content from your browser console ?

**Comment by TheOneValen** [comment] 2016-10-05 11:26
I am not sure about the "--force". Is there a way I can check that after the fact?

The Output of the debug console is
`
          Unknown error while speaking to annotation store! Object { readyState: 4, getResponseHeader: [5]</</<.ajax/w.getResponseHeader(), getAllResponseHeaders: [5]</</<.ajax/w.getAllResponseHeaders(), setRequestHeader: [5]</</<.ajax/w.setRequestHeader(), overrideMimeType: [5]</</<.ajax/w.overrideMimeType(), statusCode: [5]</</<.ajax/w.statusCode(), abort: [5]</</<.ajax/w.abort(), state: [5]</</<.Deferred/d.state(), always: [5]</</<.Deferred/d.always(), then: [5]</</<.Deferred/d.then(), 13 more… }material.min.js:5:6051`

But I also see that there is a request to the file in question which yields a 404.

**Comment by tcitworld** [comment] 2016-10-05 11:35
> I am not sure about the "--force". Is there a way I can check that after the fact?

Does `git status` says you are on tag 2.1.1 and that it's clean ?

> But I also see that there is a request to the file in question which yields a 404.

To material.min.js, not material.browser.js, right ?

**Comment by TheOneValen** [comment] 2016-10-05 11:48
There were untracked files. I cleaned them, cleared the cache. Problem still exists.

No the request is to material.browser.js

**Comment by TheOneValen** [comment] 2016-10-12 10:55
I Found an entry id prod.log

`[2016-10-12 12:52:37] request.CRITICAL: Exception thrown when handling an exception (RuntimeException: Failed to start the session because headers have already been sent by "" at line 0. at /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php line 134) {"exception":"[object] (RuntimeException(code: 0): Failed to start the session because headers have already been sent by \"\" at line 0. at /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php:134)"} []`

Maybe that helps?

**Comment by tcitworld** [comment] 2016-10-12 11:17
Does the error comes at each article request ?

**Comment by TheOneValen** [comment] 2016-10-12 11:18
No. Only when try to save an annotation.

**Comment by tcitworld** [comment] 2016-10-12 11:20
Does your server logs have more informations ?

**Comment by TheOneValen** [comment] 2016-10-12 11:20
Sorry I Tuncated the entry:

```
[2016-10-12 13:18:24] request.INFO: Matched route "{route}". {"route":"annotations_post_annotation","route_parameters":{"_controller":"Wallabag\\AnnotationBundle\\Controller\\WallabagAnnotationContro
ller::postAnnotationAction","_format":"json","entry":"87","_route":"annotations_post_annotation"},"request_uri":"https://mydomain/annotations/87","method":"POST"} []                          [2016-10-12 13:18:24] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Failed to start the session because headers have already been sent by "" at line 0." at /var/www/wal
labag/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php line 134 {"exception":"[object] (RuntimeException(code: 0): Failed to start the session because headers have already been sent by \"\" at line 0. at /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php:134)"} []                                                                                                                                                                                                    [2016-10-12 13:18:24] request.CRITICAL: Exception thrown when handling an exception (RuntimeException: Failed to start the session because headers have already been sent by "" at line 0. at /var/www/
wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php line 134) {"exception":"[object] (RuntimeException(code: 0): Failed to start the session because headers have already been sent by \"\" at line 0. at /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php:134)"} []                                                                                                                                                                               [2016-10-12 13:18:24] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Failed to start the session because headers have already been sent by "" at line 0." at /var/www/wal
labag/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php line 134 {"exception":"[object] (RuntimeException(code: 0): Failed to start the session because headers have already been sent by \"\" at line 0. at /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php:134, RuntimeException(code: 0): Failed to start the session because headers have already been sent by \"\" at line 0. at /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php:134)"} []                                                                                                                                          [2016-10-12 13:18:24] request.CRITICAL: Exception thrown when handling an exception (RuntimeException: Failed to start the session because headers have already been sent by "" at line 0. at /var/www/
wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php line 134) {"exception":"[object] (RuntimeException(code: 0): Failed to start the session because headers have already been sent by \"\" at line 0. at /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php:134)"} []
```

Is the full entry on every annotation save.

**Comment by TheOneValen** [comment] 2016-10-12 11:21
I don't have apache logs enabled but if it helps say the word.

**Comment by nicosomb** [comment] 2016-11-09 13:24
I've got the same problem locally and on v2.wallabag.org.

**Comment by tcitworld** [comment] 2016-11-15 16:07
Does it still happens on v2.wallabag.org ?

**Comment by nicosomb** [comment] 2016-11-15 16:09
No. And I don't know why it works :)

**Comment by nicosomb** [comment] 2017-12-16 22:17
I close this issue. Feel free to open a new one if bug still occurs.

**Closed by nicosomb** 2017-12-16 22:17 UTC
Labels: Bug
