### ISSUE TITLE
Wrong display in wallabag (nextinpact.com)

### ISSUE THREAD

**Issue by GannonTdW** [wallabag/wallabag#6018] opened 2022-10-16 15:23 UTC
Hello,

I have some issue with paid press articles from Nextinpact.
Notes: paid items become free after one month

test_url was with a free article, I replaced with a payer.
But I get a 404 error.

I use wallabag in version 2.5.1, in self hosting with Yunohost (app version 2.5.1~ynh3)... and at this time, I do not understand how how to see the log of wallabag. I have open a issue here: https://github.com/YunoHost-Apps/wallabag2_ynh/issues/157

 - URL: https://www.nextinpact.com/article/70148/comment-et-pourquoi-cia-a-pu-trahir-ses-propres-espions
 - wallabag version: 2.5.1 (installed with yunohost,  )

```
prune:yes

body://div[@id="article-content"]
title://div[contains(concat(' ',normalize-space(@class),' '),' article-titles ')]//h1

requires_login: yes

login_uri: https://api-v1.nextinpact.com/api/v1/Auth/login
login_username_field: emailOrLogin
login_password_field: password

strip_id_or_class: container_form_alert
strip_id_or_class: spinner-container wide
strip_id_or_class: child-briefs-container

test_url: https://www.nextinpact.com/article/70148/comment-et-pourquoi-cia-a-pu-trahir-ses-propres-espions
```

**Comment by Kdecherf** [comment] 2022-10-16 16:29
Hello @GannonTdW,

NextInpact updated their website a few month ago with an unusual login mechanism, the siteconfig does not work anymore for paid articles and we can't easily fix it for now

**Comment by HolgerAusB** [comment] 2023-07-01 17:06
found a login page. maybe that helps?

```
login_uri: https://compte.nextinpact.com/
login_username_field: UserName
login_password_field: Password
```

**Comment by Kdecherf** [comment] 2023-07-03 21:23
@HolgerAusB unfortunately it is not enough: they use an API with a Authorization header for fetching content.

**Comment by simon2cyrene** [comment] 2023-10-30 21:34
NextInpact is to become Next and the future website is in beta, based on Wordpress. It should be possible to integrate it into compatible sites in the future, don't you think?
[https://beta.next.ink](https://beta.next.ink)

**Comment by j0k3r** [comment] 2023-10-31 08:05
Well, it'll then be catched by the fingerprint of wordpress:
<img width="829" alt="image" src="https://github.com/wallabag/wallabag/assets/62333/a8e4e81e-0a58-4537-b890-96cfd985c9c2">

**Comment by HolgerAusB** [comment] 2023-10-31 16:29
I am not at home to test it, @j0k3r, but as far as I remember, wallabag is merging fingerprint-config and host-match-config. So we just need a config with the log-in stuff in `.next.ink.txt`

**Comment by Pofilo** [comment] 2023-12-19 22:13
For next.ink, the wallabager extension is working almost perfectly (using from the browser option).

Only subtitles (*h3*) are missing, I don't know what they are doing but those subtitles are very strange (not able to select them for example).

As they are using wordpress, maybe the paywall can be passed as many other website though.

**Comment by HolgerAusB** [comment] 2023-12-20 07:34
@Pofilo that depends on, how the paywall is implemented. If there is a simple way (different url-path; user-agent=google; ...) that might be possible.

As long as they are in beta, it is a bit hard here. We should wait, until next.ink is stable. Then we can try to use credential stuff in the site_config. Are you a subscriber of next.ink and a self-hoster of wallabag, so we can test site_config together.

Can you post an article link, where the h3 are missing, please?

**Comment by Pofilo** [comment] 2023-12-20 08:26
I tried to play with https://siteconfig.fivefilters.net/ but without any success.
They still have the "Beta" logo anyway, so we shouln't do something specific for the paywall.

However, we may improve the wallabager extension (tell me if I should create an issue on the other repo).
Here is an example of "h3" gone when parsed by wallabager (can be tried without being a subscriber):
https://next.ink/120832/le-reseau-interministeriel-de-letat-rie-fete-ses-10-ans-et-se-modernise/

The header "1 million d'agents, 14 000 sites" is gone.
This header is between 2 `<p>` tags and looks like:
```
<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">1 million d’agents, 14 000 sites</h3>
<!-- /wp:heading -->
```

If I remove the `wp-block-heading`, it's working like a charm.
I don't really know what to conclude, maybe wallabager doesn't like this class ? (it's strange to me)

**Comment by HolgerAusB** [comment] 2023-12-20 13:57
1. Are you a subscriber of next.ink?
2. Are you self-hosting wallabag?

If both is yes, you may try [my config](https://github.com/HolgerAusB/ftr-site-config/blob/test_next.ink/.next.ink.txt), I figured out, a few weeks ago. But I could not test it well because of no subscription. And as I am not speaking French...

`<h3>` works with that, I think it's because of the `prune: no`

I tried the password thing with a free membership but can't find a difference, so it seems not to work. But you could try it. Username and Password should set in Wallabag UI ("Accès aux sites") and NOT (!!!) in the site_config.

Don't forget to clear wallabag's cache after each change of the site-config

**Comment by HolgerAusB** [comment] 2023-12-20 14:54
Sorry, first version did not work. h3 was tripped by wallabag. This one helps here:

```
find_string: class="wp-block-heading"
replace_string: class="wb_foo"
```

It's updated in my test_file I linked previously

**Comment by Pofilo** [comment] 2023-12-20 16:27
Oh thanks for your time.
With your site_config, the `<h3>` tags are working.

However, it does not pass the paywall (I set creds in "Accès aux sites").
I'm not familiar with all this stuff, how can I debug it ?

**Comment by HolgerAusB** [comment] 2023-12-20 16:32
that is difficult. I am not experienced with that credential stuff. I had commented out some extra_field definitions. You can try to activate them. Single or combinations of them. But if they secure the login with JavaScript Voodoo, we will never find out.

**Comment by Simounet** [comment] 2023-12-20 18:20
@Pofilo Can you try with this file please? https://raw.githubusercontent.com/fivefilters/ftr-site-config/e577f0a6aff39796bd623b917f1511c8df55e43f/next.ink.txt

**Comment by Pofilo** [comment] 2023-12-20 20:54
Yeah, I can confirm this works like a charm, thanks for your time.
Tested with several articles, all ok behind the paywall.

How did you managed to find this site config ?

**Comment by Simounet** [comment] 2023-12-20 21:09
Glad to ear that! Deep dive into next.ink JS to understand what was expected and some trial and error.
I saw that you get [my PR](https://github.com/fivefilters/ftr-site-config/pull/1274) so we should be able to close this issue, don't we?

**Comment by Pofilo** [comment] 2023-12-20 21:12
Yep, this issue can be closed as a solution is found.
One can get the site config early or just wait new versions.

**Closed** 2023-12-20 21:18 UTC
Labels: Site Config, fetch/paywall

**Comment by HolgerAusB** [comment] 2023-12-22 10:11
@Simounet a big Thank You for your deep dive ❤️❤️

@Pofilo Thank you for testing. In [PR1274](https://github.com/fivefilters/ftr-site-config/pull/1274#issuecomment-1865127936) you wrote:
> Only the very top image is dropped, but it's not very useful, so I might prefer not to have it.

Personally I prefer to have this lead images in. Sometimes they are not only symbolic images. I have combined Simon's config with mine, so we could have the lead image in.

It would be very nice, if you find some time to test [THIS CONFIG](https://github.com/HolgerAusB/ftr-site-config/blob/test_next.ink/next.ink.txt) intensivly with different articles. Take your time, no hurry during the holidays.

If something of the article is missing please post the relevant html code. Or should be something striped from the fetch? Then post the html part, too.

Happy holidays and a healthy new year!

**Comment by Pofilo** [comment] 2023-12-22 17:19
It's working well (on a lot of articles).

There is only one little thing (but it's more a bug on next side).

Example article link: https://next.ink/119273/en-ligne-les-promos-foireuses-restent-dactualite/ (requires paywall but I don't leak anything :))

Next behavior:
![image](https://github.com/wallabag/wallabag/assets/7527594/e6215a50-1f7e-4569-9048-929449950013)

Wallabag behavior:
![image](https://github.com/wallabag/wallabag/assets/7527594/95b74f79-700d-4907-8cb6-c0f17c55e6ad)

The source is:
```
<p><!-- /wp:paragraph --> <!-- wp:list --></p>
<ul>
<li style="list-style-type: none;">
<ul><!-- wp:list-item --></p>
<li><a href="https://next.ink/1860/promotions-bidons-en-ligne-bientot-fin/" target="_blank" rel="noreferrer noopener">Promotions bidon en ligne : bientôt la fin ?</a></li>
</ul>
</li>
</ul>
<p><!-- /wp:list-item --></p>
<p><!-- /wp:list --> <!-- wp:paragraph --></p>
```

I'm not sure we can delete this `<li>` tag that easily.
On some articles, their bullet is indented to the very left with only 1 level.

**Comment by HolgerAusB** [comment] 2023-12-22 18:27
uff, that could be hard to solve this without subscription. I'd bet on line 4 to be the bad one, because of the unopened `</p>`

try to add:
```
strip_comments: no
find_string: <ul><!-- wp:list-item --></p>
replace_string: <ul>
```

**Comment by Pofilo** [comment] 2023-12-22 19:29
Well, the problem does not comes from the missing `<p>` but the extra `<ul><li>` level.
I tried removing it without any success.

Anyway, it's too dangerous to remove it without breaking every other listing.
If this happens too often, I will maybe contact them to maybe fix the html issue on their side.
Otherwise, I think you can make a PR with your last site_config, it's a good improvement from the one merged lastly (only this issue which is minor as only few articles are impacted).

**Comment by HolgerAusB** [comment] 2023-12-23 08:00
I agree, that this could be dangerous. For browsers the voodoo is done by JavaScript to get a pretty result. For wallabag it could get worse, if we strip to much. So we keep that for now, as is. I think, you should NOT ask 'next' to correct their code. Because archiving their content with wallabag might not a thing they'd love to see.
Thank you, @Pofilo, for testing this.

**Comment by j0k3r** [comment] 2023-12-23 08:53
Good job guys.
