### ISSUE TITLE
impossible to add a tag

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#3411] opened 2017-11-09 12:51 UTC
### Issue details

When adding this link https://v4.gandi.net/hebergement/simple?language=python
we can't add a tag and, this trigger a JS error with material.min.js

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.3
* How did you install wallabag? Via `git clone` or by downloading the package?
* Last wallabag version that did not exhibit the issue (if applicable):2.2.3
* php version:7
* OS:debian 9
* type of hosting (shared or dedicated):dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):postgresql

### Steps to reproduce/test case

as decribed earlier, add the link and have a look at that page to add a tag for example, and open the JS console and see

```
Uncaught TypeError: Cannot read property 'hash' of undefined
    at HTMLUListElement.<anonymous> (material.min.js:11)
    at Function.each (material.min.js:6)
    at ga.fn.init.each (material.min.js:6)
    at ga.fn.init.init (material.min.js:11)
    at ga.fn.init.a.fn.tabs (material.min.js:11)
    at HTMLDocument.<anonymous> (material.min.js:11)
    at j (material.min.js:7)
    at Object.fireWith [as resolveWith] (material.min.js:7)
    at Function.ready (material.min.js:7)
    at HTMLDocument.h (material.min.js:6)
```
and it's impossible to add a tag

**Comment by Kdecherf** [comment] 2017-11-10 20:50
I can't reproduce this issue on current master

**Comment by j0k3r** [comment] 2017-11-11 10:46
I reproduced the bug on app.wallabag.it maybe it's fixed in 2.3.

**Comment by Kdecherf** [comment] 2017-12-11 22:29
What is the status of this issue?

**Comment by foxmask** [comment] 2017-12-12 09:43
it's ok in 2.3
thanks

**Closed** 2017-12-12 09:44 UTC
Labels: Awaiting response, Bug
