### ISSUE TITLE
"Stay signed in" don't do what it promise

### ISSUE THREAD

**Issue by shackra** [wallabag/wallabag#1550] opened 2016-01-04 02:56 UTC
I'm experiencing this on Framabag.

This means that I have to login every single time I close my web browser, which is annoying.

**Comment by he7d3r** [comment] 2016-01-07 19:10
Duplicate of https://github.com/wallabag/wallabag/issues/1515 ?

**Comment by j0k3r** [comment] 2016-01-07 21:14
@he7d3r :+1:

**Closed by j0k3r** 2016-01-07 21:14 UTC
Labels: Bug
