### ISSUE TITLE
wrong thumbnails

### ISSUE THREAD

**Issue by mstevens** [wallabag/wallabag#6191] opened 2022-12-26 13:45 UTC
### Environment

* **Version**: 2.5.2
* **Installation**: on app.wallabag.it
* **PHP version**:
* **OS**:
* **Database**:
* **Parameters**:

### What steps will reproduce the bug?

I'm not totally sure what triggers this, but thumbnail images duped on the wrong entries.

For example in the attached image, the refold thumbnail is shown against the unrelated site jvns.ca.

![Screenshot 2022-12-26 at 13 44 18](https://user-images.githubusercontent.com/66189/209555252-ca82515c-2d52-4b75-b2bf-8dfa65caf517.png)

**Comment by j0k3r** [comment] 2023-01-02 09:22
Did you add many articles at once?
Did you notice that just today?
Did you do something before noticing that?

**Comment by mstevens** [comment] 2023-01-02 10:15
I did an import from pinboard, it seems to be in the data I imported. I haven't seen it yet in data I added directly on wallabag.

It wasn't just today. I did the import around 21 Dec and it looked a bit odd then, it took a few days before I worked out exactly what was weird and opened the issue.

**Comment by nicosomb** [comment] 2023-08-03 13:11
This issue seems to be a duplicate of https://github.com/wallabag/wallabag/issues/5108 and it's now fixed.

**Closed by nicosomb** 2023-08-03 13:11 UTC
