### ISSUE TITLE
Wallabag shows French interface when English is choosen

### ISSUE THREAD

**Issue by he7d3r** [wallabag/wallabag#3252] opened 2017-06-27 11:04 UTC
On https://framabag.org, for the third time, the user interface is back in French, even if the language selected is English. When I open the config page, it shows English, however this is inconsistent with the language used in the interface. Clicking on ENREGISTER updates it correctly (for a few weeks at least):
![bug](https://user-images.githubusercontent.com/1754791/27584475-93ab1450-5b0e-11e7-8af2-0b6323e11a23.png)

**Comment by nicosomb** [comment] 2017-06-29 07:57
Hello @he7d3r. 

Could you clean your Framabag cookies? 
I think that we already had this issue on wallabag.it and it was a cookie issue.

**Comment by tcitworld** [comment] 2017-06-29 08:07
Also on Framabag the navbar on the login screen might mess up with the rest.

**Comment by he7d3r** [comment] 2017-06-29 12:22
I cleaned the cookies. If it happens again, I'll add a note here.
(BTW: it happened again a few minutes ago, before cleaning the cookies)

**Comment by he7d3r** [comment] 2017-07-01 00:21
Cleaning the cookies didn't help. =(

**Comment by he7d3r** [comment] 2017-07-10 13:34
Cleaning the cookies didn't help. :-1:

**Comment by tcitworld** [comment] 2017-07-10 13:51
@he7d3r Please check that your browser requests English as language. 
Firefox : Settings > Content > Languages
Chrome : Settings > Advanced > Languages
Check that english is on top of them.

**Comment by he7d3r** [comment] 2017-07-11 02:00
Yes, it (Firefox) does.

**Comment by tuxmouraille** [comment] 2017-08-11 20:40
Helo,
I have the same and opposite problem. I choose french for the default language and Wallabag is always in english.

**Comment by tuxmouraille** [comment] 2017-08-11 20:40
Helo,
I have the same kind but opposite problem. I choose french for the default language and Wallabag is always in english.

**Comment by gnppn** [comment] 2017-11-22 11:47
I have the same problem on wallabag.it (version 2.3) but I can't reproduce it when I try. Unlogging and relogging seems to fix it for me.

**Comment by jpbaril** [comment] 2018-07-27 05:12
Same here. Interface is constantly back to English even if French is set in configs.

**Comment by j0k3r** [comment] 2019-05-10 12:33
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Closed by j0k3r** 2019-05-10 12:33 UTC
Labels: Framabag

**Comment by he7d3r** [comment] 2019-05-11 19:39
The problem still happens. I still have "Langue: English" in the page
https://framabag.org/config
but the interface is in French.

**Comment by j0k3r** [comment] 2019-05-11 20:00
poke @tcitworld

**Comment by he7d3r** [comment] 2020-01-28 11:55
@j0k3r : Could you reopen this issue?

**Comment by mrtpcet** [comment] 2021-01-14 13:18
Same problem for me with Wallabag on Yunohost
