### ISSUE TITLE
large bookmark imports fails

### ISSUE THREAD

**Issue by anarcat** [wallabag/wallabag#1458] opened 2015-10-05 18:39 UTC
this is a followup for #1204, so cc @nicosomb @tcitworld 

i tried an import again with my regular dataset, now got:

```
ERROR 502 - Bad Gateway!

The following error occurred:

This server received an invalid response from an upstream server it accessed to fulfill the request.

If you get this message repeatedly please contact the webmaster.

Powered by ISPConfig
```

the dataset is my huge bookmark history:

```
1,8M    /home/anarcat/Downloads/bookmarks.html
```

thanks!

**Comment by tcitworld** [comment] 2015-10-05 18:44
Framabag seems to be quite overloaded at the moment.

**Comment by anarcat** [comment] 2015-11-09 18:01
got the same error again, one month later, with a similar dataset.

**Comment by anarcat** [comment] 2015-11-23 16:06
ping?

**Comment by j0k3r** [comment] 2015-11-23 17:10
I guess this issue won't be fixed in 1.x but it must be fixed in the v2.

**Comment by spitfire** [comment] 2015-12-01 17:54
I had the same problem on my local server. I'm using nginx and all it says is:
*1 upstream timed out (60: Operation timed out) while reading response header from upstream, client: Client IP, server: servr.fqdn, request: "GET /?import HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock", host: "Server IP", referrer: "http://Server IP/?import".

php-fpm log is not useful:
[01-Dec-2015 18:47:13] NOTICE: fpm is running, pid 69208
[01-Dec-2015 18:47:13] NOTICE: ready to handle connections

any way to push this manually?

Does v2 support importing from *anything* yet?

**Comment by j0k3r** [comment] 2015-12-01 17:56
@spitfire We are working on different solution. See https://github.com/wallabag/wallabag/pull/1443 & https://github.com/wallabag/wallabag/pull/1493

**Comment by spitfire** [comment] 2015-12-01 17:59
@j0k3r that's great, but how do I get my v1 server to parse it first?

**Comment by j0k3r** [comment] 2015-12-01 18:00
Well, I think you shouldn't try that on your v1 but on the v2 (when it will be released). From what kind of source do you extract your data?

**Comment by spitfire** [comment] 2015-12-01 18:09
1st source I used was a 44K Installer exported "instapaper-export.html" (it processed fine)
2nd file was from Pocket  - 776K "ril_export.html"

If I understood you correctly I should be able to import a v1-exported json file in v2.
I have both versions up and running in separate FreeBSD jails.

Now I'd like to at least get through importing it in v1.

**Comment by j0k3r** [comment] 2015-12-01 18:41
In fact, you should be able to import v1 exported file, but also Pocket, Readability, Instapaper, etc .. in the v2 (when it'll be available).
From now, there is no import tool in the v2.

Regarding the import on the v1, I've no idea. Did you take a look at https://github.com/wallabag/wallabag/issues/530 ?

**Comment by spitfire** [comment] 2015-12-01 20:01
I've tried increasing nearly all limits in php.ini (and the one suggested for nginx.conf), splitting it by 200 entries at a time, but still hit the same error. Any ideas?

**Comment by tcitworld** [comment] 2015-12-01 20:14
> and the one suggested for nginx.conf

I think it's especially the `fastcgi_read_timeout` that needs to be increased.

**Comment by spitfire** [comment] 2015-12-01 23:07
@tcitworld I don't think it matters in my case (I have set it to 3000 anyways) - as I can see php-fpm process peaking on one cpu. It must be choking on processing those urls. Maybe parser has problems with parsing some specific urls? I can send you my Pocket export if that would help (but I'd rather not put it here to be available for anyone).

**Comment by tcitworld** [comment] 2015-12-02 07:03
Yeah, I think to remember it causes problems if URL are unreachable and/or don't return a proper http error code. You can send your pocket file at tcit at tcit dot fr, I'll have a look if it fails on specific URLs.

**Comment by spitfire** [comment] 2015-12-02 07:59
@tcitworld just sent both exports to you. Hope you'll find what's making Wallaby choke on them.

**Comment by spitfire** [comment] 2015-12-06 12:46
@tcitworld any news on that? Did you find out what was causing the import to fail?

**Comment by tcitworld** [comment] 2015-12-06 16:44
Yup, I did manage to find to find the URL that was causing the issue, but since ~~I'm stupid~~ I forgot to note which one it was, so I'm running it again now. ;-)

**Comment by spitfire** [comment] 2015-12-06 18:08
Are you planning on attempting to fix it (on the 1.x branch) or you'll just tell me which url I need to get rid of?

**Comment by tcitworld** [comment] 2015-12-06 18:15
I found 2 more URLs that are causing issues for now, and I'm just half through the process. :)
These will not be fixed on v1.x, but v2 should handle these kind of errors just fine. I'll sent you the corrected file without the URLs causing trouble when the process will end.

**Comment by tcitworld** [comment] 2015-12-06 21:27
Okay, I think I have eliminated all of the problems. Currently re-importing one more time just to be sure it all goes right and I'm sending you the file back.

**Comment by anarcat** [comment] 2015-12-06 22:32
On 2015-12-02 02:03:57, Thomas Citharel wrote:
> Yeah, I think to remember it causes problems if URL are unreachable and/or don't return a proper http error code. You can send your pocket file at tcit at tcit dot fr, I'll have a look if it fails on specific URLs.

Is this something we can do on our own or you can do for more people? :)

**Comment by tcitworld** [comment] 2015-12-06 23:02
Sure, here's a how-to : 
Import your file normally. 
When encountering an issue (blank white page), return to wallabag's home by deleting `?import` in your browser address field. 
Reconnect yourself. 
Go into the unread or the archive panel and try to find the first entry (so with a high paging number) named 'Click here to finish import' and note its original web address (just in case), then delete it. 
Finally, click on 'Click here to finish import' on any entry and wait to see if you need to reproduce the process.

**Comment by anarcat** [comment] 2015-12-07 00:03
when uploading on framabag, i don't get *any* bookmarks imported...

**Comment by tcitworld** [comment] 2015-12-07 00:15
Well, send your file to me then, at the same address I've specified above, and I'll try and fix it. :-)

**Comment by nicosomb** [comment] 2016-01-24 09:19
This issue affects wallabag v1. This version won't move anymore.

**Closed by nicosomb** 2016-01-24 09:19 UTC
Labels: Bug

**Comment by anarcat** [comment] 2016-01-24 15:28
is framabag running 2.0 yet? or will it ever?

this issue was filed mostly to followup on on a bug there, since i couldn't figure out http://support.wallabag.org/ - should i take it there?
