### ISSUE TITLE
Bagging article breaks wallabag article page

### ISSUE THREAD

**Issue by nicofrand** [wallabag/wallabag#2834] opened 2017-02-03 10:05 UTC
### Issue details

All **wallabag** links (like delete or reload) inside the left menu of the article's view are incorrect.
The links on the home page (ex: delete) are OK.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.0
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable): NA
* php version: 5.6.27
* OS: Debian 8
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

1. Bag http://www.lhc-france.fr/l-aventure-humaine/la-bd-du-lhc/archives-la-bd-du-lhc/novembre-2016-je-voudrais-de-la
2. Open the imported article
3. Look at the "reload" or "delete" links: the domain is *lhc-france.fr* instead of the wallabag's domain

**Comment by Kdecherf** [comment] 2017-03-29 20:09
Another article which have the same issue: https://news.osu.edu/news/2017/03/06/tomatotires/

Interestingly I can't reproduce the issue on the current master (90f95027a8c713047fc436bce271cb3e52bc3dee)

**Comment by j0k3r** [comment] 2017-03-30 07:51
Same problem:

```html
<base href="https://news.osu.edu/"/> 
```

**Comment by nicosomb** [comment] 2017-03-31 09:28
> Interestingly I can't reproduce the issue on the current master (90f9502)

Is that fixed with a specific release of graby?

**Comment by Kdecherf** [comment] 2017-03-31 09:30
I will try to make a git bisect in the following days to be sure.

**Comment by j0k3r** [comment] 2017-03-31 14:46
Looks like it can possible to remove the `<base` node using `post_filters`: https://github.com/j0k3r/graby/pull/76

**Comment by Kdecherf** [comment] 2019-01-16 18:12
Hello there, I can't reproduce this issue anymore on 2.3.6. Is this issue still relevant?

**Closed** 2019-01-17 11:08 UTC
Labels: Bug, Site Config
