### ISSUE TITLE
login page cut in Qupzilla

### ISSUE THREAD

**Issue by valodiadeseynes** [wallabag/wallabag#1877] opened 2016-04-06 16:31 UTC
Hi,

On Qupzilla 1.6.6 (Debian Jessie 8.4) whenever I try to use Wallabag v2 I get this: https://i.imgur.com/TItozJV.png

The login console is cut in half and I'm even unable to fill the username field with the keyboard. I had no such issue with Wallabag v1.9 and this only appears to be a problem with Qupzilla (all works well on Firefox).

Thanks for the help.

**Comment by modos189** [comment] 2016-08-25 13:28
Qupzilla v1.8.9 (Webkit 538.1, Debian unstable)
The problem is not observed, but corrected the centering of the login form centered in WebKit in #2238

**Comment by j0k3r** [comment] 2016-08-26 05:25
Should be fixed in the next release.
Thanks for the report 👍

**Closed by j0k3r** 2016-08-26 05:25 UTC
Labels: Bug, UI
