### ISSUE TITLE
Bulk edit articles

### ISSUE THREAD

**Issue by bronwynlewis** [wallabag/wallabag#1646] opened 2016-02-04 17:29 UTC
Would be awesome to be able to select multiple articles to add the same tag, delete, or mark as read.

**Comment by j0k3r** [comment] 2016-02-04 19:13
Good idea :+1:

**Comment by nicofrand** [comment] 2017-02-17 08:58
Duplicate of #1232 (except for delete/mark as read)

**Closed** 2017-02-17 08:59 UTC
Labels: Improvement
