### ISSUE TITLE
Saved PNG broken?

### ISSUE THREAD

**Issue by Rurik19** [wallabag/wallabag#2886] opened 2017-02-15 08:33 UTC
It seems that png gets broken when saving in assets:
![image](https://cloud.githubusercontent.com/assets/1955806/22960592/bfd759aa-f360-11e6-8894-57bb50f2eb18.png)
[source image here](https://habrastorage.org/files/c1a/863/324/c1a863324bfa4aa4bfc7074eb3e17902.png)
[saved image](https://wallabag2.wst174.ru/assets/images/8/4/84e45fdc/55322027.png)

**Comment by nicosomb** [comment] 2017-02-15 08:37
![capture d ecran 2017-02-15 a 09 34 16](https://cloud.githubusercontent.com/assets/121870/22966329/06a50016-f362-11e6-8ea0-e49d0f15302b.png)

I tried locally and on wallabag.it and it seems ok for me. 

Did you install php GD extension?

**Comment by Rurik19** [comment] 2017-02-15 08:40
> Did you install php GD extension?
![image](https://cloud.githubusercontent.com/assets/1955806/22966497/3ab674c6-f384-11e6-919e-4dd13375a79f.png)

**Comment by Rurik19** [comment] 2017-02-15 08:44
Just checked on app.wallabag.it - saves OK.

**Comment by j0k3r** [comment] 2017-02-15 08:45
Did you enable saving images?

**Comment by Rurik19** [comment] 2017-02-15 08:56
@j0k3r espesially - no, but as url returned is from /assets - it is enabled? Where to check that?

**Comment by j0k3r** [comment] 2017-02-15 09:02
Defined in internal settings > Misc > Download images locally

If it's enabled, then your issue is a duplicate of https://github.com/wallabag/wallabag/issues/2805

**Comment by Rurik19** [comment] 2017-02-15 09:06
Yes. It is enabled. Checked that url from #2805, it losts transparency.

**Closed** 2017-02-15 09:08 UTC
Labels: Awaiting response
