### ISSUE TITLE
ActivityPub + Fediverse implementation

### ISSUE THREAD

**Issue by xplosionmind** [wallabag/wallabag#5483] opened 2021-11-14 21:35 UTC
**Is your feature request related to a problem? Please describe.**
Not related to any problem, but to issues #679 and #806.

**Describe the solution you'd like**
It would be great if links added to Wallabag (maybe only the ones set with a specific hashtag) could be automatically posted on the [Fediverse](https://fediverse.party), through the [ActivityPub](https://activitypub.rocks) protocol.

**Describe alternatives you've considered**
Manually sharing on other Fediverse platforms, such as [Mastodon](https://joinmastodon.org)

**Additional context**
Furthermore, since highlighting is enabled in Wallabag, it could be nice if the highlife words or sentences could be the text of the post, alongside the URL.

**Comment by j0k3r** [comment] 2022-01-06 19:16
Duplicate of #806

**Closed by j0k3r** 2022-01-06 19:16 UTC
Labels: Feature
